#!/usr/bin/env python3
"""Generate the power-of-ten tables of the MSVCR71 real parser port (lane WIN-1, engine/src/Common/INI/Msvcr71Pow10.inc).

MSVCR71's __multtenpow12 (0x7C37331E) multiplies by entries of two 12-byte tables (_pow10pos at 0x7C38F690, _pow10neg at 0x7C38F7F0): 10^(d * 8^g)
for d = 1..7, g = 0..4. The entries the parser can reach (|exponent| <= 5200, so g = 4 only with d = 1) are, after the routine's own correction
(a stored low word >= 0x8000 decrements the dword at offset 2), exactly 10^k rounded to the nearest 80-bit mantissa (ties to even): measured on
all 58 of them in the RotWK msvcr71.dll (tests/test_win1_msvcr71_real.cpp re-checks this against the installed DLL). So the table is computed here
from exact rational arithmetic instead of being copied from the DLL.

    python3 tools/sim/gen_msvcr71_pow10.py > engine/src/Common/INI/Msvcr71Pow10.inc
"""
from fractions import Fraction


def nearest80(k):
    """(80-bit mantissa with the leading 1 at bit 79, unbiased binary exponent) of 10^k rounded to nearest, ties to even."""
    t = Fraction(10) ** k
    e = t.numerator.bit_length() - t.denominator.bit_length()
    while Fraction(2) ** e > t:
        e -= 1
    while Fraction(2) ** (e + 1) <= t:
        e += 1
    s = t / Fraction(2) ** e * (1 << 79)
    fl = s.numerator // s.denominator
    r = s - fl
    m = fl + 1 if r > Fraction(1, 2) or (r == Fraction(1, 2) and fl & 1) else fl
    if m == 1 << 80:
        m >>= 1
        e += 1
    return m, e


def entry(k):
    m, e = nearest80(k)
    return "{ 0x%04X, 0x%08X, 0x%08X, 0x%04X }" % (m & 0xFFFF, (m >> 16) & 0xFFFFFFFF, m >> 48, e + 16383)


def main():
    print("// GENERATED by tools/sim/gen_msvcr71_pow10.py (lane WIN-1): 10^(d * 8^g), d = 1..7 per group g, rounded to the nearest 80-bit mantissa;")
    print("// { bytes 0-1, bytes 2-5, bytes 6-9, exponent } of the 12-byte value. Do not edit; regenerate.")
    for name, sign in (("kPow10Pos", 1), ("kPow10Neg", -1)):
        print("static const Ld12Entry %s[5][7] = {" % name)
        for g in range(5):
            row = []
            for d in range(1, 8):
                k = sign * d * 8 ** g
                row.append(entry(k) if abs(k) <= 4932 + 20 else "{ 0, 0, 0, 0 }")  # beyond the 80-bit range: never reached (|exponent| <= 5200)
            print("\t{ %s }," % ", ".join(row))
        print("};")


if __name__ == "__main__":
    main()
