#!/usr/bin/env python3
"""Generate the double-double constants of the deterministic sin / cos / atan2 (lane WIN-1, engine/src/Common/System/NumericTrig.inc).

Every constant is computed with Python's decimal module at 80 significant digits and split into a double-double (hi, lo): hi is the double
nearest the exact value, lo the double nearest the remainder. Printed as C++17 hexadecimal floating literals, so the table is exact text that
every compiler reads to the same bits.

    python3 tools/sim/gen_dd_trig_tables.py > engine/src/Common/System/NumericTrig.inc
    python3 tools/sim/gen_dd_trig_tables.py --golden > engine/tests/data/win1/trig_golden.txt   (the correctly rounded results the test pins)
"""
import random
import struct
import sys
from decimal import Decimal, getcontext

getcontext().prec = 80

SIN_TERMS = 14    # sin: r^1/1! .. r^27/27!  (|r| <= pi/4: the first omitted term is below 2^-104 of r)
COS_TERMS = 14    # cos: 1 .. r^26/26!
ATAN_TABLE = 64   # atan(k / 64), k = 0..64
ATAN_TERMS = 9    # atan(u) = u - u^3/3 + ... + u^17/17  (|u| <= 1/128: the first omitted term is below 2^-119 of u)


def atan_series(x):
    """atan(x) for |x| <= 0.2 by its Taylor series, to the context precision."""
    total, term, n, x2 = Decimal(0), x, 1, x * x
    while True:
        t = term / n
        if t == 0 or abs(t) < Decimal(10) ** -(getcontext().prec + 5):
            break
        total += t
        term = -term * x2
        n += 2
    return total


def atan(x):
    """atan(x), x >= 0: halve the argument (atan x = 2 atan(x / (1 + sqrt(1 + x^2)))) until it is small, then the series."""
    doublings = 0
    while x > Decimal("0.1"):
        x = x / (1 + (1 + x * x).sqrt())
        doublings += 1
    return atan_series(x) * (2 ** doublings)


PI = 16 * atan_series(Decimal(1) / 5) - 4 * atan_series(Decimal(1) / 239)  # Machin


def dd(v):
    hi = float(v)  # Decimal -> float is correctly rounded
    lo = float(v - Decimal(hi))
    return hi, lo


def lit(x):
    return "0.0" if x == 0 else x.hex()


def row(v):
    hi, lo = dd(v)
    return "{ %s, %s }" % (lit(hi), lit(lo))


def factorial(n):
    f = 1
    for i in range(2, n + 1):
        f *= i
    return f


def main():
    out = []
    out.append("// GENERATED by tools/sim/gen_dd_trig_tables.py (lane WIN-1): double-double constants { hi, lo } of the deterministic trigonometry in")
    out.append("// NumericState.cpp. Do not edit; regenerate.")
    out.append("static const DD kPi = %s;" % row(PI))
    out.append("static const DD kPiOver2 = %s;" % row(PI / 2))
    # 1/n! for the sin terms (n odd) and the cos terms (n even)
    out.append("// sin(r) = sum_k (-1)^k r^(2k+1) / (2k+1)!: the magnitudes 1/(2k+1)!, k = 0..%d" % (SIN_TERMS - 1))
    out.append("static const DD kSinCoef[%d] = {" % SIN_TERMS)
    for k in range(SIN_TERMS):
        out.append("\t%s, // 1/%d!" % (row(Decimal(1) / factorial(2 * k + 1)), 2 * k + 1))
    out.append("};")
    out.append("// cos(r) = sum_k (-1)^k r^(2k) / (2k)!: the magnitudes 1/(2k)!, k = 0..%d" % (COS_TERMS - 1))
    out.append("static const DD kCosCoef[%d] = {" % COS_TERMS)
    for k in range(COS_TERMS):
        out.append("\t%s, // 1/%d!" % (row(Decimal(1) / factorial(2 * k)), 2 * k))
    out.append("};")
    out.append("// atan(u) = sum_k (-1)^k u^(2k+1) / (2k+1): the magnitudes 1/(2k+1), k = 0..%d" % (ATAN_TERMS - 1))
    out.append("static const DD kAtanCoef[%d] = {" % ATAN_TERMS)
    for k in range(ATAN_TERMS):
        out.append("\t%s, // 1/%d" % (row(Decimal(1) / (2 * k + 1)), 2 * k + 1))
    out.append("};")
    out.append("// atan(k / %d), k = 0..%d" % (ATAN_TABLE, ATAN_TABLE))
    out.append("static const DD kAtanTable[%d] = {" % (ATAN_TABLE + 1))
    for k in range(ATAN_TABLE + 1):
        out.append("\t%s, // atan(%d/%d)" % (row(atan(Decimal(k) / ATAN_TABLE)), k, ATAN_TABLE))
    out.append("};")
    # 2/pi to 1216 bits for the full-range reduction (Payne-Hanek): word w holds the fraction bits 32w+1 .. 32w+32, most significant first
    two_over_pi = two_over_pi_bits(1216)
    out.append("// the bits of 2/pi after the binary point, 32 per word, most significant first (1216 bits)")
    out.append("static const std::uint32_t kTwoOverPiBits[38] = {")
    words = ["0x%08X" % ((two_over_pi >> (1216 - 32 * (w + 1))) & 0xFFFFFFFF) for w in range(38)]
    for i in range(0, 38, 8):
        out.append("\t" + ", ".join(words[i:i + 8]) + ",")
    out.append("};")
    print("\n".join(out))


def pi_integer(bits):
    """floor(pi * 2^bits) with integer Machin arithmetic (guard bits included)."""
    guard = 64
    one = 1 << (bits + guard)

    def arctan_inv(n):
        total, term, k, sign = 0, one // n, 1, 1
        n2 = n * n
        while term:
            total += sign * (term // k)
            term //= n2
            k += 2
            sign = -sign
        return total
    return (16 * arctan_inv(5) - 4 * arctan_inv(239)) >> guard


def two_over_pi_bits(bits):
    """floor(2/pi * 2^bits), exact: floor(2^(bits+1) / pi) from a pi with ample guard bits."""
    p = pi_integer(bits + 128)                   # pi * 2^(bits+128)
    return (1 << (2 * bits + 129)) // p >> 0     # 2^(bits+1) * 2^(bits+128) / (pi 2^(bits+128)) = 2/pi * 2^bits


def sin_cos(x):
    """sin(x), cos(x) of a Decimal: reduce by 2 pi to [-pi, pi], then the Taylor series."""
    two_pi = 2 * PI
    x = x - two_pi * (x / two_pi).to_integral_value()
    s, c, term, n = Decimal(0), Decimal(0), Decimal(1), 0
    while True:
        if n % 2 == 0:
            c += term if n % 4 == 0 else -term
        else:
            s += term if n % 4 == 1 else -term
        n += 1
        term = term * x / n
        if term == 0 or abs(term) < Decimal(10) ** -(getcontext().prec + 5):
            break
    return s, c


def atan2(y, x):
    if x == 0:
        return PI / 2 if y > 0 else -PI / 2
    if x > 0:
        a = atan(abs(y) / x)
        return a if y >= 0 else -a
    a = PI - atan(abs(y) / -x)
    return a if y >= 0 else -a


def golden():
    """Inputs the game feeds (float32 angles and coordinates, widened to double) and some plain doubles, with the correctly rounded results."""
    rng = random.Random(0x57494E31)
    f32 = lambda v: struct.unpack("<f", struct.pack("<f", v))[0]
    angles = [0.5, 1.0, -1.5707963705062866, 1.5707963705062866, 3.1415927410125732, -3.1415927410125732, 0.7853981852531433, 1e-8, -2.5e-30,
              6.2831854820251465, 100.0, -1000.25, 123456.0]
    for _ in range(1500):
        angles.append(f32(rng.uniform(-7.0, 7.0)))
    for _ in range(300):
        angles.append(rng.uniform(-50.0, 50.0))
    pairs = [(1.0, 1.0), (-1.0, 1.0), (1.0, -1.0), (-1.0, -1.0), (0.5, 1e-9), (1e-9, 0.5), (3.0, -4.0), (-0.0, -2.0)]
    for _ in range(1500):
        pairs.append((f32(rng.uniform(-3000.0, 3000.0)), f32(rng.uniform(-3000.0, 3000.0))))
    for _ in range(200):
        pairs.append((f32(rng.uniform(-1.0, 1.0)), f32(rng.uniform(-1.0, 1.0))))
    print("# GENERATED by tools/sim/gen_dd_trig_tables.py --golden (lane WIN-1): correctly rounded sin / cos / atan2 (80 digit decimal reference)")
    print("# s|c <x> <result>   or   a <y> <x> <result>   (hexadecimal doubles)")
    for x in angles:
        sv, cv = sin_cos(Decimal(x))
        print("s %s %s" % (x.hex(), float(sv).hex()))
        print("c %s %s" % (x.hex(), float(cv).hex()))
    for y, x in pairs:
        if y == 0 and x < 0:
            continue
        print("a %s %s %s" % (y.hex(), x.hex(), float(atan2(Decimal(y), Decimal(x))).hex()))
    # huge finite arguments (the full-range reduction, Sol r1): 1e20f, 1e30f, ..., DBL_MAX, at a precision that covers 2^1024
    global PI
    getcontext().prec = 700
    PI = Decimal(pi_integer(2300)) / (Decimal(2) ** 2300)
    huge = [float(f32(1e20)), float(f32(1e30)), float(f32(-3.4e38)), 1e22, 2.0 ** 60 + 1, 1e100, -1e200, 1e300, 1.7976931348623157e308, 5.0e15, 123456789.0, 2.0 ** 52]
    for _ in range(200):
        huge.append(rng.uniform(1.0, 2.0) * 2.0 ** rng.randint(21, 1023) * rng.choice([1, -1]))
    for x in huge:
        sv, cv = sin_cos(Decimal(x))
        print("s %s %s" % (x.hex(), float(sv).hex()))
        print("c %s %s" % (x.hex(), float(cv).hex()))


if __name__ == "__main__":
    if sys.argv[1:] == ["--golden"]:
        golden()
    else:
        main()
