using System.Reflection;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace OpenBFME.Launcher;

/// <summary>
/// Repo-tracked, pinned description of the retail payloads the optional third-party
/// provisioner is allowed to install: for every file, the relative install path, the
/// exact byte size, and the SHA-256 digest.
///
/// This is the trust anchor for <see cref="AllInOneRetailProvisioner"/>. The upstream
/// workshop listing supplies only transport (where to fetch a file); it never decides
/// what is acceptable. A file is written into the install tree only when its digest
/// matches an entry here.
///
/// The shipped manifest is intentionally EMPTY. Nobody on the OpenBFME side has
/// independently verified the digests of the upstream BFME II / RotWK payloads, and
/// inventing them would be worse than shipping none: it would launder an unverified
/// download behind a verification-shaped API. Empty means the provisioner refuses to
/// run — fail closed — until a maintainer populates it from payloads they have
/// actually hashed.
/// </summary>
public sealed class RetailPayloadManifest
{
    public const string ResourceName = "OpenBFME.Launcher.retail-payload-manifest.json";
    public const string SchemaId = "openbfme.retail-payload-manifest";
    public const int SupportedSchemaVersion = 1;

    /// <summary>One pinned file: where it lands, how big it is, and what it hashes to.</summary>
    public sealed record Entry(
        [property: JsonPropertyName("path")] string Path,
        [property: JsonPropertyName("size")] long Size,
        [property: JsonPropertyName("sha256")] string Sha256);

    public sealed record Payload(
        [property: JsonPropertyName("game")] string Game,
        [property: JsonPropertyName("language")] string Language,
        [property: JsonPropertyName("packageVersion")] string? PackageVersion,
        [property: JsonPropertyName("files")] List<Entry> Files);

    private sealed record Document(
        [property: JsonPropertyName("schema")] string? Schema,
        [property: JsonPropertyName("schemaVersion")] int SchemaVersion,
        [property: JsonPropertyName("//")] string[]? Note,
        [property: JsonPropertyName("payloads")] List<Payload>? Payloads);

    /// <summary>
    /// Written into every generated manifest so the file explains itself to whoever
    /// opens it next. Part of <see cref="Serialize"/> rather than hand-added, so
    /// re-pinning cannot silently drop it.
    /// </summary>
    private static readonly string[] FileNote =
    {
        "Pinned SHA-256 digests for the optional third-party retail download path.",
        "",
        "Generated by RetailPayloadManifest.PinFromInstall() from a maintainer's own",
        "lawfully owned BFME II / Rise of the Witch-king installations. This file",
        "contains NO retail content: a SHA-256 is a one-way fingerprint, not the bytes,",
        "and cannot be turned back into them. Only {path, size, sha256} is recorded.",
        "",
        "Do NOT populate this file by copying sizes or hashes out of a third-party",
        "workshop API response. That only re-states what the upstream host claims and",
        "leaves the verification with nothing external to check against. Digests must",
        "come from bytes a maintainer actually possesses and has hashed.",
        "",
        "Every downloaded file is checked against its 'sha256' before it is moved into",
        "the install tree; a mismatch aborts the run, deletes the partial, and reports",
        "the expected and actual digests. Files the upstream host lists but this",
        "manifest does not pin are never written. An empty 'payloads' list makes the",
        "download path refuse to run — that is the intended fail-closed state for any",
        "build whose digests have not been established."
    };

    private readonly IReadOnlyList<Payload> _payloads;

    private RetailPayloadManifest(IReadOnlyList<Payload> payloads) => _payloads = payloads;

    public IReadOnlyList<Payload> Payloads => _payloads;

    /// <summary>True when no payload is pinned, i.e. the provisioner must refuse to run.</summary>
    public bool IsEmpty => _payloads.Count == 0 || _payloads.All(p => p.Files.Count == 0);

    /// <summary>An empty manifest, for tests and for the "not populated" default.</summary>
    public static RetailPayloadManifest Empty { get; } = new(Array.Empty<Payload>());

    private static RetailPayloadManifest? _embedded;

    /// <summary>The manifest compiled into the launcher assembly.</summary>
    public static RetailPayloadManifest Embedded => _embedded ??= LoadEmbedded();

    private static RetailPayloadManifest LoadEmbedded()
    {
        var assembly = Assembly.GetExecutingAssembly();
        using var stream = assembly.GetManifestResourceStream(ResourceName);
        if (stream is null)
            throw new InvalidOperationException(
                $"Embedded resource '{ResourceName}' is missing. The launcher must not be " +
                "built without the pinned retail payload manifest; see RetailPayloadManifest.cs.");
        using var reader = new StreamReader(stream);
        return Parse(reader.ReadToEnd());
    }

    public static RetailPayloadManifest Parse(string json)
    {
        Document? document;
        try
        {
            document = JsonSerializer.Deserialize<Document>(json, new JsonSerializerOptions
            {
                ReadCommentHandling = JsonCommentHandling.Skip,
                AllowTrailingCommas = true
            });
        }
        catch (JsonException error)
        {
            throw new InvalidDataException(
                $"The pinned retail payload manifest is not valid JSON: {error.Message}");
        }
        if (document is null)
            throw new InvalidDataException("The pinned retail payload manifest was empty.");
        if (!string.Equals(document.Schema, SchemaId, StringComparison.Ordinal))
            throw new InvalidDataException(
                $"Retail payload manifest schema is '{document.Schema}', expected '{SchemaId}'.");
        if (document.SchemaVersion != SupportedSchemaVersion)
            throw new InvalidDataException(
                $"Retail payload manifest schemaVersion {document.SchemaVersion} is not supported " +
                $"(this launcher understands {SupportedSchemaVersion}).");

        var payloads = new List<Payload>();
        foreach (var payload in document.Payloads ?? new List<Payload>())
        {
            if (payload.Game is not ("bfme2" or "rotwk"))
                throw new InvalidDataException(
                    $"Retail payload manifest lists unknown game '{payload.Game}'.");
            if (string.IsNullOrWhiteSpace(payload.Language))
                throw new InvalidDataException(
                    $"Retail payload '{payload.Game}' has no language code.");
            var seen = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            foreach (var entry in payload.Files ?? new List<Entry>())
                ValidateEntry(payload, entry, seen);
            payloads.Add(payload with { Files = payload.Files ?? new List<Entry>() });
        }
        return new RetailPayloadManifest(payloads);
    }

    private static void ValidateEntry(Payload payload, Entry entry, HashSet<string> seen)
    {
        var relative = NormalizeRelativePath(entry.Path);
        if (relative is null)
            throw new InvalidDataException(
                $"Retail payload '{payload.Game}' pins an unsafe path '{entry.Path}'.");
        if (!seen.Add(relative))
            throw new InvalidDataException(
                $"Retail payload '{payload.Game}' pins '{relative}' more than once.");
        if (entry.Size <= 0)
            throw new InvalidDataException(
                $"Retail payload '{payload.Game}' entry '{relative}' has no positive size.");
        if (!IsSha256Hex(entry.Sha256))
            throw new InvalidDataException(
                $"Retail payload '{payload.Game}' entry '{relative}' does not carry a " +
                "64-character hexadecimal SHA-256 digest.");
    }

    public static bool IsSha256Hex(string? value)
    {
        if (value is null || value.Length != 64) return false;
        foreach (var c in value)
            if (!((c >= '0' && c <= '9') || (c >= 'a' && c <= 'f') || (c >= 'A' && c <= 'F')))
                return false;
        return true;
    }

    /// <summary>
    /// Normalise a manifest/workshop relative path to the platform separator, or return
    /// null when it escapes the install root. Shared with the provisioner so a pinned
    /// entry and a downloaded file are keyed identically.
    /// </summary>
    public static string? NormalizeRelativePath(string? name)
    {
        if (string.IsNullOrWhiteSpace(name)) return null;
        var trimmed = name.Replace('/', System.IO.Path.DirectorySeparatorChar)
            .Replace('\\', System.IO.Path.DirectorySeparatorChar)
            .Trim()
            .TrimStart(System.IO.Path.DirectorySeparatorChar);
        if (trimmed.Length == 0) return null;
        var separator = System.IO.Path.DirectorySeparatorChar;
        if (trimmed == ".." ||
            trimmed.StartsWith(".." + separator, StringComparison.Ordinal) ||
            trimmed.Contains(separator + ".." + separator, StringComparison.Ordinal) ||
            trimmed.EndsWith(separator + "..", StringComparison.Ordinal) ||
            System.IO.Path.IsPathRooted(trimmed))
            return null;
        return trimmed;
    }

    /// <summary>
    /// The pinned payload for a game/language, or a refusal explaining that nothing is
    /// pinned. This is the fail-closed door: no digests, no download.
    /// </summary>
    public Payload RequirePayload(string game, string language)
    {
        if (IsEmpty)
            throw new InvalidOperationException(
                "The pinned retail payload manifest is empty, so the optional download " +
                "path refuses to run. OpenBFME does not verify third-party game payloads " +
                "by size alone, and no maintainer has published SHA-256 digests for them " +
                "yet. Point the launcher at your own lawfully owned BFME II / RotWK " +
                "installation instead (Browse…), or populate " +
                "launcher/OpenBFME.Launcher/retail-payload-manifest.json with digests you " +
                "have verified yourself.");

        var code = (language ?? "").Trim();
        if (code.Length == 0) code = AllInOneRetailProvisioner.DefaultLanguageCode;
        var match = _payloads.FirstOrDefault(p =>
                        string.Equals(p.Game, game, StringComparison.OrdinalIgnoreCase) &&
                        string.Equals(p.Language, code, StringComparison.OrdinalIgnoreCase))
                    ?? _payloads.FirstOrDefault(p =>
                        string.Equals(p.Game, game, StringComparison.OrdinalIgnoreCase) &&
                        string.Equals(p.Language, "ALL", StringComparison.OrdinalIgnoreCase));
        if (match is null || match.Files.Count == 0)
            throw new InvalidOperationException(
                $"No retail payload is pinned for {game} in language '{code}'. The download " +
                "path refuses to install files it cannot verify against a published digest.");
        return match;
    }

    /// <summary>
    /// Build a payload block by hashing an installation a maintainer already has and
    /// trusts. This is the only honest way out of the empty-manifest refusal: digests
    /// must come from bytes someone verified, not from what a download host asserts
    /// about its own files.
    /// </summary>
    public static Payload PinFromInstall(
        string game, string language, string installDirectory, string? packageVersion = null)
    {
        if (game is not ("bfme2" or "rotwk"))
            throw new ArgumentOutOfRangeException(nameof(game), game, "Expected bfme2 or rotwk.");
        var root = System.IO.Path.GetFullPath(installDirectory);
        if (!Directory.Exists(root))
            throw new DirectoryNotFoundException($"No installation at {root}.");

        var files = new List<Entry>();
        foreach (var file in Directory.EnumerateFiles(root, "*", SearchOption.AllDirectories)
                     .OrderBy(p => p, StringComparer.OrdinalIgnoreCase))
        {
            var relative = NormalizeRelativePath(System.IO.Path.GetRelativePath(root, file));
            if (relative is null) continue;
            // Skip our own bookkeeping and any interrupted download.
            if (relative.EndsWith(".part", StringComparison.OrdinalIgnoreCase)) continue;
            if (relative.Equals("openbfme-provision.json", StringComparison.OrdinalIgnoreCase)) continue;
            var info = new FileInfo(file);
            if (info.Length <= 0) continue;
            using var stream = File.OpenRead(file);
            var hash = System.Security.Cryptography.SHA256.HashData(stream);
            files.Add(new Entry(
                relative.Replace(System.IO.Path.DirectorySeparatorChar, '/'),
                info.Length,
                Convert.ToHexString(hash).ToLowerInvariant()));
        }
        if (files.Count == 0)
            throw new InvalidDataException($"No files found under {root} to pin.");
        return new Payload(game, language.Trim().ToUpperInvariant(), packageVersion, files);
    }

    /// <summary>Serialise payloads back into the on-disk manifest shape.</summary>
    public static string Serialize(IEnumerable<Payload> payloads) =>
        JsonSerializer.Serialize(
            new Document(SchemaId, SupportedSchemaVersion, FileNote, payloads.ToList()),
            new JsonSerializerOptions
            {
                WriteIndented = true,
                // Keep the note and any punctuation readable in the committed file
                // rather than \u-escaped. This manifest is meant to be reviewed by eye.
                Encoder = System.Text.Encodings.Web.JavaScriptEncoder.UnsafeRelaxedJsonEscaping
            }) + "\n";

    /// <summary>Index a payload by normalised relative path.</summary>
    public static IReadOnlyDictionary<string, Entry> Index(Payload payload)
    {
        var map = new Dictionary<string, Entry>(StringComparer.OrdinalIgnoreCase);
        foreach (var entry in payload.Files)
        {
            var relative = NormalizeRelativePath(entry.Path);
            if (relative is not null) map[relative] = entry;
        }
        return map;
    }
}
