// OpenBFME. GPL-3.0.
//
// AudioAssetCache: finds audio files through the archive file system exactly as retail names them (the virtual path generated by
// AudioEventRTS) and keeps decoded sounds under a memory budget.
//
// Retail (Miles, RW MilesAudioManager: the AudioFootprintInBytes setting, 8 MB) caches the COMPRESSED file bytes and decodes while
// playing. This cache keeps decoded PCM (the device needs PCM), so its budget is a multiple of the footprint setting (the IMA ADPCM
// expansion is 4x): INFERENCE, stop S-249. Streams (music, dialog, ambient) are not cached: the device reads them through
// readFile() and an Mp3Stream.
//
// No fallbacks: a missing file or a decode failure is returned as an error string and counted in the report; nothing is substituted.

#pragma once

#include "Common/ArchiveFileSystem.h"
#include "Common/Audio/AudioDecode.h"

#include <cstdint>
#include <list>
#include <memory>
#include <string>
#include <unordered_map>
#include <vector>

class AudioAssetCache
{
public:
	AudioAssetCache(ArchiveFileSystem *files, std::uint64_t decodedBudgetBytes);

	bool exists(const std::string &virtualPath) const;
	// The raw bytes of the file (shared, kept alive by the caller). Null + *error when missing.
	std::shared_ptr<const std::vector<std::uint8_t>> readFile(const std::string &virtualPath, std::string *error);
	// Header info (frames, rate, channels) without decoding; for MP3 an exact walk of the frame headers.
	bool probe(const std::string &virtualPath, AudioDecode::AudioInfo *info, std::string *error);
	// The decoded file. Null + *error when missing or when decoding fails.
	std::shared_ptr<const AudioDecode::DecodedAudio> decoded(const std::string &virtualPath, std::string *error);
	// Length in milliseconds (probe), -1 and *error when unavailable.
	double lengthMs(const std::string &virtualPath, std::string *error);

	struct Stats
	{
		std::uint64_t hits = 0;
		std::uint64_t misses = 0;
		std::uint64_t decodes = 0;
		std::uint64_t evictions = 0;
		double decodeMilliseconds = 0.0;
		std::uint64_t bytesCached = 0;
		std::uint64_t peakBytesCached = 0;
		std::uint64_t errors = 0;
	};
	const Stats &stats() const { return m_stats; }
	void clear();

private:
	struct Entry
	{
		std::shared_ptr<const AudioDecode::DecodedAudio> audio;
		std::list<std::string>::iterator lru;
		std::uint64_t bytes = 0;
	};

	ArchiveFileSystem *m_files;
	std::uint64_t m_budget;
	std::unordered_map<std::string, Entry> m_entries; // key: lower-case path
	std::list<std::string> m_lru;                      // most recent first
	Stats m_stats;
};
