// OpenBFME: faithful rebuild of The Battle for Middle-earth II: Rise of the Witch-king 2.01.
// Derived from Command & Conquer Generals Zero Hour, (c) 2001-2003 Electronic Arts Inc., GPL-3.0.

#include "Libraries/WWVegas/WW3D2/w3dchunks.h"
#include "Libraries/WWVegas/WW3D2/w3d_file.h"
#include "Libraries/WWVegas/WWLib/chunkio.h"

#include <algorithm>

namespace
{

struct ChunkName
{
	std::uint32_t Id;
	const char *Name;
};

#define N(x) { x, #x }

// Every id in w3d_file.h, ascending. Obsolete ids keep their ZH OBSOLETE_ prefix.
const ChunkName kChunkNames[] = {
	N(W3D_CHUNK_MESH),
	N(W3D_CHUNK_VERTICES),
	N(W3D_CHUNK_VERTEX_NORMALS),
	N(W3D_CHUNK_MESH_USER_TEXT),
	N(W3D_CHUNK_VERTEX_INFLUENCES),
	N(W3D_CHUNK_MESH_HEADER3),
	N(W3D_CHUNK_TRIANGLES),
	N(W3D_CHUNK_VERTEX_SHADE_INDICES),
	N(W3D_CHUNK_PRELIT_UNLIT),
	N(W3D_CHUNK_PRELIT_VERTEX),
	N(W3D_CHUNK_PRELIT_LIGHTMAP_MULTI_PASS),
	N(W3D_CHUNK_PRELIT_LIGHTMAP_MULTI_TEXTURE),
	N(W3D_CHUNK_MATERIAL_INFO),
	N(W3D_CHUNK_SHADERS),
	N(W3D_CHUNK_VERTEX_MATERIALS),
	N(W3D_CHUNK_VERTEX_MATERIAL),
	N(W3D_CHUNK_VERTEX_MATERIAL_NAME),
	N(W3D_CHUNK_VERTEX_MATERIAL_INFO),
	N(W3D_CHUNK_VERTEX_MAPPER_ARGS0),
	N(W3D_CHUNK_VERTEX_MAPPER_ARGS1),
	N(W3D_CHUNK_TEXTURES),
	N(W3D_CHUNK_TEXTURE),
	N(W3D_CHUNK_TEXTURE_NAME),
	N(W3D_CHUNK_TEXTURE_INFO),
	N(W3D_CHUNK_MATERIAL_PASS),
	N(W3D_CHUNK_VERTEX_MATERIAL_IDS),
	N(W3D_CHUNK_SHADER_IDS),
	N(W3D_CHUNK_DCG),
	N(W3D_CHUNK_DIG),
	N(W3D_CHUNK_SCG),
	N(W3D_CHUNK_SHADER_MATERIAL_ID),
	N(W3D_CHUNK_TEXTURE_STAGE),
	N(W3D_CHUNK_TEXTURE_IDS),
	N(W3D_CHUNK_STAGE_TEXCOORDS),
	N(W3D_CHUNK_PER_FACE_TEXCOORD_IDS),
	N(W3D_CHUNK_SHADER_MATERIALS),
	N(W3D_CHUNK_SHADER_MATERIAL),
	N(W3D_CHUNK_SHADER_MATERIAL_HEADER),
	N(W3D_CHUNK_SHADER_MATERIAL_PROPERTY),
	N(W3D_CHUNK_DEFORM),
	N(W3D_CHUNK_DEFORM_SET),
	N(W3D_CHUNK_DEFORM_KEYFRAME),
	N(W3D_CHUNK_DEFORM_DATA),
	N(W3D_CHUNK_TANGENTS),
	N(W3D_CHUNK_BITANGENTS),
	N(W3D_CHUNK_PS2_SHADERS),
	N(W3D_CHUNK_AABTREE),
	N(W3D_CHUNK_AABTREE_HEADER),
	N(W3D_CHUNK_AABTREE_POLYINDICES),
	N(W3D_CHUNK_AABTREE_NODES),
	N(W3D_CHUNK_HIERARCHY),
	N(W3D_CHUNK_HIERARCHY_HEADER),
	N(W3D_CHUNK_PIVOTS),
	N(W3D_CHUNK_PIVOT_FIXUPS),
	N(W3D_CHUNK_ANIMATION),
	N(W3D_CHUNK_ANIMATION_HEADER),
	N(W3D_CHUNK_ANIMATION_CHANNEL),
	N(W3D_CHUNK_BIT_CHANNEL),
	N(W3D_CHUNK_COMPRESSED_ANIMATION),
	N(W3D_CHUNK_COMPRESSED_ANIMATION_HEADER),
	N(W3D_CHUNK_COMPRESSED_ANIMATION_CHANNEL),
	N(W3D_CHUNK_COMPRESSED_BIT_CHANNEL),
	N(W3D_CHUNK_COMPRESSED_ANIMATION_MOTION_CHANNEL),
	N(W3D_CHUNK_MORPH_ANIMATION),
	N(W3D_CHUNK_MORPHANIM_HEADER),
	N(W3D_CHUNK_MORPHANIM_CHANNEL),
	N(W3D_CHUNK_MORPHANIM_POSENAME),
	N(W3D_CHUNK_MORPHANIM_KEYDATA),
	N(W3D_CHUNK_MORPHANIM_PIVOTCHANNELDATA),
	N(W3D_CHUNK_HMODEL),
	N(W3D_CHUNK_HMODEL_HEADER),
	N(W3D_CHUNK_NODE),
	N(W3D_CHUNK_COLLISION_NODE),
	N(W3D_CHUNK_SKIN_NODE),
	N(OBSOLETE_W3D_CHUNK_HMODEL_AUX_DATA),
	N(OBSOLETE_W3D_CHUNK_SHADOW_NODE),
	N(W3D_CHUNK_LODMODEL),
	N(W3D_CHUNK_LODMODEL_HEADER),
	N(W3D_CHUNK_LOD),
	N(W3D_CHUNK_COLLECTION),
	N(W3D_CHUNK_COLLECTION_HEADER),
	N(W3D_CHUNK_COLLECTION_OBJ_NAME),
	N(W3D_CHUNK_PLACEHOLDER),
	N(W3D_CHUNK_TRANSFORM_NODE),
	N(W3D_CHUNK_POINTS),
	N(W3D_CHUNK_LIGHT),
	N(W3D_CHUNK_LIGHT_INFO),
	N(W3D_CHUNK_SPOT_LIGHT_INFO),
	N(W3D_CHUNK_NEAR_ATTENUATION),
	N(W3D_CHUNK_FAR_ATTENUATION),
	N(W3D_CHUNK_EMITTER),
	N(W3D_CHUNK_EMITTER_HEADER),
	N(W3D_CHUNK_EMITTER_USER_DATA),
	N(W3D_CHUNK_EMITTER_INFO),
	N(W3D_CHUNK_EMITTER_INFOV2),
	N(W3D_CHUNK_EMITTER_PROPS),
	N(OBSOLETE_W3D_CHUNK_EMITTER_COLOR_KEYFRAME),
	N(OBSOLETE_W3D_CHUNK_EMITTER_OPACITY_KEYFRAME),
	N(OBSOLETE_W3D_CHUNK_EMITTER_SIZE_KEYFRAME),
	N(W3D_CHUNK_EMITTER_LINE_PROPERTIES),
	N(W3D_CHUNK_EMITTER_ROTATION_KEYFRAMES),
	N(W3D_CHUNK_EMITTER_FRAME_KEYFRAMES),
	N(W3D_CHUNK_EMITTER_BLUR_TIME_KEYFRAMES),
	N(W3D_CHUNK_EMITTER_EXTRA_INFO),
	N(W3D_CHUNK_AGGREGATE),
	N(W3D_CHUNK_AGGREGATE_HEADER),
	N(W3D_CHUNK_AGGREGATE_INFO),
	N(W3D_CHUNK_TEXTURE_REPLACER_INFO),
	N(W3D_CHUNK_AGGREGATE_CLASS_INFO),
	N(W3D_CHUNK_HLOD),
	N(W3D_CHUNK_HLOD_HEADER),
	N(W3D_CHUNK_HLOD_LOD_ARRAY),
	N(W3D_CHUNK_HLOD_SUB_OBJECT_ARRAY_HEADER),
	N(W3D_CHUNK_HLOD_SUB_OBJECT),
	N(W3D_CHUNK_HLOD_AGGREGATE_ARRAY),
	N(W3D_CHUNK_HLOD_PROXY_ARRAY),
	N(W3D_CHUNK_BOX),
	N(W3D_CHUNK_SPHERE),
	N(W3D_CHUNK_RING),
	N(W3D_CHUNK_NULL_OBJECT),
	N(W3D_CHUNK_LIGHTSCAPE),
	N(W3D_CHUNK_LIGHTSCAPE_LIGHT),
	N(W3D_CHUNK_LIGHT_TRANSFORM),
	N(W3D_CHUNK_DAZZLE),
	N(W3D_CHUNK_DAZZLE_NAME),
	N(W3D_CHUNK_DAZZLE_TYPENAME),
	N(W3D_CHUNK_SOUNDROBJ),
	N(W3D_CHUNK_SOUNDROBJ_HEADER),
	N(W3D_CHUNK_SOUNDROBJ_DEFINITION),
	N(W3D_CHUNK_SHDMESH),
	N(W3D_CHUNK_SHDMESH_NAME),
	N(W3D_CHUNK_SHDMESH_HEADER),
	N(W3D_CHUNK_SHDMESH_USER_TEXT),
	N(W3D_CHUNK_SHDSUBMESH),
	N(W3D_CHUNK_SHDSUBMESH_HEADER),
	N(W3D_CHUNK_SHDSUBMESH_SHADER),
	N(W3D_CHUNK_SHDSUBMESH_SHADER_CLASSID),
	N(W3D_CHUNK_SHDSUBMESH_SHADER_DEF),
	N(W3D_CHUNK_SHDSUBMESH_VERTICES),
	N(W3D_CHUNK_SHDSUBMESH_VERTEX_NORMALS),
	N(W3D_CHUNK_SHDSUBMESH_TRIANGLES),
	N(W3D_CHUNK_SHDSUBMESH_VERTEX_SHADE_INDICES),
	N(W3D_CHUNK_SHDSUBMESH_UV0),
	N(W3D_CHUNK_SHDSUBMESH_UV1),
	N(W3D_CHUNK_SHDSUBMESH_TANGENT_BASIS_S),
	N(W3D_CHUNK_SHDSUBMESH_TANGENT_BASIS_T),
	N(W3D_CHUNK_SHDSUBMESH_TANGENT_BASIS_SxT),
	N(W3D_CHUNK_SHDSUBMESH_VERTEX_COLOR),
	N(W3D_CHUNK_SHDSUBMESH_VERTEX_INFLUENCES),
	N(W3D_CHUNK_VERTICES_2),
	N(W3D_CHUNK_VERTEX_NORMALS_2),
	N(WWSHADE_CHUNK_SHDDEF_VARIABLES),
	N(WWSHADE_CHUNK_SIMPLE_VARIABLES),
	N(WWSHADE_CHUNK_GLOSSMASK_VARIABLES),
	N(WWSHADE_CHUNK_CUBEMAP_VARIABLES),
};

#undef N

const size_t kChunkNameCount = sizeof(kChunkNames) / sizeof(kChunkNames[0]);

void walk(ChunkLoadClass &cload, std::uint32_t parent, W3DChunkWalkStats &stats)
{
	while (cload.Open_Chunk())
	{
		std::uint32_t id = cload.Cur_Chunk_ID();
		std::uint32_t size = cload.Cur_Chunk_Length();
		W3DChunkStat &stat = stats.ById[id];
		stat.Count++;
		stat.Bytes += size;
		stats.ByParent[std::make_pair(parent, id)]++;
		if (!W3D_Chunk_Is_Known(id))
		{
			stats.Unknown.push_back(id);
		}
		if (cload.Contains_Chunks())
		{
			walk(cload, id, stats);
		}
		cload.Close_Chunk();
	}
}

} // namespace

const char *W3D_Chunk_Name(std::uint32_t id)
{
	const ChunkName *end = kChunkNames + kChunkNameCount;
	const ChunkName *it = std::lower_bound(kChunkNames, end, id, [](const ChunkName &c, std::uint32_t v) { return c.Id < v; });
	return (it != end && it->Id == id) ? it->Name : nullptr;
}

std::vector<std::uint32_t> W3D_Chunk_All_Ids()
{
	std::vector<std::uint32_t> ids;
	for (const ChunkName &c : kChunkNames)
	{
		ids.push_back(c.Id);
	}
	return ids;
}

void W3DChunkWalkStats::Merge(const W3DChunkWalkStats &other)
{
	for (const auto &kv : other.ById)
	{
		W3DChunkStat &s = ById[kv.first];
		s.Count += kv.second.Count;
		s.Bytes += kv.second.Bytes;
	}
	for (const auto &kv : other.ByParent)
	{
		ByParent[kv.first] += kv.second;
	}
	Unknown.insert(Unknown.end(), other.Unknown.begin(), other.Unknown.end());
}

bool Walk_W3D_Chunks(const std::uint8_t *data, size_t size, W3DChunkWalkStats &stats, std::string *error)
{
	ChunkLoadClass cload(data, size);
	walk(cload, W3DChunkWalkStats::ROOT, stats);
	if (cload.Had_Error())
	{
		if (error)
		{
			*error = "a chunk overruns its parent or the file, or a partial chunk header trails";
		}
		return false;
	}
	return true;
}
