## Lane AIO-1: installing the game files from the All In One BFME Launcher's download service (the BFME Foundation Project's and the
## Patch 2.22 team's), with the player's consent. On by default since round 3 (DEFAULT_ENABLED); nothing downloads without the
## player's click on Download (the window's Download the games screen). The owner
## approved using this service directly on 2026-10-10 (docs/AIO.md, "Decisions"). Today it installs the original versions only: the
## packages of scripts/core/aio_pins.gd ("original-RotWK" = Vanilla 2.01, "original-BFME2" = Vanilla 1.06). The code is package-generic
## (a guid, its file list, the checks); a mod would be one more row in that table.
##
## The service, as the AIO launcher's open-source WorkshopKit uses it (github.com/MarcellVokk/BfmeFoundationProject; observed 2026-10-10):
##   * GET https://bfmeladder.com/api/workshop/download?guid=<package> with the headers AuthAccountUuid: unauthenticated and
##     AuthAccountPassword: (empty) (BfmeWorkshopDownloadManager.Download, HttpUtils.GetJson, BfmeWorkshopAuthInfo.Unauthenticated):
##     a JSON BfmeWorkshopEntry {Guid, Name, Version, Game, Type, Owner, Files: [{Guid, Name, Url, Md5, Language, Size}]};
##   * every file at https://workshop-files.bfmeladder.com/<Owner>/<Md5> (content-addressed; Range requests are answered with 206);
##   * a file is installed when its Language is ALL or the game's language (BfmeWorkshopSyncManager.AddFiles).
## Our rules on top (not the AIO launcher's):
##   * the service's word is not enough: every file the install takes is pinned with its name, MD5 and size (scripts/core/aio_pins.gd,
##     generated by tools/release/aio_pins.py from tools/release/aio_package_files.json: all 612 English files, checked against
##     engine/data/retail-archives); a listed file that is not pinned, a pinned file that is not listed, another MD5, a non-zero Size
##     other than the pinned one, a fractional number, a URL other than the pinned <files host>/<owner>/<md5> (the owner is pinned per
##     package: the owner's decision, "pin them for now") all stop the install before any file is requested; the pinned size is used
##     (the service lists some files with Size 0, RotWK's lang\EnglishAudio.big among them); a file already on disk must have the
##     pinned size and MD5;
##   * anything we do not recognise (an HTTP status, a body that is not the expected JSON, a moved or missing file, a wrong MD5) stops
##     with a message naming the file and what the player can do (REMEDY); never a guess, never a silent fallback;
##   * every file is downloaded to <name>.part (resumed with Range: pause / resume), its MD5 checked, then renamed; a failed file is
##     deleted; nothing is deleted that this launcher did not write, no registry key is written, no AIO program is run;
##   * only the English tables exist, so only the English files are installed.
## Afterwards the folders go to the game: <game user dir>/downloaded-installs.cfg (InstallLocator::kDownloadedMarkerName), which the
## first-run screen offers as found installs; the player still confirms them and the mount checks every archive (PLAN rule 10).
extends RefCounted

const NetPolicy := preload("res://scripts/net/net_policy.gd")
const Pins := preload("res://scripts/core/aio_pins.gd")
const Log := preload("res://scripts/core/launcher_log.gd")
const GameOptions := preload("res://scripts/core/game_options.gd")

## The one switch: on since round 3 (the owner wants the download offered; nothing downloads without the player's consent and click).
## The player's setting overrides it either way.
const DEFAULT_ENABLED := true

const SERVICE := "https://bfmeladder.com"                      # WorkshopKit BfmeWorkshopManager.WorkshopServerHost
const FILES := "https://workshop-files.bfmeladder.com"         # WorkshopKit BfmeWorkshopManager.WorkshopFilesHost
const HOSTS := ["bfmeladder.com", "workshop-files.bfmeladder.com"]
const PAGE := "https://bfmeladder.com/download"                 # the project's download page (shown in the consent)
const PROJECT := "the All In One BFME Launcher (the BFME Foundation Project and the Patch 2.22 team)"
const REMEDY := "Try again later. Or install the games with the All In One BFME Launcher yourself (%s) and pick their folders when OpenBFME asks." % PAGE
const MAX_MANIFEST := 4 * 1024 * 1024
const RECORD := "aio-install.json"
const MARKER := "downloaded-installs.cfg"   # InstallLocator::kDownloadedMarkerName
# outcome kinds: the command line maps them to exit codes 1, 2, 3, 2
const REFUSED := "refused"    # the setting is off, no consent, a bad folder, too little space
const NETWORK := "network"    # the service could not be reached or a download broke (it resumes next time)
const REJECTED := "rejected"  # the service answered something we do not recognise, or its data failed a check
const STOPPED := "stopped"    # the player paused or cancelled

var updater  # Updater (scripts/core/updater.gd): its state, HTTP client, network policy, progress callback and data folder
var service := SERVICE
var files_origin := FILES
var packages: Array = Pins.PACKAGES
var stop_request := ""  # "pause" or "cancel", set from the UI thread (with updater.http.cancelled)
var test_stop_after := ""  # tests: "<folder>/<file>:<pause|cancel>" asks for a stop right after that file was checked and kept


func _init(u) -> void:
	updater = u


func enabled() -> bool:
	return updater.state.get_value("aio", "enabled", DEFAULT_ENABLED) == true


func set_enabled(on: bool) -> void:
	updater.state.set_value("aio", "enabled", on)
	updater._save_state()


## Tests: one loopback server plays both of the service's hosts. "" or why not.
func set_test_origin(origin: String) -> String:
	var why := NetPolicy.check_test_origin(origin)
	if why != "":
		return why
	service = origin
	files_origin = origin
	updater.policy.test_origin = origin
	return ""


## Tests: pinned tables of made-up files instead of the retail ones (a JSON array in aio_pins.gd's PACKAGES form). "" or why not.
func set_test_pins(path: String) -> String:
	var d = JSON.parse_string(FileAccess.get_file_as_string(path))
	if typeof(d) != TYPE_ARRAY or d.is_empty():
		return "the test pins %s are not a JSON array of packages" % path
	packages = d
	return ""


func total_size() -> int:
	var n := 0
	for p in packages:
		n += int(p.get("bytes", 0))
	return n


## What the player's Download press (the window) or --aio-consent (the command line) agrees to; logged with the consent. Lane UI-3: the
## window shows one line naming the source and a link instead, and no ownership checkbox (the owner, 2026-10-10: "just let people
## figure that out").
func consent_text() -> String:
	var lines := PackedStringArray()
	lines.append("The game files are downloaded from the servers of %s, %s and %s. They do not come from EA or from OpenBFME." % [PROJECT, SERVICE.trim_prefix("https://"), FILES.trim_prefix("https://")])
	for p in packages:
		lines.append("  %s: their package \"%s\" (%s)" % [p.label, p.name, p.guid])
	lines.append("About %.1f GB. Every archive is checked against OpenBFME's own list before it is kept. OpenBFME sends those servers only " % (total_size() / 1e9) +
		"its name and version; their privacy policy (bfmeladder.com/privacy) applies to their servers.")
	return "\n".join(lines)


func _report(text: String, done := -1, total := -1) -> void:
	updater._report(text, done, total)


static func _fail(kind: String, error: String) -> Dictionary:
	return {"ok": false, "kind": kind, "error": error}


## a failure the player can do something about: the message, then what to do
static func _broken(kind: String, error: String) -> Dictionary:
	return _fail(kind, "%s %s" % [error, REMEDY])


## The plain relative path of a manifest file name ("lang\\English.big" -> "lang/English.big"), or "" when it is not one (absolute,
## a drive, "..", ".", an empty or Windows-invalid component, characters outside printable ASCII).
static func safe_relative(name: String) -> String:
	var rel := name.replace("\\", "/")
	if rel.is_empty() or rel.begins_with("/") or rel.length() > 240:
		return ""
	for c in rel:
		var u := c.unicode_at(0)
		if u < 0x20 or u >= 0x7f or c in [":", "*", "?", "\"", "<", ">", "|"]:
			return ""
	for part in rel.split("/"):
		if part in ["", ".", ".."] or part.ends_with(" ") or part.ends_with("."):
			return ""
	return rel


## A JSON number that is a whole number (JSON.parse_string gives floats): Sol r1, Game 2.5 / Type 0.5 / fractional sizes were truncated.
static func _whole(v) -> bool:
	return typeof(v) == TYPE_FLOAT and v == floor(v) and absf(v) < 9.0e15


## Checks one package's manifest (the service's JSON) against its pinned table: every file the install takes must be pinned (name, MD5,
## size; Sol r1: the files outside the archive tables trusted the manifest) and every pinned file must be listed. {ok, kind, error, files:
## [{rel, md5, size, url}] sorted by path, all: the manifest's file count}. Nothing here touches the network or the disk.
func check_manifest(pkg: Dictionary, body: PackedByteArray) -> Dictionary:
	var what := "The service's package %s" % pkg.guid
	var m = JSON.parse_string(body.get_string_from_utf8())
	if typeof(m) != TYPE_DICTIONARY:
		return _broken(REJECTED, "%s is not the file list OpenBFME knows (not a JSON object)." % what)
	if m.get("Guid") != pkg.guid:
		return _broken(REJECTED, "%s answered with the package '%s'." % [what, str(m.get("Guid")).left(80)])
	if not _whole(m.get("Game")) or int(m.Game) != int(pkg.game) or not _whole(m.get("Type")) or int(m.Type) != 0:
		return _broken(REJECTED, "%s is no longer the base game package (Game %s, Type %s)." % [what, JSON.stringify(m.get("Game")), JSON.stringify(m.get("Type"))])
	var owner = m.get("Owner")
	if typeof(owner) != TYPE_STRING or owner != pkg.owner:
		return _broken(REJECTED, "%s moved its files (owner '%s', pinned '%s')." % [what, str(owner).left(80), pkg.owner])
	if typeof(m.get("Files")) != TYPE_ARRAY:
		return _broken(REJECTED, "%s has no file list." % what)
	var hex := RegEx.create_from_string("^[0-9a-f]{32}$")
	var pinned := {}
	for a in pkg.files:
		pinned[str(a[0]).to_lower()] = a
	var chosen := {}
	for f in m.Files:
		if typeof(f) != TYPE_DICTIONARY or typeof(f.get("Name")) != TYPE_STRING or typeof(f.get("Md5")) != TYPE_STRING \
				or typeof(f.get("Url")) != TYPE_STRING or typeof(f.get("Language")) != TYPE_STRING:
			return _broken(REJECTED, "%s has a file entry OpenBFME does not recognise." % what)
		if not _whole(f.get("Size")) or f.Size < 0:
			return _broken(REJECTED, "%s lists %s with the size %s." % [what, f.Name.left(120).c_escape(), JSON.stringify(f.get("Size"))])
		var langs: PackedStringArray = f.Language.split(" ", false)
		if not (f.Language == "" or f.Language == "ALL" or pkg.language in langs):
			continue
		var rel := safe_relative(f.Name)
		if rel == "":
			return _broken(REJECTED, "%s lists a file name that is not a plain relative path: '%s'." % [what, f.Name.left(120).c_escape()])
		if hex.search(f.Md5) == null:
			return _broken(REJECTED, "%s lists %s with a malformed MD5." % [what, rel])
		if f.Url != "%s/%s/%s" % [files_origin, pkg.owner, f.Md5]:
			return _broken(REJECTED, "%s lists %s at '%s', not at the pinned %s/%s/<md5>." % [what, rel, f.Url.left(160), files_origin, pkg.owner])
		var key := rel.to_lower()
		if chosen.has(key):
			return _broken(REJECTED, "%s lists %s twice." % [what, rel])
		if not pinned.has(key):
			return _broken(REJECTED, "%s lists %s, which OpenBFME's list of %s does not have: the package changed. Nothing was downloaded." % [what, rel, pkg.label])
		var pin: Array = pinned[key]
		if f.Md5 != pin[1]:
			return _broken(REJECTED, "%s lists %s with MD5 %s; %s has %s. Nothing was downloaded." % [what, rel, f.Md5, pkg.label, pin[1]])
		if int(f.Size) != 0 and int(f.Size) != int(pin[2]):
			return _broken(REJECTED, "%s lists %s with %d bytes; %s has %d. Nothing was downloaded." % [what, rel, int(f.Size), pkg.label, int(pin[2])])
		# the pinned size always (the service lists some files with Size 0); the download takes no more and no less, then the MD5
		chosen[key] = {"rel": rel, "md5": pin[1], "size": int(pin[2]), "url": f.Url}
	for key in pinned:
		if not chosen.has(key):
			return _broken(REJECTED, "%s no longer lists %s, a file of %s. Nothing was downloaded." % [what, pinned[key][0], pkg.label])
	var files := chosen.values()
	files.sort_custom(func(a, b): return a.rel < b.rel)
	return {"ok": true, "kind": "", "error": "", "files": files, "all": m.Files.size()}


static func md5_of(path: String) -> String:
	var f := FileAccess.open(path, FileAccess.READ)
	if f == null:
		return ""
	var hc := HashingContext.new()
	hc.start(HashingContext.HASH_MD5)
	while f.get_position() < f.get_length():
		hc.update(f.get_buffer(1 << 20))
	return hc.finish().hex_encode()


## Downloads every package of the table into <target>/<its folder> (the AIO launcher's names: RotWK, BFME2). Blocking (the window runs
## it on its worker thread; pause / cancel through request_stop). {ok, kind, error, folders: {key: path}, downloaded, kept}
func install(target: String, consented: bool) -> Dictionary:
	if not enabled():
		return _fail(REFUSED, "the setting \"Offer to download the games\" (--aio) is off")
	if not consented:
		return _fail(REFUSED, "the player has not agreed to download the game files from %s" % PROJECT)
	if target == "" or not target.is_absolute_path():
		return _fail(REFUSED, "the target folder must be an absolute path (got '%s')" % target)
	var err := DirAccess.make_dir_recursive_absolute(target)
	if err != OK and not DirAccess.dir_exists_absolute(target):
		return _fail(REFUSED, "cannot create %s (%s)" % [target, error_string(err)])
	Log.line("LAUNCHER AIO consent given: " + consent_text().replace("\n", " "))
	stop_request = ""
	updater.http.cancelled = false
	updater.policy.extra_hosts = HOSTS.duplicate()
	var r := _install(target)
	updater.policy.extra_hosts = []
	updater.http.cancelled = false
	return r


## From the UI thread: "pause" (keep the partial file: the next install resumes it) or "cancel" (remove the partial file).
func request_stop(how: String) -> void:
	stop_request = how
	updater.http.cancelled = true


func _stopped(part: String) -> Dictionary:
	if stop_request == "cancel":
		if part != "":
			DirAccess.remove_absolute(part)
		return _fail(STOPPED, "cancelled; the files already checked are kept, the one in progress was removed")
	return _fail(STOPPED, "paused; it resumes where it stopped")


func _install(target: String) -> Dictionary:
	var plans := []
	for pkg in packages:
		var url := "%s/api/workshop/download?guid=%s" % [service, String(pkg.guid).uri_encode()]
		_report("Asking %s for the files of %s" % [service.trim_prefix("https://"), pkg.guid])
		var m: Dictionary = updater.http.get_small(url, MAX_MANIFEST, "application/json", "",
			PackedStringArray(["AuthAccountUuid: unauthenticated", "AuthAccountPassword: "]))
		if not m.ok and stop_request != "":
			return _stopped("")
		if not m.ok:
			return _broken(NETWORK, "The file list of %s could not be fetched: %s." % [pkg.guid, m.error])
		if m.code != 200:
			return _broken(REJECTED if m.code < 500 and m.code != 429 else NETWORK, "The service answered HTTP %d for the file list of %s." % [m.code, pkg.guid])
		var c := check_manifest(pkg, m.body)
		if not c.ok:
			return c
		plans.append({"pkg": pkg, "dir": target.path_join(pkg.folder), "files": c.files})
		Log.line("LAUNCHER AIO %s: %d of the package's %d files are installed (%s; every one is pinned and matches)" % [pkg.guid, c.files.size(), c.all, pkg.language])
	var total := 0
	var need := 0
	var count := 0
	for p in plans:
		for f in p.files:
			total += f.size
			count += 1
			if FileAccess.file_exists(p.dir.path_join(f.rel)):
				continue
			var part: String = p.dir.path_join(f.rel) + ".part"
			need += f.size - (FileAccess.open(part, FileAccess.READ).get_length() if FileAccess.file_exists(part) else 0)
	var space := DirAccess.open(target).get_space_left() if DirAccess.open(target) != null else 0
	if space <= 0:
		return _fail(REFUSED, "the free space of %s cannot be read: pick another folder" % target)
	if need > space:
		return _fail(REFUSED, "%s has %.1f GB free; the game files need %.1f GB more" % [target, space / 1e9, need / 1e9])
	Log.line("LAUNCHER AIO %d files, %.2f GB in all, %.2f GB to download, %.1f GB free" % [count, total / 1e9, need / 1e9, space / 1e9])
	var done := 0
	var downloaded := 0
	var kept := 0
	var index := 0
	for p in plans:
		for f in p.files:
			if stop_request != "":
				return _stopped("")
			index += 1
			var dest: String = p.dir.path_join(f.rel)
			var base := done
			var show := "File %d of %d, %s/%s" % [index, count, p.pkg.folder, f.rel]
			if FileAccess.file_exists(dest):
				_report("Checking " + show, done, total)
				var length := FileAccess.open(dest, FileAccess.READ).get_length() if FileAccess.open(dest, FileAccess.READ) != null else -1
				if length != f.size:
					return _fail(REJECTED, "%s already exists and is not %s's file (%d bytes, expected %d): move it away or pick another folder" % [dest, p.pkg.guid, length, f.size])
				var have := md5_of(dest)
				if have != f.md5:
					return _fail(REJECTED, "%s already exists and is not %s's file (MD5 %s, expected %s): move it away or pick another folder" % [dest, p.pkg.guid, have, f.md5])
				kept += 1
				done += f.size
				continue
			DirAccess.make_dir_recursive_absolute(dest.get_base_dir())
			var part := dest + ".part"
			var size: int = f.size
			var each := func(n: int, _s: int) -> void: _report("%s: %d%%" % [show, int(n * 100.0 / maxi(size, 1))], base + n, total)
			var d: Dictionary = updater.http.download(f.url, part, size, each)
			if d.resumed > 0:
				Log.line("LAUNCHER AIO resumed %s at %d bytes" % [f.rel, d.resumed])
			if not d.ok and stop_request != "":
				return _stopped(part)
			if not d.ok:
				if "HTTP 404" in d.error or "HTTP 410" in d.error:
					return _broken(REJECTED, "The service no longer has %s/%s (%s)." % [p.pkg.folder, f.rel, d.error])
				if "HTTP" in d.error or "more than" in d.error or "wrong place" in d.error:
					return _broken(REJECTED, "%s/%s: the service answered something OpenBFME does not recognise (%s)." % [p.pkg.folder, f.rel, d.error])
				return _broken(NETWORK, "%s/%s: %s." % [p.pkg.folder, f.rel, d.error])
			_report("Checking " + show, base + size, total)
			var got := md5_of(part)
			if got != f.md5:
				DirAccess.remove_absolute(part)
				return _broken(REJECTED, "%s/%s from the service has MD5 %s, expected %s: it was deleted." % [p.pkg.folder, f.rel, got, f.md5])
			if DirAccess.rename_absolute(part, dest) != OK:
				return _fail(REFUSED, "cannot rename %s to %s" % [part, dest])
			downloaded += 1
			done += size
			if test_stop_after != "" and test_stop_after.get_slice(":", 0) == "%s/%s" % [p.pkg.folder, f.rel]:
				request_stop(test_stop_after.get_slice(":", 1))
	# a pause or cancel that came during the last check: nothing is handed to the game (Sol r1)
	if stop_request != "":
		return _stopped("")
	var folders := {}
	var record := {"service": service, "target": target, "date": Time.get_datetime_string_from_system(true), "packages": []}
	for p in plans:
		folders[p.pkg.key] = p.dir
		record.packages.append({"guid": p.pkg.guid, "name": p.pkg.name, "folder": p.dir, "files": p.files.size(), "policySha256": p.pkg.policySha256})
	record["folders"] = folders
	var f := FileAccess.open(updater.data_dir.path_join(RECORD), FileAccess.WRITE)
	if f != null:
		f.store_string(JSON.stringify(record, "  ") + "\n")
		f.close()
	var why := write_marker(folders)
	if why != "":
		return _fail(REFUSED, "the files are installed and checked, but the game could not be told where: %s. Pick %s when OpenBFME asks." % [why, ", ".join(folders.values())])
	for p in plans:
		Log.line("LAUNCHER AIO installed %s (%s) in %s" % [p.pkg.label, p.pkg.guid, p.dir])
	return {"ok": true, "kind": "", "error": "", "folders": folders, "downloaded": downloaded, "kept": kept}


## The first-run handoff: <game user dir>/downloaded-installs.cfg (InstallLocator::readDownloaded: SOURCE, <KEY>_INSTALL lines), written
## atomically. "" or why not.
func write_marker(folders: Dictionary) -> String:
	var dir := GameOptions.game_user_dir()
	var err := DirAccess.make_dir_recursive_absolute(dir)
	if err != OK and not DirAccess.dir_exists_absolute(dir):
		return "cannot create %s (%s)" % [dir, error_string(err)]
	var guids := PackedStringArray()
	for p in packages:
		guids.append(p.guid)
	var lines := PackedStringArray(["# Written by the OpenBFME launcher after it downloaded and checked these folders. The game offers them on its first start.",
		"SOURCE=All In One BFME Launcher service: " + ", ".join(guids)])
	for key in folders:
		lines.append("%s_INSTALL=%s" % [String(key).to_upper(), folders[key]])
	var path := dir.path_join(MARKER)
	var f := FileAccess.open(path + ".tmp", FileAccess.WRITE)
	if f == null:
		return "cannot write %s (%s)" % [path, error_string(FileAccess.get_open_error())]
	f.store_string("\n".join(lines) + "\n")
	f.close()
	if DirAccess.rename_absolute(path + ".tmp", path) != OK:
		return "cannot replace %s" % path
	Log.line("LAUNCHER AIO the game will offer these folders on its first start (%s)" % path)
	return ""


## After a cancel: remove the partial files of this download, <target>/<folder>/<pinned file>.part, and nothing else (Sol r1: every
## *.part below the folders went, also files this launcher did not write). Completed, checked files stay.
func remove_partials(target: String) -> int:
	var n := 0
	for p in packages:
		for f in p.files:
			var part := target.path_join(p.folder).path_join(str(f[0])) + ".part"
			if FileAccess.file_exists(part) and DirAccess.remove_absolute(part) == OK:
				n += 1
	return n
