// OpenBFME. GPL-3.0.
//
// GENERATED by tools/weapon/gen_names.py from the golden lists in engine/tests/data/weapon1; do not edit.
// The binary's own name enumerations (full registries, PLAN rule 6). See GameLogic/Damage.h and GameLogic/Weapon.h.

#include "GameLogic/Damage.h"
#include "GameLogic/Weapon.h"
#include "GameLogic/Armor.h"
#include "GameLogic/ArmorSet.h"
#include "GameLogic/DamageFX.h"
#include "GameLogic/WeaponNugget.h"
#include "GameLogic/WeaponSet.h"

// RW 0xDA15A8, 28 names
const char *const TheDamageNames[] = {
	"FORCE", "CRUSH", "SLASH", "PIERCE",
	"SIEGE", "STRUCTURAL", "FLAME", "HEALING",
	"UNRESISTABLE", "WATER", "PENALTY", "FALLING",
	"TOPPLING", "REFLECTED", "PASSENGER", "MAGIC",
	"CHOP", "HERO", "SPECIALIST", "URUK",
	"HERO_RANGED", "FLY_INTO", "UNDEFINED", "LOGICAL_FIRE",
	"CAVALRY", "CAVALRY_RANGED", "POISON", "FROST",
	nullptr };

// RW 0xDA1630, 24 names
const char *const TheWeaponDeathNames[] = {
	"NORMAL", "NONE", "CRUSHED", "BURNED",
	"EXPLODED", "POISONED", "TOPPLED", "FLOODED",
	"SUICIDED", "LASERED", "DETONATED", "SPLATTED",
	"POISONED_BETA", "EXTRA_2", "EXTRA_3", "EXTRA_4",
	"EXTRA_5", "EXTRA_6", "EXTRA_7", "EXTRA_8",
	"KNOCKBACK", "SUPERNATURAL", "FADED", "SLAUGHTERED",
	nullptr };

// RW 0xDA1510, 36 names
const char *const TheDamageFXTypeNames[] = {
	"SWORD_SLASH", "WITCH_KING_MORGUL_BLADE", "REFLECTED", "GOOD_ARROW_PIERCE",
	"EVIL_ARROW_PIERCE", "SMALL_ROCK", "BIG_ROCK", "CLUBBING",
	"FLAME", "MAGIC", "BALROG_SWORD", "BALROG_WHIP",
	"ELECTRIC", "GIMLI_LEAP", "STRUCTURAL", "FLOOD_HORSE",
	"BOLT", "BOLT2", "MAGIC2", "MAGIC3",
	"FIRE1", "FIRE2", "FIRE3", "SPARKS1",
	"SPARKS2", "EARTH1", "EARTH2", "POISON",
	"TORNADO", "UNDEFINED", "NECRO1", "NECRO2",
	"NECRO3", "NECRO4", "NECRO5", "NECRO6",
	nullptr };

// RW 0xDA14FC, 3 names
const char *const TheFXTriggerNames[] = {
	"NONE", "CATAPULT_ROCK", "TREBUCHET_ROCK",
	nullptr };

// RW 0xDA16BC, 3 names
const char *const TheWeaponReloadNames[] = {
	"YES", "NO", "RETURN_TO_BASE",
	nullptr };

// RW 0xDA16CC, 4 names
const char *const TheWeaponPrefireNames[] = {
	"PER_SHOT", "PER_ATTACK", "PER_CLIP", "PER_POSITION",
	nullptr };

// RW 0xDA16E0, 10 names
const char *const TheWeaponAffectsMaskNames[] = {
	"SELF", "ALLIES", "ENEMIES", "NEUTRALS",
	"SUICIDE", "NOT_SIMILAR", "NOT_AIRBORNE", "PROJECTILES",
	"SAME_HEIGHT_ONLY", "MINES",
	nullptr };

// RW 0xDA170C, 11 names
const char *const TheWeaponCollideMaskNames[] = {
	"ALLIES", "ENEMIES", "NEUTRAL", "STRUCTURES",
	"SHRUBBERY", "PROJECTILES", "WALLS", "SMALL_MISSILES",
	"BALLISTIC_MISSILES", "CONTROLLED_STRUCTURES", "MONSTERS",
	nullptr };

// RW 0xDA12E4, 5 names
const char *const TheWeaponSlotTypeNames[] = {
	"PRIMARY", "SECONDARY", "TERTIARY", "QUATERNARY",
	"QUINARY",
	nullptr };

// RW 0xDA12FC, 9 names
const char *const TheWeaponChoiceCriteriaNames[] = {
	"PREFER_MOST_DAMAGE", "PREFER_LONGEST_RANGE", "PREFER_GRAB_OVER_DAMAGE", "PREFER_LEAST_MOVEMENT",
	"SELECT_AT_RANDOM", "USE_WEAPONSET_DEFAULT_CRITERIA", "FROM_PLAYER", "FROM_SCRIPT",
	"FROM_AI",
	nullptr };

// RW 0xDA1314, 3 names
const char *const TheCommandSourceMaskNames[] = {
	"FROM_PLAYER", "FROM_SCRIPT", "FROM_AI",
	nullptr };

// RW 0xDA1740, 22 names
const char *const TheWeaponBonusConditionNames[] = {
	"GARRISONED", "HORDE", "CONTINUOUS_FIRE_MEAN", "CONTINUOUS_FIRE_FAST",
	"NATIONALISM", "PLAYER_UPGRADE", "DRONE_SPOTTING", "DEMORALIZED_OBSOLETE",
	"ENTHUSIASTIC", "VETERAN", "ELITE", "HERO",
	"BATTLEPLAN_BOMBARDMENT", "BATTLEPLAN_HOLDTHELINE", "BATTLEPLAN_SEARCHANDDESTROY", "SUBLIMINAL",
	"SOLO_HUMAN_EASY", "SOLO_HUMAN_NORMAL", "SOLO_HUMAN_HARD", "SOLO_AI_EASY",
	"SOLO_AI_NORMAL", "SOLO_AI_HARD",
	nullptr };

// RW 0xDA179C, 6 names
const char *const TheWeaponBonusFieldNames[] = {
	"DAMAGE", "RADIUS", "RANGE", "RATE_OF_FIRE",
	"PRE_ATTACK", "FIRING",
	nullptr };

// RW 0xD9F5E4, 4 names
const char *const TheVeterancyNames[] = {
	"REGULAR", "VETERAN", "ELITE", "HEROIC",
	nullptr };

// RW 0xDB5D9C, 4 names
const char *const TheDamageSubTypeNames[] = {
	"NORMAL", "BECOME_UNDEAD", "SELF", "BECOME_UNDEAD_ONCE",
	nullptr };

// RW 0xD9FA08, 12 names
const char *const TheEmotionTypeNames[] = {
	"TAUNT", "CHEER", "HERO_CHEER", "POINT",
	"FEAR", "UNCONTROLLABLE_FEAR", "TERROR", "DOOM",
	"QUARRELSOME", "ALERT", "BRACE_FOR_BEING_CRUSHED", "CHEER_FOR_ABOUT_TO_CRUSH",
	nullptr };

// RW 0xD9FA40, 15 names
const char *const TheAntiCategoryNames[] = {
	"NONE", "LEADERSHIP", "FORMATION", "SPELL",
	"WEAPON", "STRUCTURE", "LEVEL", "BUFF",
	"DEBUFF", "STUN", "INNATE_ARMOR", "INNATE_DAMAGEMULT",
	"INNATE_VISION", "INNATE_AUTOHEAL", "INNATE_HEALTH",
	nullptr };

// RW 0xDB6694, 5 names
const char *const TheFireLogicTypeNames[] = {
	"INCREASE_BURN_RATE", "DECREASE_BURN_RATE", "INCREASE_FUEL", "INCREASE_BURN_RATE_ON_EXISTING_FIRE",
	"INCREASE_FUEL_ON_EXISTING_FIRE",
	nullptr };

// RW 0xD9FA80, 21 names
const char *const TheArmorSetNames[] = {
	"VETERAN", "ELITE", "HERO", "PLAYER_UPGRADE",
	"WEAK_VERSUS_BASEDEFENSES", "ALTERNATE_FORMATION", "MOUNTED", "PLAYER_UPGRADE_2",
	"PLAYER_UPGRADE_3", "UNBESIEGEABLE", "AS_TOWER", "CREATE_A_HERO_01",
	"CREATE_A_HERO_02", "CREATE_A_HERO_03", "CREATE_A_HERO_04", "CREATE_A_HERO_05",
	"CREATE_A_HERO_06", "CREATE_A_HERO_07", "CREATE_A_HERO_08", "CREATE_A_HERO_09",
	"CREATE_A_HERO_10",
	nullptr };

// RW 0xDA5110, 36 names
const char *const TheDamageFXBlockTypeNames[] = {
	"SWORD_SLASH", "WITCH_KING_MORGUL_BLADE", "REFLECTED", "GOOD_ARROW_PIERCE",
	"EVIL_ARROW_PIERCE", "SMALL_ROCK", "BIG_ROCK", "CLUBBING",
	"FLAME", "MAGIC", "BALROG_SWORD", "BALROG_WHIP",
	"ELECTRIC", "GIMLI_LEAP", "STRUCTURAL", "FLOOD_HORSE",
	"BOLT", "BOLT2", "MAGIC2", "MAGIC3",
	"FIRE1", "FIRE2", "FIRE3", "SPARKS1",
	"SPARKS2", "EARTH1", "EARTH2", "POISON",
	"TORNADO", "UNDEFINED", "NECRO1", "NECRO2",
	"NECRO3", "NECRO4", "NECRO5", "NECRO6",
	nullptr };

// RW 0xC16928, 5 pairs
const LookupListRec TheWeaponSlotLookup[] = {
	{ "PRIMARY", 0 },
	{ "SECONDARY", 1 },
	{ "TERTIARY", 2 },
	{ "QUATERNARY", 3 },
	{ "QUINARY", 4 },
	{ nullptr, 0 } };
