#!/usr/bin/env python3
"""Generates engine/src/GameLogic/BitFlagNames.cpp from the golden name lists (lane HORDE-1).

The lists are the binary's own enumerations (KindOf, ModelCondition, ObjectStatus, weapon condition and
death type names), dumped by dump_tables.py into engine/tests/data/horde1/list_*.tsv. Engine code holds the
full registry, never a subset (PLAN rule 6).

    python tools/horde_oracle/gen_names.py            # rewrite the file
    python tools/horde_oracle/gen_names.py --check    # exit 1 when it is out of date
"""
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
DATA = ROOT / "engine" / "tests" / "data" / "horde1"
OUT = ROOT / "engine" / "src" / "GameLogic" / "BitFlagNames.cpp"

LISTS = [
    ("TheKindOfNames", "list_kindof_names.tsv", "RW 0xDA0E68"),
    ("TheModelConditionNames", "list_model_condition_names.tsv", "RW 0xD9FAD8"),
    ("TheObjectStatusNames", "list_object_status_names.tsv", "RW 0xD8AFF0"),
    ("TheWeaponConditionNames", "list_weapon_condition_names.tsv", "RW 0xDA1328"),
    ("TheDeathTypeNames", "list_death_type_names.tsv", "RW 0xDA39E8"),
    ("TheMeleeBehaviorNames", "list_melee_behavior_names.tsv", "RW 0xDAEB2C"),
]


def render() -> str:
    out = [
        "// OpenBFME. GPL-3.0.",
        "//",
        "// GENERATED by tools/horde_oracle/gen_names.py from the golden lists in engine/tests/data/horde1; do not edit.",
        "// The binary's own name enumerations (full registries, PLAN rule 6). See GameLogic/BitFlags.h.",
        "",
        '#include "GameLogic/BitFlags.h"',
        "",
    ]
    for sym, fname, where in LISTS:
        names = [line.split("\t", 1)[1] for line in (DATA / fname).read_text().splitlines()]
        out.append(f"// {where}, {len(names)} names")
        out.append(f"const char *const {sym}[] = {{")
        for i in range(0, len(names), 6):
            out.append("\t" + ", ".join(f'"{n}"' for n in names[i:i + 6]) + ",")
        out.append("\tnullptr };")
        out.append("")
    return "\n".join(out)


if __name__ == "__main__":
    text = render()
    if "--check" in sys.argv:
        sys.exit(0 if OUT.exists() and OUT.read_text() == text else 1)
    OUT.write_text(text, newline="\n")
    print("wrote", OUT)
