#!/usr/bin/env python3
"""Independent reference for the game-logic RNG (lane HORDE-1, stop S-080).

Two generators, written from the disassembly / ZH source, not from the C++ port:

  RotWK_GameDat_LCG   RotWK game.dat 0x6D315D randomValue, 0x6D31D4 seedRandom
  ZH_CarryChain       ZH RandomValue.cpp, identical to BFME2 1.06 game.dat 0x633EC3

and the integer / real wrappers (RW 0x6D328E / 0x6D332C) with the x87 PC24 chain computed in exact
rational arithmetic (round-to-nearest-even to a 24-bit significand after every step).

    python tools/horde_oracle/rng_reference.py > engine/tests/data/horde1/rng_golden.json
"""
from __future__ import annotations

import json
import struct
import sys
from fractions import Fraction as F

M = (1 << 32) - 1
INIT = [0xF22D0E56, 0x883126E9, 0xC624DD2F, 0x0702C49C, 0x9E353F7D, 0x6FDF3B64]


class Lcg:
    name = "RotWK_GameDat_LCG"

    @staticmethod
    def seed(s):
        # RW 0x6D31D4: edx:eax = SEED * 0x7FFFFFED; all six words = eax
        return [(s * 0x7FFFFFED) & M] * 6

    @staticmethod
    def draw(seed):
        # RW 0x6D315D: edx:eax = seed[0] * 0x08088405; eax += 1; seed[0] = eax; return eax ^ edx
        p = seed[0] * 0x08088405
        low, high = (p + 1) & M, (p >> 32) & M
        seed[0] = low
        return low ^ high


class Zh:
    name = "ZH_CarryChain"

    @staticmethod
    def seed(s):
        return [(s + x) & M for x in INIT]

    @staticmethod
    def draw(seed):
        carry = 0

        def adc(a, b):
            nonlocal carry
            total = (a + b + carry) & M
            carry = 1 if (total < a or total < b) else 0
            return total

        ax = adc(seed[5], seed[4]); seed[4] = ax
        ax = adc(ax, seed[3]); seed[3] = ax
        ax = adc(ax, seed[2]); seed[2] = ax
        ax = adc(ax, seed[1]); seed[1] = ax
        ax = adc(ax, seed[0]); seed[0] = ax
        for i in (5, 4, 3, 2, 1):
            seed[i] = (seed[i] + 1) & M
            if seed[i] != 0:
                return ax
        seed[0] = (seed[0] + 1) & M
        return (ax + 1) & M


def round24(x):
    x = F(x)
    if x == 0:
        return x
    sign = 1 if x > 0 else -1
    x = abs(x)
    e = x.numerator.bit_length() - x.denominator.bit_length() - 24
    while x / F(2) ** e >= 1 << 24:
        e += 1
    while x / F(2) ** e < 1 << 23:
        e -= 1
    q = x / F(2) ** e
    fl = q.numerator // q.denominator
    rem = q - fl
    if rem > F(1, 2) or (rem == F(1, 2) and fl % 2 == 1):
        fl += 1
    return sign * F(fl) * F(2) ** e


def f32_bits(v):
    return struct.unpack("<I", struct.pack("<f", float(v)))[0]


def get_value(gen, seed, lo, hi):
    delta = (hi - lo + 1) & M
    if delta == 0:
        return hi, False
    r = gen.draw(seed)
    v = (r % delta) + lo
    return v, True


def get_value_real(gen, seed, lo, hi):
    lo_f, hi_f = F(lo), F(hi)
    delta = round24(hi_f - lo_f)          # subss: float32 subtraction
    if delta <= 0:
        return hi, False
    r = gen.draw(seed)
    signed = r - (1 << 32) if r & 0x80000000 else r
    t = F(signed)                          # fild dword
    if signed < 0:
        t = round24(t + (1 << 32))         # fadd 2^32
    t = round24(t * F(1, 1 << 32))         # fmul theMultFactor (= 2^-32)
    t = round24(t * delta)                 # fmul delta
    t = round24(t + lo_f)                  # fadd lo
    return float(t), True


INT_OPS = [(0, 99), (-5, 5), (5, 5), (0, -1), (1, 3), (0, 2**31 - 1), (-100, 100), (7, 6), (0, 4), (10, 20)]
REAL_OPS = [(-1.0, 1.0), (0.0, 1.0), (3.0, 3.0), (2.5, 2.0), (0.0, 360.0), (-20.0, 20.0), (0.0, 0.5), (1.0, 1.0000001)]


def sequence(gen, seedval):
    seed = gen.seed(seedval)
    ops = []
    for i in range(24):
        if i % 3 == 2:
            lo, hi = REAL_OPS[(i // 3) % len(REAL_OPS)]
            v, drew = get_value_real(gen, seed, lo, hi)
            ops.append({"op": "r", "lo_bits": f32_bits(lo), "hi_bits": f32_bits(hi), "result_bits": f32_bits(v), "drew": drew})
        else:
            lo, hi = INT_OPS[(i - i // 3) % len(INT_OPS)]
            v, drew = get_value(gen, seed, lo, hi)
            ops.append({"op": "i", "lo": lo, "hi": hi, "result": v, "drew": drew})
    return ops


def build():
    out = {"comment": "generated by tools/horde_oracle/rng_reference.py; do not edit", "algorithms": {}}
    for gen in (Lcg, Zh):
        cases = []
        for seedval in (0, 12345, 0xF22D0E56, 0xDEADBEEF):
            seed = gen.seed(seedval)
            seed_after = list(seed)
            raw = [gen.draw(seed) for _ in range(8)]
            cases.append({
                "seed": seedval,
                "seed_array": seed_after,
                "raw": raw,
                "sequence": sequence(gen, seedval),
            })
        out["algorithms"][gen.name] = cases
    return out


if __name__ == "__main__":
    json.dump(build(), sys.stdout, indent=1, sort_keys=True)
    sys.stdout.write("\n")
