// OpenBFME unit tests. GPL-3.0.
// HORDE-2 synthetic data shared by the horde2 tests: a trampling rider, footmen and a pikeman with a revenge weapon, their crush weapons, and a horde with a banner carrier.
#pragma once

#include "GameLogic/Object/ExperienceTracker.h"

// lane INTEG-1: the banner carrier reads the horde's ExperienceTracker rank (RW 0x871A1B); these fixtures load no ExperienceLevel data, so the tests set the rank
// through RW 0x79D72A (ExperienceTracker::setRank) instead of earning it (the retail test earns it: test_xp_retail.cpp)
struct ExperienceTrackerTestAccess
{
	static void setRank(ExperienceTracker &t, int rank) { t.setRank(rank); }
};

namespace horde2test
{
const char kCrushObjects[] =
	"Object Rider\n"
	"  KindOf = CAVALRY SELECTABLE CAN_ATTACK SCORE\n"
	"  VisionRange = 150\n"
	"  CrusherLevel = 1\n"
	"  CrushableLevel = 3\n"
	"  CrushWeapon = TrampleWeapon\n"
	"  MinCrushVelocityPercent = 40%\n"
	"  CrushDecelerationPercent = 20%\n"
	"  Geometry = CYLINDER\n"
	"  GeometryMajorRadius = 8\n"
	"  GeometryMinorRadius = 8\n"
	"  GeometryHeight = 20\n"
	"  ArmorSet\n"
	"    Conditions = None\n"
	"    Armor = PlainArmor\n"
	"  End\n"
	"  WeaponSet\n"
	"    Conditions = None\n"
	"    Weapon = PRIMARY SwordWeapon\n"
	"  End\n"
	"  Body = ActiveBody ModuleTag_Body\n"
	"    MaxHealth = 300\n"
	"  End\n"
	"  Behavior = AIUpdateInterface ModuleTag_AI\n"
	"  End\n"
	"  Behavior = SquishCollide ModuleTag_Squish\n"
	"  End\n"
	"  Behavior = DestroyDie ModuleTag_Destroy\n"
	"  End\n"
	"  LocomotorSet\n"
	"    Locomotor = WalkerLoco\n"
	"    Condition = SET_NORMAL\n"
	"    Speed = 80\n"
	"  End\n"
	"End\n"
	"Object Footman\n"
	"  KindOf = INFANTRY SELECTABLE SCORE\n"
	"  CrushableLevel = 0\n"
	"  Geometry = CYLINDER\n"
	"  GeometryMajorRadius = 8\n"
	"  GeometryMinorRadius = 8\n"
	"  GeometryHeight = 20\n"
	"  ArmorSet\n"
	"    Conditions = None\n"
	"    Armor = NoArmor\n"
	"  End\n"
	"  Body = ActiveBody ModuleTag_Body\n"
	"    MaxHealth = 100\n"
	"  End\n"
	"  Behavior = AIUpdateInterface ModuleTag_AI\n"
	"  End\n"
	"  Behavior = SquishCollide ModuleTag_Squish\n"
	"  End\n"
	"  Behavior = DestroyDie ModuleTag_Destroy\n"
	"  End\n"
	"  LocomotorSet\n"
	"    Locomotor = WalkerLoco\n"
	"    Condition = SET_NORMAL\n"
	"    Speed = 55\n"
	"  End\n"
	"End\n"
	"Object Pikeman\n"
	"  KindOf = INFANTRY SELECTABLE CAN_ATTACK SCORE\n"
	"  CrushableLevel = 1\n"
	"  CrushRevengeWeapon = PikeRevenge\n"
	"  Geometry = CYLINDER\n"
	"  GeometryMajorRadius = 8\n"
	"  GeometryMinorRadius = 8\n"
	"  GeometryHeight = 20\n"
	"  ArmorSet\n"
	"    Conditions = None\n"
	"    Armor = NoArmor\n"
	"  End\n"
	"  WeaponSet\n"
	"    Conditions = None\n"
	"    Weapon = PRIMARY SwordWeapon\n"
	"  End\n"
	"  Body = ActiveBody ModuleTag_Body\n"
	"    MaxHealth = 100\n"
	"  End\n"
	"  Behavior = AIUpdateInterface ModuleTag_AI\n"
	"  End\n"
	"  Behavior = SquishCollide ModuleTag_Squish\n"
	"  End\n"
	"  Behavior = DestroyDie ModuleTag_Destroy\n"
	"  End\n"
	"  LocomotorSet\n"
	"    Locomotor = WalkerLoco\n"
	"    Condition = SET_NORMAL\n"
	"    Speed = 55\n"
	"  End\n"
	"End\n";

const char kCrushWeapons[] =
	"Weapon TrampleWeapon\n"
	"  AttackRange = 20\n"
	"  DamageNugget\n"
	"    Damage = 60\n"
	"    Radius = 0.0\n"
	"    DelayTime = 0\n"
	"    DamageType = CRUSH\n"
	"    DeathType = CRUSHED\n"
	"  End\n"
	"End\n"
	"Weapon PikeRevenge\n"
	"  AttackRange = 20\n"
	"  DamageNugget\n"
	"    Damage = 25\n"
	"    Radius = 0.0\n"
	"    DelayTime = 0\n"
	"    DamageType = PIERCE\n"
	"    DeathType = NORMAL\n"
	"  End\n"
	"End\n";

const char kBannerObjects[] =
	"Object Bannerman\n"
	"  KindOf = INFANTRY SELECTABLE HORDE_BANNER_CARRIER\n"
	"  Geometry = CYLINDER\n"
	"  GeometryMajorRadius = 8\n"
	"  GeometryMinorRadius = 8\n"
	"  GeometryHeight = 20\n"
	"  ArmorSet\n"
	"    Conditions = None\n"
	"    Armor = PlainArmor\n"
	"  End\n"
	"  Body = ActiveBody ModuleTag_Body\n"
	"    MaxHealth = 100\n"
	"  End\n"
	"  Behavior = AIUpdateInterface ModuleTag_AI\n"
	"  End\n"
	"  Behavior = BannerCarrierUpdate ModuleTag_Banner\n"
	"    IdleSpawnRate = 2000\n"
	"    MeleeFreeUnitSpawnTime = 4000\n"
	"    DiedRespawnTime = 2000\n"
	"    MeleeFreeBannerReSpawnTime = 4000\n"
	"    MorphCondition = UnitType:Swordsman ModelState:\"USER_2\"\n"
	"  End\n"
	"  Behavior = DestroyDie ModuleTag_Destroy\n"
	"  End\n"
	"  LocomotorSet\n"
	"    Locomotor = WalkerLoco\n"
	"    Condition = SET_NORMAL\n"
	"    Speed = 55\n"
	"  End\n"
	"End\n"
	"Object BannerHorde\n"
	"  KindOf = HORDE MELEE_HORDE LARGE_RECTANGLE_PATHFIND SELECTABLE CAN_ATTACK\n"
	"  VisionRange = 200\n"
	"  WeaponSet\n"
	"    Conditions = None\n"
	"    Weapon = PRIMARY SwordWeapon\n"
	"  End\n"
	"  Geometry = BOX\n"
	"  GeometryMajorRadius = 30\n"
	"  GeometryMinorRadius = 45\n"
	"  GeometryHeight = 20\n"
	"  Body = ImmortalBody ModuleTag_Body\n"
	"    MaxHealth = 1\n"
	"  End\n"
	"  Behavior = HordeAIUpdate ModuleTag_AI\n"
	"  End\n"
	"  Behavior = HordeContain ModuleTag_Contain\n"
	"    RankInfo = RankNumber:1 UnitType:Swordsman Position:X:50 Y:0 Position:X:50 Y:20 Position:X:50 Y:-20\n"
	"    Slots = 3\n" // lane INTEG-1: the refill limit (RW 0x89A3E1 compares the members with Slots, module data + 0x98)
	"    InitialPayload = Swordsman 3\n"
	"    BannerCarriersAllowed = Bannerman\n"
	"    BannerCarrierPosition = UnitType:Swordsman Pos:X:10.0 Y:0.0\n"
	"    BannerCarrierMinLevel = 0\n"
	"  End\n"
	"  LocomotorSet\n"
	"    Locomotor = HordeLoco\n"
	"    Condition = SET_NORMAL\n"
	"    Speed = 50\n"
	"  End\n"
	"End\n";
} // namespace horde2test
