// OpenBFME unit tests: the whole retail map corpus of the pure RotWK 2.01 + BFME2 1.06 mount. GPL-3.0.
//
// Runs only when ROTWK_INSTALL and BFME2_INSTALL are set (prints SKIP otherwise). Expected values are
// NEVER this engine's own output:
//  * tests/data/map-survey.json, generated by tools/maps/map_survey.py from the spec author's
//    independent reference parser (census.py / fullparse.py / btdstats.py), and
//  * the retail maps/mapcache.ini inside the mounted archives (fileSize, extentMax, Player_N_Start
//    positions), and
//  * the per-chunk version table of spec maps-and-terrain.md 1.6.
//
// It uses the process-wide mount from RetailTestMount (never a second mount: 213 archives open at
// once already sit close to the CRT's 512 FILE* limit).

#include "doctest.h"
#include "MapCorpusUtil.h"
#include "RetailTestMount.h"

#include "Common/Crc32.h"
#include "Common/DataChunk.h"
#include "Common/LooseFileScan.h"
#include "Common/MiniJson.h"
#include "GameClient/MapCache.h"
#include "GameClient/MapUtil.h"
#include "GameEngineDevice/W3DDevice/GameClient/HeightMapMesh.h"
#include "GameEngineDevice/Win32Device/Common/Win32BIGFileSystem.h"
#include "GameClient/TGAFile.h"
#include "GameClient/TerrainAtlas.h"
#include "GameClient/TerrainRoads.h"
#include "GameClient/TerrainTypes.h"
#include "GameLogic/Map/TerrainLogic.h"
#include "GameLogic/Object/ObjectNameIndex.h"

#include <algorithm>
#include <chrono>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <functional>
#include <map>
#include <set>
#include <sstream>

using namespace mapcorpus;

namespace
{

std::string tupleStr(int a, int b, int c, int d)
{
	return "(" + std::to_string(a) + ", " + std::to_string(b) + ", " + std::to_string(c) + ", " + std::to_string(d) + ")";
}

std::string orderKey(const std::vector<std::string> &v)
{
	std::string s;
	for (const std::string &x : v)
	{
		s += x + ",";
	}
	return s;
}

size_t popcount(const std::vector<std::uint8_t> &v)
{
	size_t n = 0;
	for (std::uint8_t b : v)
	{
		for (int i = 0; i < 8; ++i)
		{
			n += (b >> i) & 1;
		}
	}
	return n;
}

// Spec maps-and-terrain.md 1.6: chunk -> version -> number of files (181 pure retail files).
const std::map<std::string, std::map<int, int>> kSpecVersionTable = {
	{ "/HeightMapData", { { 5, 181 } } },
	{ "/BlendTileData", { { 8, 3 }, { 11, 1 }, { 14, 2 }, { 15, 33 }, { 16, 10 }, { 18, 132 } } },
	{ "/WorldInfo", { { 1, 181 } } },
	{ "/MPPositionList", { { 0, 178 } } },
	{ "MPPositionList/MPPositionInfo", { { 1, 178 } } },
	{ "/SidesList", { { 5, 3 }, { 6, 178 } } },
	{ "/LibraryMapLists", { { 1, 181 } } },
	{ "LibraryMapLists/LibraryMaps", { { 1, 181 } } },
	{ "/Teams", { { 1, 181 } } },
	{ "/PlayerScriptsList", { { 1, 131 }, { 5, 35 }, { 6, 15 } } },
	{ "/BuildLists", { { 1, 181 } } },
	{ "/ObjectsList", { { 3, 181 } } },
	{ "ObjectsList/Object", { { 3, 151 } } }, // 30 files have an empty list
	{ "/PolygonTriggers", { { 4, 3 }, { 5, 36 } } },
	{ "/TriggerAreas", { { 1, 142 } } },
	{ "/StandingWaterAreas", { { 2, 142 } } },
	{ "/RiverAreas", { { 1, 12 }, { 2, 130 } } },
	{ "/StandingWaveAreas", { { 1, 10 }, { 2, 132 } } },
	{ "/GlobalLighting", { { 7, 51 }, { 8, 130 } } },
	{ "/PostEffectsChunk", { { 1, 142 } } },
	{ "/EnvironmentData", { { 2, 3 }, { 3, 178 } } },
	{ "/NamedCameras", { { 2, 181 } } },
	{ "/CameraAnimationList", { { 1, 7 }, { 3, 135 } } },
	{ "/WaypointsList", { { 1, 181 } } },
	{ "/SkyboxSettings", { { 1, 49 } } },
};

struct Counters
{
	int maps = 0;
	size_t objects = 0;
	size_t cliffPatched = 0, blendPatched = 0, extraPatched = 0;
	size_t formalCliff = 0, formalCliffCells = 0;
	int formalCliffNumCliffInfo = -1;
	std::vector<std::string> mapsWithPatches;
	size_t objectsOutsideZhZ = 0;
	size_t emptyNameObjects = 0;
	std::map<std::string, std::map<int, int>> versionFiles; // "parent/label" -> version -> files
	std::map<std::string, int> orders;
	std::map<std::string, size_t> objectNameCounts;
	std::map<std::string, std::vector<std::string>> unresolvedBy; // name -> maps
	std::set<std::string> condNames, actionNames;
	std::vector<std::string> waypointProblems;
	std::set<std::string> surveyStarNames; // "*" template names named by the oracle survey
	int maxChunkDepth = 0;                 // deepest chunk nesting in the corpus (levels)
	std::map<std::string, int> classTiles; // distinct terrain class name -> largest numTiles any map asks of it
	size_t waypoints = 0;
	size_t roadPairs = 0, roadSameName = 0, roadOrphans = 0, roadUnknown = 0, roadDuplicates = 0;
	size_t waypointLinks = 0;
	std::set<std::string> roadNames, roadUnknownNames;
	size_t decodedBytes = 0;
	std::vector<std::string> zeroLeftoverFailures;
	std::set<std::string> lightingSizes;
};

} // namespace

TEST_CASE("map corpus: every pure 2.01 + BFME2 1.06 .map parses with zero leftover bytes and matches the independent oracle")
{
	retailtest::Mount *mount = retailtest::pureMount();
	if (!mount)
	{
		retailtest::printSkip("map corpus");
		return;
	}
	REQUIRE_MESSAGE(mount->fs != nullptr, mount->error);

	std::vector<unsigned char> surveyBytes;
	std::string err;
	REQUIRE_MESSAGE(retailtest::readLocalFile(retailtest::dataDir() + "/map-survey.json", surveyBytes, &err), err);
	JsonValue survey;
	REQUIRE_MESSAGE(JsonValue::parse(std::string(surveyBytes.begin(), surveyBytes.end()), survey, &err), err);
	const JsonValue &surveyMaps = J(survey, "maps");

	// 1. the mounted file list is exactly the oracle's 181 maps
	FilenameList list;
	mount->fs->getFileListInDirectory("", "", "*.map", list, true);
	std::set<std::string> mounted;
	for (const std::string &p : list)
	{
		mounted.insert(slashes(lowerStr(p), '/'));
	}
	std::set<std::string> oracle;
	for (const auto &kv : surveyMaps.object)
	{
		oracle.insert(kv.first);
	}
	CHECK(mounted.size() == 181);
	CHECK(mounted == oracle);

	// 2. the name index (template resolution), built once from the winning INI files
	ObjectNameIndex names;
	REQUIRE_MESSAGE(ObjectNameScan::build(*mount->fs, names, &err), err);
	std::printf("  info: scanned %zu INI files and %zu map.ini files: %zu object names, %zu road names\n",
		names.iniFilesScanned, names.mapIniFilesScanned, names.objectNames.size(), names.roadNames.size());

	RoadTypeIndex roadTypes;
	REQUIRE_MESSAGE(TerrainRoads::load(*mount->fs, roadTypes, &err), err);

	Counters c;
	auto t0 = std::chrono::steady_clock::now();
	std::vector<std::uint8_t> bytes;
	for (const std::string &path : list)
	{
		const std::string key = slashes(lowerStr(path), '/');
		INFO("map " << key);
		const JsonValue *sp = surveyMaps.get(key);
		REQUIRE(sp != nullptr);
		const JsonValue &s = *sp;

		REQUIRE_MESSAGE(mount->fs->readFile(path, bytes, &err), err);
		LoadedMap m;
		MapReadOptions opt;
		opt.strict = true; // zero leftover bytes, no unknown chunk
		if (!MapReader::load(bytes, key, opt, m, &err))
		{
			FAIL_CHECK("load failed: " << err);
			c.zeroLeftoverFailures.push_back(key + ": " + err);
			continue;
		}
		++c.maps;
		c.decodedBytes += m.decodedSize;

		// ---- envelope / ownership
		CHECK(archiveLabel(mount->fs->getArchiveFilenameForFile(path)) == J(s, "src").string);
		CHECK((std::int64_t)m.storedSize == N(J(s, "stored")));
		CHECK((std::int64_t)m.decodedSize == N(J(s, "decoded")));
		CHECK(m.envelope == "EAR");
		CHECK((std::int64_t)m.tocEntries == N(J(s, "toc")));
		CHECK(m.issues.empty());

		// ---- chunk structure: top-level order and every (parent/label) version
		std::string wantOrder;
		for (const JsonValue &o : J(s, "order").array)
		{
			wantOrder += o.string + ",";
		}
		CHECK(orderKey(m.topLevelOrder) == wantOrder);
		c.orders[wantOrder]++;
		std::map<std::string, std::set<int>> wantVersions;
		for (const auto &kv : J(s, "versions").object)
		{
			for (const JsonValue &v : kv.second.array)
			{
				wantVersions[kv.first].insert((int)N(v));
			}
		}
		CHECK(m.versions == wantVersions);
		for (const auto &kv : m.versions)
		{
			for (int v : kv.second)
			{
				c.versionFiles[kv.first][v]++;
			}
		}
		for (const ChunkStat &cs : m.chunkLog)
		{
			CHECK_MESSAGE(cs.parsed, "chunk " << cs.label << " was not parsed");
			CHECK_MESSAGE(cs.leftover == 0, "chunk " << cs.label << " left " << cs.leftover << " bytes");
			if (cs.label == "GlobalLighting")
			{
				c.lightingSizes.insert("v" + std::to_string(cs.version) + ":" + std::to_string(cs.size));
			}
		}

		// ---- heightmap
		const JsonValue &hm = J(s, "heightMap");
		const WorldHeightMap &w = m.heightMap;
		CHECK(w.m_width == N(J(hm, "w")));
		CHECK(w.m_height == N(J(hm, "h")));
		CHECK(w.m_borderSize == N(J(hm, "border")));
		const auto &wb = J(hm, "boundaries").array;
		REQUIRE(w.m_boundaries.size() == wb.size());
		for (size_t i = 0; i < wb.size(); ++i)
		{
			CHECK(w.m_boundaries[i].x == N(wb[i].array[0]));
			CHECK(w.m_boundaries[i].y == N(wb[i].array[1]));
		}
		CHECK(w.crcHeights() == (std::uint32_t)N(J(hm, "crc")));
		std::uint16_t mn = 65535, mx = 0;
		std::int64_t sum = 0;
		for (std::uint16_t h : w.m_data)
		{
			mn = std::min(mn, h);
			mx = std::max(mx, h);
			sum += h;
		}
		CHECK(mn == N(J(hm, "min")));
		CHECK(mx == N(J(hm, "max")));
		CHECK(sum == N(J(hm, "sum")));

		// ---- blend tile data
		const JsonValue &bl = J(s, "blend");
		REQUIRE(w.m_hasBlendTileData);
		CHECK(w.m_blendTileVersion == N(J(bl, "version")));
		CHECK(w.m_rawCrc.tile == (std::uint32_t)N(J(bl, "tileCrc")));
		CHECK(w.m_rawCrc.blend == (std::uint32_t)N(J(bl, "blendCrc")));
		CHECK(w.m_rawCrc.extraBlend == (std::uint32_t)N(J(bl, "extraCrc")));
		CHECK(w.m_rawCrc.cliffInfo == (std::uint32_t)N(J(bl, "cliffCrc")));
		CHECK(w.m_rawCrc.cliffState == (std::uint32_t)N(J(bl, "cliffStateCrc")));
		CHECK(w.m_numBitmapTiles == N(J(bl, "numBitmapTiles")));
		CHECK(w.m_numBlendedTiles == N(J(bl, "numBlendedTiles")));
		CHECK(w.m_numCliffInfo == N(J(bl, "numCliffInfo")));
		const auto &wc = J(bl, "classes").array;
		REQUIRE(w.m_textureClasses.size() == wc.size());
		int tileSum = 0;
		for (size_t i = 0; i < wc.size(); ++i)
		{
			CHECK(w.m_textureClasses[i].firstTile == N(wc[i].array[0]));
			CHECK(w.m_textureClasses[i].numTiles == N(wc[i].array[1]));
			CHECK(w.m_textureClasses[i].width == N(wc[i].array[2]));
			CHECK(w.m_textureClasses[i].legacy == 0);
			CHECK(w.m_textureClasses[i].name == wc[i].array[3].string);
			tileSum += w.m_textureClasses[i].numTiles;
		}
		CHECK_MESSAGE(w.m_numBitmapTiles == tileSum, "numBitmapTiles != sum(numTiles)");
		CHECK(w.m_edgeTextureClasses.empty()); // always 0 in the corpus
		CHECK(w.m_numEdgeTiles == 0);
		{
			std::map<std::string, int> dirs, inv, longs;
			for (size_t i = 1; i < w.m_blendedTiles.size(); ++i)
			{
				const TBlendTileInfo &b = w.m_blendedTiles[i];
				dirs[tupleStr(b.horiz, b.vert, b.rightDiagonal, b.leftDiagonal)]++;
				inv[std::to_string(b.inverted)]++;
				longs[std::to_string(b.longDiagonal)]++;
				CHECK(b.customBlendEdgeClass == -1);
			}
			auto cmp = [&](const char *name, const std::map<std::string, int> &got) {
				std::map<std::string, int> want;
				for (const auto &kv : J(bl, name).object)
				{
					want[kv.first] = (int)N(kv.second);
				}
				CHECK(got == want);
			};
			cmp("blendDirCounts", dirs);
			cmp("invertedCounts", inv);
			cmp("longCounts", longs);
		}
		// independent per-map statistics (btdstats.py)
		{
			const JsonValue &bs = J(s, "btdstats");
			std::int64_t maxTile = -1, minTile = 1 << 30;
			for (std::int16_t t : w.m_tileNdxes)
			{
				maxTile = std::max<std::int64_t>(maxTile, t);
				minTile = std::min<std::int64_t>(minTile, t);
			}
			CHECK(maxTile == N(J(bs, "maxTile")));
			CHECK(minTile == N(J(bs, "minTile")));
			CHECK((std::int64_t)w.m_textureClasses.size() == N(J(bs, "numClasses")));
			// the oracle counts raw non-zero indices; our arrays were patched, so add the patched count back
			auto nonzero = [](const std::vector<std::int32_t> &v) {
				std::int64_t n = 0;
				for (std::int32_t x : v) n += x != 0;
				return n;
			};
			CHECK(nonzero(w.m_blendTileNdxes) + w.m_patchReport.blendIndicesPatched == N(J(bs, "cellsBlended")));
			CHECK(nonzero(w.m_extraBlendTileNdxes) + w.m_patchReport.extraBlendIndicesPatched == N(J(bs, "cellsExtra")));
			CHECK(nonzero(w.m_cliffInfoNdxes) + w.m_patchReport.cliffIndicesPatched == N(J(bs, "cellsCliffUV")));
			// planes in the oracle's order: cliff state, A (v>=10), B (v>=11), taint (14<=v<25), extra pass (v>=15), visibility (v>=17)
			std::vector<size_t> planes = { popcount(w.m_cellCliffState) };
			if (w.m_blendTileVersion >= 10) planes.push_back(popcount(w.m_planeA));
			if (w.m_blendTileVersion >= 11) planes.push_back(popcount(w.m_planeB));
			if (w.m_blendTileVersion >= 14) planes.push_back(popcount(w.m_planeTaint));
			if (w.m_blendTileVersion >= 15) planes.push_back(popcount(w.m_planeExtraPass));
			if (w.m_blendTileVersion >= 17) planes.push_back(popcount(w.m_planeVisibility));
			const auto &pb = J(bs, "planeBits").array;
			REQUIRE(planes.size() == pb.size());
			for (size_t i = 0; i < pb.size(); ++i)
			{
				CHECK_MESSAGE((std::int64_t)planes[i] == N(pb[i]), "plane " << i);
			}
			if (w.m_blendTileVersion >= 16)
			{
				std::map<int, std::int64_t> flam;
				for (std::uint8_t f : w.m_flammability) flam[f]++;
				for (const JsonValue &fv : J(bs, "flam").array)
				{
					CHECK(flam[(int)N(fv.array[0])] == N(fv.array[1]));
				}
			}
		}
		c.cliffPatched += (size_t)w.m_patchReport.cliffIndicesPatched;
		c.blendPatched += (size_t)w.m_patchReport.blendIndicesPatched;
		c.extraPatched += (size_t)w.m_patchReport.extraBlendIndicesPatched;
		if (w.m_patchReport.cliffFormallyOutOfRange || w.m_patchReport.blendFormallyOutOfRange || w.m_patchReport.extraBlendFormallyOutOfRange)
		{
			c.mapsWithPatches.push_back(key + " (formally out of range: cliff " + std::to_string(w.m_patchReport.cliffFormallyOutOfRange)
				+ ", blend " + std::to_string(w.m_patchReport.blendFormallyOutOfRange) + ", extra "
				+ std::to_string(w.m_patchReport.extraBlendFormallyOutOfRange) + "; numCliffInfo " + std::to_string(w.m_numCliffInfo)
				+ ", cells " + std::to_string(w.m_dataSize) + ")");
			c.formalCliff = (size_t)w.m_patchReport.cliffFormallyOutOfRange;
			c.formalCliffNumCliffInfo = w.m_numCliffInfo;
			c.formalCliffCells = (size_t)w.m_dataSize;
		}

		// ---- world info
		if (const JsonValue *wi = s.get("worldInfo"))
		{
			for (const auto &kv : wi->object)
			{
				const Dict::Pair *p = m.chunks.worldInfo.find(kv.first);
				REQUIRE_MESSAGE(p != nullptr, "worldInfo key " << kv.first);
				if (kv.second.isString())
				{
					CHECK(p->s == kv.second.string);
				}
				else
				{
					double got = p->type == Dict::DICT_BOOL ? (p->b ? 1.0 : 0.0) : p->type == Dict::DICT_INT ? (double)p->i : (double)p->r;
					CHECK(got == kv.second.number);
				}
			}
			CHECK(m.chunks.worldInfo.getPairCount() == wi->object.size());
		}

		// ---- objects
		const JsonValue &ob = J(s, "objects");
		CHECK((std::int64_t)m.chunks.objects.size() == N(J(ob, "count")));
		std::map<std::string, int> flags;
		std::map<std::string, int> nameCounts;
		int empty = 0;
		for (const MapObject &o : m.chunks.objects)
		{
			flags[std::to_string(o.m_flags)]++;
			nameCounts[o.m_objectName]++;
			empty += o.m_objectName.empty();
			c.objectNameCounts[o.m_objectName]++;
		}
		std::map<std::string, int> wantFlags;
		for (const auto &kv : J(ob, "flags").object)
		{
			wantFlags[kv.first] = (int)N(kv.second);
		}
		CHECK(flags == wantFlags);
		CHECK(empty == N(J(ob, "emptyName")));
		{
			// the oracle's list of the "*" pseudo-template names this map places
			std::set<std::string> mine;
			for (const auto &kv : nameCounts)
			{
				if (!kv.first.empty() && kv.first[0] == '*') mine.insert(kv.first);
			}
			std::set<std::string> theirs;
			for (const JsonValue &v : J(ob, "starNames").array) theirs.insert(v.string);
			CHECK(mine == theirs);
			c.surveyStarNames.insert(theirs.begin(), theirs.end());
		}
		CHECK((std::int64_t)nameCounts.size() == N(J(ob, "distinctNames")));
		std::string lines;
		bool first = true;
		for (const auto &kv : nameCounts)
		{
			if (!first)
			{
				lines += "\n";
			}
			first = false;
			lines += kv.first + "\t" + std::to_string(kv.second);
		}
		CHECK(crc32Bytes(lines.data(), lines.size()) == (std::uint32_t)N(J(ob, "nameCountCrc")));
		for (const ChunkStat &cs : m.chunkLog)
		{
			c.maxChunkDepth = std::max(c.maxChunkDepth, cs.depth + 1); // depth 0 = top level = one level
		}
		c.objects += m.chunks.objects.size();
		c.objectsOutsideZhZ += (size_t)m.chunks.objectsOutsideZhZRange;
		c.emptyNameObjects += (size_t)empty;

		// template-name resolution against the INI object names (names only, see ObjectNameIndex.h)
		std::string mapIni = slashes(key.substr(0, key.find_last_of('/')), '\\') + "\\map.ini";
		std::set<std::string> seenUnresolved;
		for (const MapObject &o : m.chunks.objects)
		{
			if (!o.m_objectName.empty() && names.resolveObject(o, mapIni) == ObjectNameIndex::Unresolved
				&& seenUnresolved.insert(o.m_objectName).second)
			{
				c.unresolvedBy[o.m_objectName].push_back(key);
			}
		}

		// ---- terrain logic: every WaypointsList id names a waypoint object (spec 4.2); roads (spec 2.6)
		{
			TerrainLogic logic;
			std::vector<std::string> problems;
			logic.init(m.heightMap, m.chunks, &problems);
			const JsonValue &wp = J(s, "waypoints");
			CHECK((std::int64_t)logic.waypoints().size() == N(J(wp, "objects")));
			CHECK((std::int64_t)m.chunks.waypointLinks.size() == N(J(wp, "links")));
			CHECK((std::int64_t)problems.size() == N(J(wp, "badLinks"))); // links naming an id with no waypoint object
			for (const std::string &p : problems)
			{
				c.waypointProblems.push_back(key + ": " + p);
			}
			c.waypoints += logic.waypoints().size();
			c.waypointLinks += m.chunks.waypointLinks.size();

			// roads: ZH pairs a ROAD_POINT1 object with the object right after it when that has ROAD_POINT2 (names are
			// not compared); the spec author's roadchk.py additionally required equal names
			std::vector<RoadStrip> strips;
			RoadBuildReport rr;
			TerrainRoads::buildStrips(m.chunks.objects, roadTypes, m.heightMap, 0.0f, strips, rr);
			int sameName = 0;
			for (size_t i = 0; i + 1 < m.chunks.objects.size(); ++i)
			{
				if (m.chunks.objects[i].getFlag(FLAG_ROAD_POINT1) && m.chunks.objects[i + 1].getFlag(FLAG_ROAD_POINT2))
				{
					sameName += m.chunks.objects[i].m_objectName == m.chunks.objects[i + 1].m_objectName;
					++i;
				}
			}
			const JsonValue &rs = J(s, "roads");
			CHECK(rr.pairs == N(J(rs, "pairsFlag")));
			CHECK(sameName == N(J(rs, "pairsSameName")));
			CHECK(rr.orphanPoints == N(J(rs, "orphans")));
			std::set<std::string> names;
			for (const MapObject &o : m.chunks.objects)
			{
				if (o.getFlag(FLAG_ROAD_FLAGS))
				{
					names.insert(o.m_objectName);
				}
			}
			std::set<std::string> wantNames;
			for (const JsonValue &n : J(rs, "names").array) wantNames.insert(n.string);
			CHECK(names == wantNames);
			if (key.rfind("maps/", 0) == 0)
			{
				c.roadPairs += rr.pairs;
				c.roadSameName += (size_t)sameName;
				c.roadOrphans += rr.orphanPoints;
				c.roadUnknown += rr.unknownRoadTypes;
				c.roadDuplicates += rr.duplicateSegments;
				c.roadNames.insert(names.begin(), names.end());
				for (const std::string &u : rr.unknownNames) c.roadUnknownNames.insert(u);
			}
		}

		// ---- the other chunks
		CHECK((std::int64_t)m.chunks.waypointLinks.size() == N(J(s, "waypointLinks")));
		CHECK((std::int64_t)m.chunks.mpPositions.size() == N(J(s, "mpPositions")));
		size_t blEntries = 0;
		for (const SidesInfo &si : m.sides.sides) blEntries += si.buildList.size();
		for (const FactionBuildList &f : m.sides.factionBuildLists) blEntries += f.entries.size();
		CHECK((std::int64_t)blEntries == N(J(s, "buildListEntries")));
		CHECK((std::int64_t)m.sides.factionBuildLists.size() == N(J(s, "factionBuildLists")));
		size_t libRefs = 0;
		for (const auto &l : m.sides.libraryMaps) libRefs += l.size();
		CHECK((std::int64_t)libRefs == N(J(s, "libraryMapRefs")));
		CHECK((std::int64_t)m.chunks.triggerAreas.size() == N(J(s, "triggerAreas")));
		CHECK((std::int64_t)m.chunks.postEffects.size() == N(J(s, "postEffects")));
		CHECK((std::int64_t)m.chunks.cameraAnimations.size() == N(J(s, "cameraAnimations")));
		// per-side arrays are index-aligned with SidesList in every retail map (spec 2.10)
		CHECK(m.sides.libraryMaps.size() == m.sides.sides.size());
		CHECK(m.sides.factionBuildLists.size() == m.sides.sides.size());
		CHECK(m.playerScripts.lists.size() == m.sides.sides.size());

		const auto &water = J(s, "standingWater").array;
		REQUIRE(m.chunks.standingWaterAreas.size() == water.size());
		for (size_t i = 0; i < water.size(); ++i)
		{
			const StandingWaterArea &a = m.chunks.standingWaterAreas[i];
			CHECK(a.name == water[i].array[0].string);
			CHECK((double)a.uvScrollSpeed == water[i].array[1].number);
			CHECK((int)a.additiveBlending == N(water[i].array[2]));
			CHECK((std::int64_t)a.points.size() == N(water[i].array[3]));
			CHECK(a.waterHeight == N(water[i].array[4]));
		}
		const auto &rivers = J(s, "rivers").array;
		REQUIRE(m.chunks.riverAreas.size() == rivers.size());
		for (size_t i = 0; i < rivers.size(); ++i)
		{
			const RiverArea &a = m.chunks.riverAreas[i];
			CHECK(a.name == rivers[i].array[0].string);
			CHECK((double)a.uvScrollSpeed == rivers[i].array[1].number);
			char rgba[16];
			std::snprintf(rgba, sizeof(rgba), "%02x%02x%02x%02x", a.r, a.g, a.b, a.a0);
			CHECK(std::string(rgba) == rivers[i].array[3].string);
			CHECK((double)a.alpha == rivers[i].array[4].number);
			CHECK(a.waterHeight == N(rivers[i].array[5]));
			CHECK((std::int64_t)a.lines.size() == N(rivers[i].array[6]));
		}
		const auto &waves = J(s, "waves").array;
		REQUIRE(m.chunks.standingWaveAreas.size() == waves.size());
		for (size_t i = 0; i < waves.size(); ++i)
		{
			const StandingWaveArea &a = m.chunks.standingWaveAreas[i];
			CHECK(a.name == waves[i].array[0].string);
			CHECK((std::int64_t)a.points.size() == N(waves[i].array[3]));
			const auto &vals = waves[i].array[4].array;
			REQUIRE(vals.size() == 9);
			CHECK(a.finalWidth == N(vals[0]));
			CHECK(a.finalHeight == N(vals[1]));
			CHECK(a.initialWidthFraction == N(vals[2]));
			CHECK(a.initialHeightFraction == N(vals[3]));
			CHECK(a.initialVelocity == N(vals[4]));
			CHECK(a.timeToFadeMs == N(vals[5]));
			CHECK(a.timeToCompressMs == N(vals[6]));
			CHECK(a.timeOffset2ndWaveMs == N(vals[7]));
			CHECK(a.distanceFromShore == N(vals[8]));
		}

		// ---- environment data (macro/cloud textures)
		if (m.chunks.hasEnvironmentData)
		{
			const EnvironmentData &e = m.chunks.environment;
			std::string macroKey = "('" + e.macroTexture + "', " + std::to_string(e.isMacroTextureStretched ? 1 : 0) + ")";
			CHECK(J(s, "envMacro").get(macroKey) != nullptr);
			CHECK(J(s, "envCloud").get(e.cloudTexture) != nullptr);
		}
		std::set<std::string> classNames;
		for (const TXTextureClass &t : w.m_textureClasses) classNames.insert(t.name);
		std::set<std::string> wantClassNames;
		for (const JsonValue &n : J(s, "texClassNames").array) wantClassNames.insert(n.string);
		CHECK(classNames == wantClassNames);
		for (const TXTextureClass &t : w.m_textureClasses)
		{
			c.classTiles[t.name] = std::max(c.classTiles[t.name], t.numTiles);
		}

		// ---- scripts
		const JsonValue &sc = J(s, "scripts");
		size_t conds = 0, acts = 0, params = 0;
		std::map<std::string, int> condTail, actTail;
		std::function<void(const std::vector<ScriptItem> &)> walkItems = [&](const std::vector<ScriptItem> &items) {
			for (const ScriptItem &it : items)
			{
				if (it.group)
				{
					walkItems(it.group->items);
					continue;
				}
				const Script &sct = *it.script;
				for (const OrCondition &oc : sct.orConditions)
				{
					for (const ScriptCondition &cd : oc.conditions)
					{
						++conds;
						params += cd.params.size();
						if (cd.version >= 5) condTail["(" + std::to_string(cd.flagA) + ", " + std::to_string(cd.flagB) + ")"]++;
						c.condNames.insert(cd.internalName);
					}
				}
				for (const auto *list : { &sct.actions, &sct.falseActions })
				{
					for (const ScriptActionRec &a : *list)
					{
						++acts;
						params += a.params.size();
						if (a.version >= 3) actTail[std::to_string(a.tail)]++;
						c.actionNames.insert(a.internalName);
					}
				}
			}
		};
		for (const ScriptList &l : m.playerScripts.lists)
		{
			walkItems(l.items);
		}
		CHECK((std::int64_t)conds == N(J(sc, "conditions")));
		CHECK((std::int64_t)acts == N(J(sc, "actions")));
		CHECK((std::int64_t)params == N(J(sc, "parameters")));
		std::map<std::string, int> wantCondTail, wantActTail;
		for (const auto &kv : J(sc, "condTail").object) wantCondTail[kv.first] = (int)N(kv.second);
		for (const auto &kv : J(sc, "actionTail").object) wantActTail[kv.first] = (int)N(kv.second);
		CHECK(condTail == wantCondTail);
		CHECK(actTail == wantActTail);
	}
	auto t1 = std::chrono::steady_clock::now();
	std::printf("  info: parsed %d maps, %.1f MB decoded, in %.1f s\n", c.maps, c.decodedBytes / 1048576.0,
		std::chrono::duration<double>(t1 - t0).count());

	CHECK(c.maps == 181);
	CHECK(c.zeroLeftoverFailures.empty());

	// Per-chunk version counts against the spec table (spec 1.6) ...
	for (const auto &chunk : kSpecVersionTable)
	{
		std::map<int, int> got;
		auto it = c.versionFiles.find(chunk.first);
		if (it != c.versionFiles.end())
		{
			got = it->second;
		}
		CHECK_MESSAGE(got == chunk.second, "version counts of " << chunk.first);
	}
	// ... and no chunk label outside the spec's inventory (script chunks excluded from the table above)
	static const std::set<std::string> kScriptChunks = { "PlayerScriptsList/ScriptList", "ScriptList/Script", "ScriptList/ScriptGroup",
		"ScriptGroup/Script", "ScriptGroup/ScriptGroup", "Script/OrCondition", "OrCondition/Condition", "Script/ScriptAction", "Script/ScriptActionFalse" };
	for (const auto &kv : c.versionFiles)
	{
		const bool inInventory = kSpecVersionTable.count(kv.first) != 0 || kScriptChunks.count(kv.first) != 0;
		CHECK_MESSAGE(inInventory, "chunk not in the spec inventory: " << kv.first);
	}
	// script chunk versions (spec 1.6): ScriptGroup 2,3; Script 2,4; OrCondition 1; Condition 4,5,6; ScriptAction(+False) 2,3
	auto versionsOf = [&](const char *k) {
		std::set<int> v;
		auto it = c.versionFiles.find(k);
		if (it != c.versionFiles.end())
		{
			for (const auto &kv : it->second) v.insert(kv.first);
		}
		return v;
	};
	CHECK(versionsOf("PlayerScriptsList/ScriptList") == std::set<int>{ 1 });
	CHECK(versionsOf("ScriptList/ScriptGroup") == std::set<int>{ 2, 3 });
	CHECK(versionsOf("ScriptGroup/ScriptGroup") == std::set<int>{ 3 });
	CHECK(versionsOf("ScriptList/Script") == std::set<int>{ 2, 4 });
	CHECK(versionsOf("ScriptGroup/Script") == std::set<int>{ 2, 4 });
	CHECK(versionsOf("Script/OrCondition") == std::set<int>{ 1 });
	CHECK(versionsOf("OrCondition/Condition") == std::set<int>{ 4, 5, 6 });
	CHECK(versionsOf("Script/ScriptAction") == std::set<int>{ 2, 3 });
	CHECK(versionsOf("Script/ScriptActionFalse") == std::set<int>{ 2, 3 });

	// GlobalLighting chunk sizes: all 130 v8 chunks are 1360 bytes, all 51 v7 chunks 1348 (spec 1.7.17)
	CHECK(c.lightingSizes == (std::set<std::string>{ "v7:1348", "v8:1360" }));

	// top-level orders: the oracle's own tally (132 / 36 / 10 / 3). NOTE the spec text says 130 / 10 / 36 which
	// sums to 176 of 181 files: the spec's count for the main order is off by two and it omits the 3 files
	// without MPPositionList.
	std::map<int, int> orderSizes;
	for (const auto &kv : c.orders)
	{
		orderSizes[kv.second]++;
	}
	CHECK(c.orders.size() == 4);
	{
		std::vector<int> counts;
		for (const auto &kv : c.orders) counts.push_back(kv.second);
		std::sort(counts.begin(), counts.end());
		CHECK(counts == std::vector<int>{ 3, 10, 36, 132 });
	}

	// "patch bad maps" (ZH WorldHeightMap.cpp:533-545). The spec (1.7.2, 4.2) expects osgiliath's cliff indices to
	// be patched. They are only FORMALLY out of range: osgiliath has numCliffInfo == 0, so even the stored zeros
	// fail "index < numCliffInfo", and writing 0 over 0 changes nothing. No stored index in the corpus is
	// actually out of range (spec claim proved wrong).
	std::printf("  info: maps whose index arrays fail the range test: %zu; entries whose value the patch changed: cliff %zu, blend %zu, extra %zu\n",
		c.mapsWithPatches.size(), c.cliffPatched, c.blendPatched, c.extraPatched);
	for (const std::string &s : c.mapsWithPatches)
	{
		std::printf("        %s\n", s.c_str());
	}
	CHECK(c.cliffPatched == 0);
	CHECK(c.blendPatched == 0);
	CHECK(c.extraPatched == 0);
	CHECK(c.mapsWithPatches.size() == 1);
	if (c.mapsWithPatches.size() == 1)
	{
		CHECK(c.mapsWithPatches[0].find("map wor osgiliath") != std::string::npos);
		CHECK(c.formalCliffNumCliffInfo == 0);
		CHECK(c.formalCliff == c.formalCliffCells);
	}

	// objects
	std::printf("  info: %zu objects, %zu distinct template names, %zu objects beyond ZH's z range, %zu with an empty name\n",
		c.objects, c.objectNameCounts.size(), c.objectsOutsideZhZ, c.emptyNameObjects);
	std::printf("  info: deepest chunk nesting in the corpus: %d levels (DataChunkInput::MAX_CHUNK_NESTING = %d)\n", c.maxChunkDepth,
		(int)DataChunkInput::MAX_CHUNK_NESTING);
	CHECK(c.maxChunkDepth < (int)DataChunkInput::MAX_CHUNK_NESTING);
	CHECK(c.objects == 264616); // spec 2.7: "counts over 264,616 objects"
	CHECK(c.emptyNameObjects == 0); // the empty-name objects only occur in the excluded 2.02 maps (spec 1.9)
	std::printf("  info: unresolved object template names (not an INI Object/ChildObject/ObjectReskin, road, bridge, or *special): %zu\n",
		c.unresolvedBy.size());
	for (const auto &kv : c.unresolvedBy)
	{
		std::printf("        '%s' x%zu in %zu map(s), e.g. %s\n", kv.first.c_str(), c.objectNameCounts[kv.first], kv.second.size(), kv.second[0].c_str());
	}
	CHECK_MESSAGE(c.unresolvedBy.empty(), "unresolved object template names are listed above");
	{
		// the "*" names the loader treats as special are exactly the ones the corpus uses, no wildcard
		std::set<std::string> starNames;
		for (const auto &kv : c.objectNameCounts)
		{
			if (!kv.first.empty() && kv.first[0] == '*')
			{
				starNames.insert(kv.first);
				std::printf("        special name '%s' x%zu\n", kv.first.c_str(), kv.second);
			}
		}
		std::set<std::string> known(ObjectNameIndex::specialNames().begin(), ObjectNameIndex::specialNames().end());
		CHECK(starNames == known);
		CHECK(c.surveyStarNames == known); // and the independent survey names exactly those
	}

	// terrain texture classes (spec 2.3, [CORPUS terrres.py]): 990 distinct class names, every one resolves in
	// terrain.ini to a texture that exists, 534 have no "_nrm" normal map; the texture loader decodes them all
	{
		TerrainTypeIndex types;
		REQUIRE_MESSAGE(TerrainTypes::load(*mount->fs, types, &err), err);
		int unknown = 0, missingTex = 0, noNrm = 0, undecodable = 0, undersized = 0, topDown = 0, rle = 0;
		std::vector<std::string> topDownNames;
		for (const auto &kv : c.classTiles)
		{
			const std::string *tex = types.findTexture(kv.first);
			if (!tex)
			{
				++unknown;
				continue;
			}
			const std::string path = TerrainTypeIndex::textureArchivePath(*tex);
			if (!mount->fs->doesFileExist(path))
			{
				++missingTex;
				continue;
			}
			noNrm += !mount->fs->doesFileExist(TerrainTypeIndex::textureArchivePath(TerrainTypeIndex::normalMapName(*tex)));
			REQUIRE(mount->fs->readFile(path, bytes, &err));
			TGAImage img;
			if (!TGAFile::decode(bytes.data(), bytes.size(), img, &err))
			{
				++undecodable;
				rle += err.find("RLE") != std::string::npos;
				continue;
			}
			if (img.topDownFlag)
			{
				++topDown;
				topDownNames.push_back(*tex);
			}
			undersized += TerrainAtlas::countTiles(img.width, img.height) < kv.second;
		}
		std::printf("  info: %zu distinct terrain classes: %d unknown to terrain.ini, %d texture files missing, %d without _nrm, %d undecodable (%d RLE), %d undersized for their class, %d top-down TGAs\n",
			c.classTiles.size(), unknown, missingTex, noNrm, undecodable, rle, undersized, topDown);
		for (const std::string &n : topDownNames)
		{
			std::printf("        top-down TGA (retail flips it by ignoring the flag): %s\n", n.c_str());
		}
		CHECK(c.classTiles.size() == 990);
		CHECK(unknown == 0);
		CHECK(missingTex == 0);
		CHECK(noNrm == 534); // S-034
		CHECK(undecodable == 0);
		CHECK(undersized == 0);
		CHECK(topDown == 2); // spec 2.3: 2 retail terrain TGAs carry the top-down flag
	}

	// roads in the 127 files under maps/ (spec 2.6, [CORPUS roadchk.py]): 14389 valid pairs. That count requires both
	// points to carry the same road name; ZH ignores the second name, so 2 more pairs (14391) exist, and the 4
	// "orphan points" the spec reports are those 2 name-mismatched pairs. 54 road names.
	std::printf("  info: roads under maps/: %zu pairs by ZH's rule (%zu with equal names), %zu orphan points, %zu distinct road names, %zu pairs whose road type is not in roads.ini, %zu duplicate segments\n",
		c.roadPairs, c.roadSameName, c.roadOrphans, c.roadNames.size(), c.roadUnknown, c.roadDuplicates);
	for (const std::string &u : c.roadUnknownNames)
	{
		std::printf("        road type not in roads.ini: '%s'\n", u.c_str());
	}
	CHECK(c.roadSameName == 14389);
	CHECK(c.roadPairs == 14391);
	CHECK(c.roadOrphans == 0);
	CHECK(c.roadNames.size() == 54);
	// spec claim wrong (2.6: "54 road types, all present in roads.ini"): one road-flagged object is the shrub
	// template EttenmoorsShrub01, which is an Object, not a roads.ini road
	CHECK(c.roadUnknown == 1);
	CHECK(c.roadUnknownNames == (std::set<std::string>{ "EttenmoorsShrub01" }));
	// waypoints: the spec expects every WaypointsList link to name two waypoint objects
	std::printf("  info: %zu waypoints, %zu links in the corpus, %zu links name an id with no waypoint object\n", c.waypoints, c.waypointLinks, c.waypointProblems.size());
	std::set<std::string> badMaps;
	for (const std::string &p : c.waypointProblems)
	{
		badMaps.insert(p.substr(0, p.find(": ")));
	}
	for (const std::string &b : badMaps)
	{
		std::printf("        %s\n", b.c_str());
	}
	CHECK(c.waypoints == 5015); // spec 2.7: 5015 waypoint objects
	CHECK(c.waypointLinks == 1680);
	// spec claim wrong: 42 links in exactly one map ('cin fornost - peaceful pan - clean') name unknown ids
	CHECK(c.waypointProblems.size() == 42);
	CHECK(badMaps == (std::set<std::string>{ "maps/cin fornost - peaceful pan - clean/cin fornost - peaceful pan - clean.map" }));
	std::printf("  info: distinct condition internal names %zu, action internal names %zu\n", c.condNames.size(), c.actionNames.size());
}

TEST_CASE("map corpus: Minas Morgul cliff cells straddle their texture class and carry the per-pixel wrap rect (Sol review)")
{
	retailtest::Mount *mount = retailtest::pureMount();
	if (!mount)
	{
		retailtest::printSkip("map corpus cliff wrap");
		return;
	}
	REQUIRE_MESSAGE(mount->fs != nullptr, mount->error);
	std::string err;
	std::vector<std::uint8_t> bytes;
	const std::string path = "maps\\map wor minas morgul\\map wor minas morgul.map";
	REQUIRE_MESSAGE(mount->fs->readFile(path, bytes, &err), err);
	LoadedMap m;
	MapReadOptions opt;
	REQUIRE_MESSAGE(MapReader::load(bytes, path, opt, m, &err), err);
	TerrainTypeIndex types;
	REQUIRE_MESSAGE(TerrainTypes::load(*mount->fs, types, &err), err);
	TerrainAtlasImages images;
	TerrainAtlasReport report;
	REQUIRE_MESSAGE(TerrainAtlas::build(m.heightMap, *mount->fs, types, images, report, &err), err);
	HeightMapMeshOptions mo; // default: the 256-px hypothesis with per-pixel wrap
	std::vector<TerrainChunk> chunks;
	TerrainMeshStats stats;
	REQUIRE_MESSAGE(HeightMapMesh::build(m.heightMap, m.chunks.hasGlobalLighting ? &m.chunks.lighting : nullptr, mo, chunks, stats, &err), err);
	std::printf("  info: Minas Morgul: %zu base cliff cells, %zu with a corner outside their class block (they wrap per pixel)\n",
		stats.wrapCells, stats.straddlingCells);
	// Independent measurement by the Sol review of d661596d (it recomputed the cliff UVs from the map bytes): 1460
	// applicable base cliff cells, 1458 of which extend beyond their class and its 4-px gutter when the four corners
	// are only shifted together; e.g. cell (469,277) of CliffMinasMorgul01 reaches local V = 384 px in a 256-px class
	CHECK(stats.wrapCells == 1460);
	CHECK(stats.straddlingCells == 1458);
	// every one of those cells carries its class rect on all four vertices, and every wrapped sample of any
	// corner stays inside the block
	size_t withRect = 0, leaks = 0;
	for (const TerrainChunk &c : chunks)
	{
		const TerrainLayerMesh &L = c.layer[0];
		for (size_t v = 0; v + 3 < L.vertexCount(); v += 4)
		{
			ClassWrapRect r;
			r.x0 = L.wrap[v * 4];
			r.y0 = L.wrap[v * 4 + 1];
			r.w = L.wrap[v * 4 + 2];
			r.h = L.wrap[v * 4 + 3];
			if (!r.valid())
			{
				continue;
			}
			++withRect;
			for (size_t k = 0; k < 4; ++k)
			{
				float wu, wv;
				TerrainUv::wrapIntoClass(r, L.uv[(v + k) * 2], L.uv[(v + k) * 2 + 1], wu, wv);
				leaks += wu < r.x0 || wu > r.x0 + r.w || wv < r.y0 || wv > r.y0 + r.h;
			}
		}
	}
	CHECK(withRect == 1460);
	CHECK(leaks == 0);
}
