// OpenBFME unit tests: the Lua facts read from the RotWK binary (lane LUA-1; spec lua-scripting.md 2.4, 3.2, 3.3, 4.1, 4.3).
// engine/tests/data/lua/binary-facts.tsv is generated by tools/lua_binary_facts.py from a RotWK game.dat (addresses, names, counts: no retail
// bytes). The tests compare the engine's tables with it and, when RW_GAME_DAT names the game.dat, re-read the same facts from the binary
// with the C++ PE reader (a second, independent extraction). Without RW_GAME_DAT those tests print SKIP.
// Caveat S-001: this game.dat is community modified; spec 0.2 found no branch from the Lua library or the LuaScriptEngine unit into the
// added sections.

#include "doctest.h"

#include "LuaTestUtil.h"
#include "PeImage.h"
#include "RetailTestMount.h"

#include "GameLogic/ScriptEngine/LuaBindingNames.h"
#include "GameLogic/ScriptEngine/LuaXml.h"

#include <fstream>
#include <memory>
#include <sstream>

using luatest::run;
using retailtest::PeImage;

namespace
{
struct Fact
{
	std::string kind, index, value, extra;
};

const std::vector<Fact> &facts()
{
	static std::vector<Fact> all;
	if (all.empty())
	{
		std::ifstream f(retailtest::dataDir() + "/lua/binary-facts.tsv");
		REQUIRE_MESSAGE(f.good(), "engine/tests/data/lua/binary-facts.tsv is missing");
		std::string line;
		while (std::getline(f, line))
		{
			if (line.empty() || line[0] == '#')
			{
				continue;
			}
			Fact x;
			std::istringstream ss(line);
			std::getline(ss, x.kind, '\t');
			std::getline(ss, x.index, '\t');
			std::getline(ss, x.value, '\t');
			std::getline(ss, x.extra, '\t');
			all.push_back(x);
		}
	}
	return all;
}
std::vector<Fact> of(const char *kind)
{
	std::vector<Fact> out;
	for (const Fact &f : facts())
	{
		if (f.kind == kind)
		{
			out.push_back(f);
		}
	}
	return out;
}
std::string value(const char *kind, const char *key)
{
	for (const Fact &f : facts())
	{
		if (f.kind == kind && f.index == key)
		{
			return f.value;
		}
	}
	FAIL("no fact " << kind << " " << key);
	return "";
}
std::uint32_t parseHex(const std::string &s) { return (std::uint32_t)std::stoul(s, nullptr, 16); }
} // namespace

TEST_CASE("binary facts: the registration tables of the engine are the retail ones: 41 logic and 21 drawable functions, names and order")
{
	const std::vector<Fact> logic = of("logic"), drawable = of("drawable");
	REQUIRE(logic.size() == 41);
	REQUIRE(drawable.size() == 21);
	for (size_t i = 0; i < 41; ++i)
	{
		CHECK(logic[i].value == kLuaLogicBindingNames[i]);
		CHECK(logic[i].index == std::to_string(i));
	}
	for (size_t i = 0; i < 21; ++i)
	{
		CHECK(drawable[i].value == kLuaDrawableBindingNames[i]);
	}
	// _ALERT and GetFrame are the same function in both states
	CHECK(logic[0].extra == drawable[0].extra);
	CHECK(logic[1].extra == drawable[1].extra);
	// every other address is distinct: 60 distinct names, 60 distinct functions
	std::set<std::string> addresses;
	for (const Fact &f : logic)
	{
		addresses.insert(f.extra);
	}
	for (const Fact &f : drawable)
	{
		addresses.insert(f.extra);
	}
	CHECK(addresses.size() == 60);
}

TEST_CASE("binary facts: the five libraries register the names of the retail tables (33 + 11 + 11 + 23 + 5) and 37 / 19 / 11 / 23 / 5 function globals")
{
	luatest::Rig dummy;
	LuaReportSink sink;
	lua_State *L = lua_open(0x100);
	REQUIRE(L);
	void (*openers[5])(lua_State *) = { lua_baselibopen, lua_iolibopen, lua_strlibopen, lua_mathlibopen, lua_dblibopen };
	const char *libs[5] = { "lib_base", "lib_io", "lib_str", "lib_math", "lib_db" };
	const size_t tableSize[5] = { 33, 11, 11, 23, 5 };
	std::set<std::string> before;
	auto functionGlobals = [&] {
		lua_settop(L, 0);
		REQUIRE(lua_dostring(L, "names = '' foreach(globals(), function(k, v) if type(v) == 'function' then names = names .. k .. ' ' end end)") == 0);
		lua_getglobal(L, "names");
		std::set<std::string> s;
		std::istringstream in(lua_tostring(L, -1));
		std::string w;
		while (in >> w)
		{
			s.insert(w);
		}
		lua_settop(L, 0);
		return s;
	};
	for (int i = 0; i < 5; ++i)
	{
		openers[i](L);
		const std::set<std::string> now = functionGlobals();
		std::set<std::string> added;
		for (const std::string &n : now)
		{
			if (!before.count(n))
			{
				added.insert(n);
			}
		}
		const std::vector<Fact> table = of(libs[i]);
		REQUIRE(table.size() == tableSize[i]);
		for (const Fact &f : table)
		{
			INFO(libs[i] << " " << f.value);
			if (f.value == "_ERRORMESSAGE" && i == 1)
			{
				continue; // the io library's replaces the base library's: no new global name
			}
			CHECK(now.count(f.value) == 1);
		}
		static const size_t expected[5] = { 37, 19, 11, 23, 5 };
		CHECK(added.size() == expected[i]);
		before = now;
	}
	lua_close(L);
	// the type names of the six stock tags (RW 0xD0B298) and the seventh entry that is the bytes of "table"
	const std::vector<Fact> names = of("typename");
	REQUIRE(names.size() == 6);
	LuaReportSink s2;
	LuaRuntime rt(s2, "t");
	const int tags[6] = { 0, 1, 2, 3, 4, 5 };
	for (int i = 0; i < 6; ++i)
	{
		CHECK(std::string(lua_typename(rt.state(), tags[i])) == names[(size_t)i].value);
	}
	CHECK(value("typename_overrun", "6") == "0x6C626174");
}

TEST_CASE("binary facts: the 17 internal events, the entity table and the strings the engine uses are the retail ones")
{
	const std::vector<Fact> events = of("internal_event");
	REQUIRE(events.size() == 17);
	for (const Fact &f : events)
	{
		CHECK(f.value == kLuaInternalEventNames[std::stoi(f.index)]);
	}
	// the five entities decode to their characters in the lexer
	for (const Fact &f : of("xml_entity"))
	{
		EaXmlLexer x("<A>&" + f.value + ";</A>");
		REQUIRE(x.next() == EaXmlLexer::START);
		REQUIRE(x.next() == EaXmlLexer::TEXT);
		INFO(f.value);
		CHECK(x.tail() == f.extra);
	}
	// strings: through the behaviour that uses them
	CHECK(luatest::Rig::objectGlobalNameFormat() == value("string", "object_global"));
	CHECK(value("string", "alert_prefix") == "LUA Alert: ");
	CHECK(value("string", "scripts_lua") == "Data\\Scripts\\Scripts.lua");
	CHECK(value("string", "script_events_xml") == "Data\\Scripts\\ScriptEvents.xml");
	CHECK(value("string", "overlay_lua") == "%s\\Scripts.lua");
	CHECK(value("string", "overlay_xml") == "%s\\ScriptEvents.xml");
	CHECK(value("string", "xml_decl") == "<?xml version=\"1.0\"?>");
	CHECK(value("string", "root_element") == "SageLuaScriptSection");
	CHECK(value("string", "eventhandler") == "EventHandler");
	CHECK(value("string", "attr_eventname") == "EventName");
	CHECK(value("string", "attr_function") == "ScriptFunctionName");
	CHECK(value("string", "attr_debug") == "DebugSingleStep");
	CHECK(value("string", "attr_inherit") == "Inherit");
	CHECK(value("string", "attr_name") == "Name");
	CHECK(value("string", "conditions") == "Conditions");
	CHECK(value("string", "not_defined") == " is not defined.");
	CHECK(value("string", "not_a_function") == " is not a lua function.");
	CHECK(value("string", "number_format") == "%.16g");
	CHECK(value("string", "describe_named") == "Object %d (%s) [%s, owned by player %d (%ls)]");
	CHECK(value("string", "describe_unnamed") == "Object %d [%s, owned by player %d (%ls)]");
	CHECK(value("string", "describe_none") == "<No Object>");
	CHECK(value("string", "lua_version") == "Lua 4.0.1 Copyright (C) 1994-2000 TeCGraf, PUC-Rio $");
	CHECK(value("string", "true_text") == "true");
}

TEST_CASE("binary facts: the instructions behind the findings: OP_NOT tag first, dispatch depth `cmp 0xA; jg`, the second argument checked at index 1 (Q3)")
{
	CHECK(value("bytes", "op_not_tag_first") == "c746f0060000008b46f0");    // mov dword [esi-0x10], 6 ; mov eax, [esi-0x10]
	CHECK(value("bytes", "dispatch_depth_cmp") == "83bed40000000a0f8f");    // cmp dword [esi+0xD4], 0xA ; jg
	CHECK(value("bytes", "q3_second_arg_read") == "6a0257e8");              // push 2 ; push edi ; call (lua_toobjid of index 2)
	CHECK(value("bytes", "q3_second_arg_type") == "5557e8");                // push ebp (= 1) ; push edi ; call (lua_type of index 1)
}

// ---------------------------------------------------------------------------------------------------------------------
// the same facts read from the binary
// ---------------------------------------------------------------------------------------------------------------------
namespace
{
std::vector<std::pair<std::string, std::uint32_t>> scanRegistrations(const PeImage &pe, std::uint32_t lo, std::uint32_t hi)
{
	std::vector<std::uint8_t> code;
	REQUIRE(pe.read(lo, hi - lo, &code));
	std::vector<std::pair<std::string, std::uint32_t>> out;
	std::uint32_t pending = 0;
	for (size_t i = 0; i + 5 < code.size(); ++i)
	{
		if (code[i] != 0xE8)
		{
			continue;
		}
		const std::int32_t rel = (std::int32_t)((std::uint32_t)code[i + 1] | ((std::uint32_t)code[i + 2] << 8) | ((std::uint32_t)code[i + 3] << 16) | ((std::uint32_t)code[i + 4] << 24));
		const std::uint32_t target = lo + (std::uint32_t)i + 5 + (std::uint32_t)rel;
		// the last `push imm32` in the 16 bytes before the call
		std::uint32_t imm = 0;
		for (size_t b = i >= 16 ? i - 16 : 0; b + 5 <= i; ++b)
		{
			if (code[b] == 0x68)
			{
				const std::uint32_t v = (std::uint32_t)code[b + 1] | ((std::uint32_t)code[b + 2] << 8) | ((std::uint32_t)code[b + 3] << 16) | ((std::uint32_t)code[b + 4] << 24);
				const bool func = v >= 0x401000 && v < 0xB00000, text = v >= 0xBD0000 && v < 0xD20000;
				if ((target == 0xB5B890 && func) || (target == 0xB5BB70 && text))
				{
					imm = v;
				}
			}
		}
		if (target == 0xB5B890)
		{
			pending = imm;
		}
		else if (target == 0xB5BB70)
		{
			out.emplace_back(pe.cstring(imm), pending);
		}
		i += 4;
	}
	return out;
}
} // namespace

TEST_CASE("binary facts: re-read from game.dat: the registration sequences, the library tables, the type names, the entity table, the byte patterns")
{
	const PeImage *pe = PeImage::fromEnvironment();
	if (!pe)
	{
		retailtest::printSkip("binary facts: re-read from game.dat (set RW_GAME_DAT)");
		return;
	}
	const auto logic = scanRegistrations(*pe, 0x739C10, 0x73A0B9);
	const auto drawable = scanRegistrations(*pe, 0x737654, 0x7378E0);
	REQUIRE(logic.size() == 41);
	REQUIRE(drawable.size() == 21);
	const std::vector<Fact> expectedLogic = of("logic"), expectedDrawable = of("drawable");
	for (size_t i = 0; i < 41; ++i)
	{
		CHECK(logic[i].first == expectedLogic[i].value);
		CHECK(logic[i].second == parseHex(expectedLogic[i].extra));
		CHECK(logic[i].first == kLuaLogicBindingNames[i]);
	}
	for (size_t i = 0; i < 21; ++i)
	{
		CHECK(drawable[i].first == expectedDrawable[i].value);
		CHECK(drawable[i].second == parseHex(expectedDrawable[i].extra));
		CHECK(drawable[i].first == kLuaDrawableBindingNames[i]);
	}
	// libraries: luaL_reg tables
	const struct { const char *kind; std::uint32_t va; int count; } libs[5] = { { "lib_base", 0xD0ACB8, 33 }, { "lib_io", 0xD0A9A0, 11 }, { "lib_str", 0xD0A728, 11 }, { "lib_math", 0xD0A5F0, 23 }, { "lib_db", 0xD0A4D8, 5 } };
	for (const auto &lib : libs)
	{
		const std::vector<Fact> expected = of(lib.kind);
		REQUIRE((int)expected.size() == lib.count);
		for (int i = 0; i < lib.count; ++i)
		{
			CHECK(pe->cstring(pe->u32At(lib.va + 8 * (std::uint32_t)i)) == expected[(size_t)i].value);
			CHECK(pe->u32At(lib.va + 8 * (std::uint32_t)i + 4) == parseHex(expected[(size_t)i].extra));
		}
	}
	// the six type names and the overrun
	const std::vector<Fact> names = of("typename");
	for (int i = 0; i < 6; ++i)
	{
		CHECK(pe->cstring(pe->u32At(0xD0B298 + 4 * (std::uint32_t)i)) == names[(size_t)i].value);
	}
	CHECK(pe->u32At(0xD0B298 + 24) == 0x6C626174);
	CHECK(pe->cstring(0xD0B2B0) == "table");
	// the entity table
	for (const Fact &f : of("xml_entity"))
	{
		const std::uint32_t row = 0xDB72C4 + 8 * (std::uint32_t)std::stoi(f.index);
		CHECK(pe->cstring(pe->u32At(row)) == f.value);
		std::vector<std::uint8_t> ch;
		REQUIRE(pe->read(row + 4, 1, &ch));
		CHECK(std::string(1, (char)ch[0]) == f.extra);
	}
	// the strings and the byte patterns
	for (const Fact &f : of("string"))
	{
		INFO(f.index);
		const std::string text = pe->cstring(parseHex(f.extra));
		CHECK(text.substr(0, text.find('\n')) == f.value);
	}
	const std::pair<const char *, std::pair<std::uint32_t, size_t>> patterns[4] = {
		{ "op_not_tag_first", { 0xB63759, 10 } }, { "dispatch_depth_cmp", { 0x735F71, 9 } }, { "q3_second_arg_read", { 0x736B1A, 4 } }, { "q3_second_arg_type", { 0x736B2A, 3 } } };
	for (const auto &p : patterns)
	{
		CHECK(pe->hex(p.second.first, p.second.second) == value("bytes", p.first));
	}
	// the Lua library is statically linked: the identification string and _VERSION
	CHECK(pe->cstring(0xD0A3F0).find("$Lua: Lua 4.0.1 Copyright (C) 1994-2000 TeCGraf, PUC-Rio $") == 0);
	CHECK(pe->cstring(0xD0B134) == "Lua 4.0.1");
}
