#!/usr/bin/env python3
"""Extracts the name tables of the spell book port (lane SPELL-1) from a retail RotWK game.dat.

    ROTWK_INSTALL=<install dir> python3 tools/spell/extract_spell_tables.py [--check]

Reads <ROTWK_INSTALL>/game.dat at run time (pefile); nothing from the binary is stored except the name lists this script
writes to engine/src/Common/SpecialPowerNames.inc. --check re-extracts and fails when the committed file differs.

  SpecialPowerType  RW 0xDA5C90  (the `Enum` row of the SpecialPower field table RW 0xDA5FD8, parseIndexList RW 0x42E956)
  SpecialPower Flags RW 0xDA5F34 (the `Flags` row, parseBitString32 RW 0x42E840): the array has no NULL after its seven
                     flag names; the attribute modifier names follow it and scanIndexList walks on into them (35 names).
  OCL Disposition   RW 0xD9E3A8  (the CreateObject / CreateDebris `Disposition` row, parseBitString32 RW 0x42E840)
  CreateLocation    RW 0xDB32D8  (OCLSpecialPower `CreateLocation`, parseIndexList RW 0x42E956)

Caveat (PLAN rule 9, stop S-001): the RotWK game.dat on this project is the community-modified image.
"""
import argparse
import os
import struct
import sys
from pathlib import Path

import pefile

ROOT = Path(__file__).resolve().parent.parent.parent
OUT = ROOT / "engine" / "src" / "Common" / "SpecialPowerNames.inc"
LISTS = (("kSpecialPowerTypeNames", 0xDA5C90), ("kSpecialPowerFlagNames", 0xDA5F34), ("kOCLDispositionNames", 0xD9E3A8),
         ("kOCLCreateLocationNames", 0xDB32D8))


class Image:
    def __init__(self, path):
        self.pe = pefile.PE(path, fast_load=True)
        self.base = self.pe.OPTIONAL_HEADER.ImageBase

    def read(self, va, n):
        return self.pe.get_data(va - self.base, n)

    def cstr(self, va):
        out = bytearray()
        while True:
            b = self.read(va + len(out), 1)
            if b == b"\0":
                return out.decode("latin-1")
            out += b

    def names(self, va):
        out = []
        while True:
            p = struct.unpack("<I", self.read(va + 4 * len(out), 4))[0]
            if p == 0:
                return out
            out.append(self.cstr(p))


def render(img):
    lines = ["// Generated by tools/spell/extract_spell_tables.py from the RotWK game.dat. Do not edit.",
             "// Each list is the NULL-terminated name array the INI parser walks (scanIndexList); index = value / bit."]
    for name, va in LISTS:
        values = img.names(va)
        lines.append(f"// RW 0x{va:X}: {len(values)} names")
        lines.append(f"const char *const {name}[] = {{")
        lines += [f'\t"{v}",' for v in values]
        lines.append("\tnullptr")
        lines.append("};")
    return "\n".join(lines) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    install = os.environ.get("ROTWK_INSTALL")
    if not install:
        print("ROTWK_INSTALL is not set", file=sys.stderr)
        return 2
    text = render(Image(os.path.join(install, "game.dat")))
    if args.check:
        if OUT.read_text() != text:
            print(f"{OUT} differs from the binary", file=sys.stderr)
            return 1
        return 0
    OUT.write_text(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
