#!/usr/bin/env python3
"""Extracts the draw-module registries from a retail RotWK game.dat (lane DRAW-1).

    ROTWK_INSTALL=<install dir> python3 tools/draw/extract_draw_tables.py [--check]

Reads <ROTWK_INSTALL>/game.dat at run time (pefile); nothing from the binary is stored except the tables this script
prints. Output, written next to the engine sources:

  engine/src/Common/ModelConditionNames.inc        the ModelConditionFlags bit-name table (RW 0xD9FAD8)
  engine/tests/data/draw/draw_field_tables.json    the draw-module FieldParse tables and name lists
  engine/src/GameEngineDevice/W3DDevice/GameClient/Drawable/Draw/W3DModelDrawNameLists.inc   the name lists as C++ arrays

--check re-extracts and fails when the committed files differ (the tests pin the committed copies; this proves
the copies still match a binary).

Caveat (PLAN rule 9, stop S-001): the RotWK game.dat on this project is the community-modified image. The tables
below sit in .rdata/.data; the same token lists and row offsets were found in the BFME2 1.06 game.dat (table VAs
differ there) when this script was written.
"""
import argparse
import json
import os
import struct
import sys

import pefile

# RotWK game.dat virtual addresses (ModelConditionFlags: RW 0xD9FAD8 is the name array scanIndexList walks, used by
# BitFlags::parse at RW 0x4B5E05).
NAME_ARRAY = 0xD9FAD8

FIELD_TABLES = {
    # W3DModelDrawModuleData-style tables
    "W3DScriptedModelDraw": 0xBE1320,       # buildFieldParse at RW 0x4C893A adds this table only
    "W3DHordeModelDraw.LodOptions": 0xBDCAA0,  # one row; parse at RW 0x478B94 reads LOW/MEDIUM/HIGH then ...
    "LodOptions.row": 0xBDCA20,
    "ModelConditionState": 0xBE0A78,         # parse at RW 0x4C800E
    "AnimationState": 0xD99F60,              # parse at RW 0x4C8840 (also IdleAnimationState, TransitionState)
    "Animation": 0xBE04B8,                   # parse at RW 0x4C7A89
    "AttachModel": 0xBE06E8,                 # parse at RW 0x4C7E42
}

NAME_LISTS = {
    "WeaponSlotType": 0xDA12E4,
    "AnimationState.Flags": 0xD99F18,
    "Animation.AnimationMode": 0xD99EF8,
    "ShadowType": 0xD99EB0,
    "StaticGameLODLevel": 0xD9E6BC,
    "ParticleSysBone.FXTrigger": 0xD99E84,   # RW 0x4BCC4D
    "ParticleSysBone.Persist": 0xD99E70,
    "TimeOfDay": 0xDA3A68,                   # TimeOfDayTexture, RW 0x4C42A8
}


class Image:
    def __init__(self, path):
        self.pe = pefile.PE(path)
        self.base = self.pe.OPTIONAL_HEADER.ImageBase
        self.secs = [(s.Name.rstrip(b"\0").decode(), self.base + s.VirtualAddress, s.Misc_VirtualSize, s.get_data())
                     for s in self.pe.sections]

    def read(self, va, n):
        for _name, a, _sz, d in self.secs:
            if a <= va < a + len(d):
                return d[va - a:va - a + n]
        raise ValueError("VA %#x is outside every section" % va)

    def u32(self, va):
        return struct.unpack("<I", self.read(va, 4))[0]

    def cstr(self, va):
        try:
            b = self.read(va, 96)
        except ValueError:
            return None
        e = b.find(b"\0")
        if e <= 0:
            return None
        s = b[:e]
        return s.decode("latin1") if all(32 <= c < 127 for c in s) else None

    def in_text(self, va):
        return any(n == ".text" and a <= va < a + sz for n, a, sz, _ in self.secs)


def name_list(img, va, limit=None):
    out = []
    while limit is None or len(out) < limit:
        p = img.u32(va)
        s = img.cstr(p) if p else None
        if s is None:
            break
        out.append(s)
        va += 4
    return out


def field_table(img, va):
    rows = []
    while True:
        tok, fn, ud, off = struct.unpack("<IIII", img.read(va, 16))
        s = img.cstr(tok) if tok else None
        if s is None or not img.in_text(fn):
            break
        rows.append({"token": s, "parse": "%#x" % fn, "userData": "%#x" % ud, "offset": off})
        va += 16
    return rows


def extract(path):
    img = Image(path)
    out = {"nameArray": "%#x" % NAME_ARRAY, "tables": {}, "lists": {}}
    names = name_list(img, NAME_ARRAY)
    out["conditionNames"] = names
    for k, va in FIELD_TABLES.items():
        out["tables"][k] = {"va": "%#x" % va, "rows": field_table(img, va)}
    # Lists are read to their first NULL pointer exactly as INI::scanIndexList walks them. StaticGameLODLevel (RW 0xD9E6BC) is
    # NOT NULL terminated after its five names: the arrays of the neighbouring tables follow it, so retail's scanIndexList
    # walks all of them (48 entries). The run is reproduced as is (stop S-094 records it).
    for k, va in NAME_LISTS.items():
        out["lists"][k] = name_list(img, va, 256)
    return out


def inc_text(names):
    lines = ["// Generated by tools/draw/extract_draw_tables.py from the RotWK game.dat ModelConditionFlags name array",
             "// (RW 0xD9FAD8, %d names; index = bit number). Do not edit." % len(names)]
    for n in names:
        lines.append('"%s",' % n)
    return "\n".join(lines) + "\n"


LIST_IDENTS = {
    "WeaponSlotType": "kWeaponSlotNames",
    "AnimationState.Flags": "kAnimationStateFlagNames",
    "Animation.AnimationMode": "kAnimationModeNames",
    "ShadowType": "kShadowTypeNames",
    "StaticGameLODLevel": "kStaticGameLODNames",
    "ParticleSysBone.FXTrigger": "kFXTriggerNames",
    "ParticleSysBone.Persist": "kPersistNames",
    "TimeOfDay": "kTimeOfDayNames",
}


def lists_text(lists):
    lines = ["// Generated by tools/draw/extract_draw_tables.py from the RotWK game.dat name lists the draw module parsers use",
             "// (RW 0xDA12E4, 0xD99F18, 0xD99EF8, 0xD99EB0, 0xD9E6BC, 0xD99E84, 0xD99E70, 0xDA3A68). Do not edit."]
    for key, ident in LIST_IDENTS.items():
        lines.append("const char *const %s[] = {" % ident)
        for n in lists[key]:
            lines.append('\t"%s",' % n)
        lines.append("\tnullptr,")
        lines.append("};")
    return "\n".join(lines) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--root", default=os.path.normpath(os.path.join(os.path.dirname(__file__), "..", "..")))
    args = ap.parse_args()
    install = os.environ.get("ROTWK_INSTALL")
    if not install:
        print("ROTWK_INSTALL is not set", file=sys.stderr)
        return 2
    data = extract(os.path.join(install, "game.dat"))
    inc_path = os.path.join(args.root, "engine", "src", "Common", "ModelConditionNames.inc")
    lists_path = os.path.join(args.root, "engine", "src", "GameEngineDevice", "W3DDevice", "GameClient", "Drawable", "Draw",
                              "W3DModelDrawNameLists.inc")
    json_path = os.path.join(args.root, "engine", "tests", "data", "draw", "draw_field_tables.json")
    payload = {k: v for k, v in data.items() if k != "conditionNames"}
    payload["conditionNameCount"] = len(data["conditionNames"])
    jtext = json.dumps(payload, indent=1, sort_keys=False) + "\n"
    itext = inc_text(data["conditionNames"])
    ltext = lists_text(data["lists"])
    if args.check:
        ok = (open(inc_path, newline="").read() == itext and open(json_path, newline="").read() == jtext
              and open(lists_path, newline="").read() == ltext)
        print("committed tables match the binary" if ok else "committed tables DIFFER from the binary")
        return 0 if ok else 1
    os.makedirs(os.path.dirname(json_path), exist_ok=True)
    with open(inc_path, "w", newline="\n") as f:
        f.write(itext)
    with open(json_path, "w", newline="\n") as f:
        f.write(jtext)
    with open(lists_path, "w", newline="\n") as f:
        f.write(ltext)
    print("wrote %d condition names and %d tables" % (len(data["conditionNames"]), len(data["tables"])))
    return 0


if __name__ == "__main__":
    sys.exit(main())
