#!/usr/bin/env python3
"""Generates engine/src/GameLogic/WeaponNames.cpp from the golden name lists (lane WEAPON-1).

The lists are the binary's own enumerations (damage types, death types, weapon slots, ...), dumped by dump_tables.py into
engine/tests/data/weapon1/list_*.tsv. Engine code holds the full registry, never a subset (PLAN rule 6).

    python3 tools/weapon/gen_names.py            # rewrite the file
    python3 tools/weapon/gen_names.py --check    # exit 1 when it is out of date
"""
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
DATA = ROOT / "engine" / "tests" / "data" / "weapon1"
OUT = ROOT / "engine" / "src" / "GameLogic" / "WeaponNames.cpp"

LISTS = [
    ("TheDamageNames", "list_damage_type_names.tsv", "RW 0xDA15A8"),
    ("TheWeaponDeathNames", "list_weapon_death_type_names.tsv", "RW 0xDA1630"),
    ("TheDamageFXTypeNames", "list_damage_fx_type_names.tsv", "RW 0xDA1510"),
    ("TheFXTriggerNames", "list_fx_trigger_names.tsv", "RW 0xDA14FC"),
    ("TheWeaponReloadNames", "list_auto_reload_names.tsv", "RW 0xDA16BC"),
    ("TheWeaponPrefireNames", "list_pre_attack_type_names.tsv", "RW 0xDA16CC"),
    ("TheWeaponAffectsMaskNames", "list_radius_damage_affects_names.tsv", "RW 0xDA16E0"),
    ("TheWeaponCollideMaskNames", "list_projectile_collides_names.tsv", "RW 0xDA170C"),
    ("TheWeaponSlotTypeNames", "list_weapon_slot_names.tsv", "RW 0xDA12E4"),
    # RW 0xDA12FC has no terminator of its own: its 6 names run straight into the command source names at 0xDA1314 (a
    # scanIndexList over it sees all 9 entries, 6..8 being FROM_PLAYER, FROM_SCRIPT, FROM_AI)
    ("TheWeaponChoiceCriteriaNames", "list_weapon_choice_criteria_names.tsv", "RW 0xDA12FC"),
    ("TheCommandSourceMaskNames", "list_command_source_names.tsv", "RW 0xDA1314"),
    ("TheWeaponBonusConditionNames", "list_weapon_bonus_condition_names.tsv", "RW 0xDA1740"),
    ("TheWeaponBonusFieldNames", "list_weapon_bonus_field_names.tsv", "RW 0xDA179C"),
    ("TheVeterancyNames", "list_veterancy_names.tsv", "RW 0xD9F5E4"),
    ("TheDamageSubTypeNames", "list_damage_sub_type_names.tsv", "RW 0xDB5D9C"),
    ("TheEmotionTypeNames", "list_emotion_type_names.tsv", "RW 0xD9FA08"),
    ("TheAntiCategoryNames", "list_anti_category_names.tsv", "RW 0xD9FA40"),
    ("TheFireLogicTypeNames", "list_fire_logic_type_names.tsv", "RW 0xDB6694"),
    ("TheArmorSetNames", "list_armor_set_condition_names.tsv", "RW 0xD9FA80"),
    ("TheDamageFXBlockTypeNames", "list_damage_fx_block_type_names.tsv", "RW 0xDA5110"),
]

# {name, value} lookup lists: (symbol, tsv, where)
LOOKUPS = [
    ("TheWeaponSlotLookup", "lookup_weapon_slot_lookup.tsv", "RW 0xC16928"),
]


def render() -> str:
    out = [
        "// OpenBFME. GPL-3.0.",
        "//",
        "// GENERATED by tools/weapon/gen_names.py from the golden lists in engine/tests/data/weapon1; do not edit.",
        "// The binary's own name enumerations (full registries, PLAN rule 6). See GameLogic/Damage.h and GameLogic/Weapon.h.",
        "",
        '#include "GameLogic/Damage.h"',
        '#include "GameLogic/Weapon.h"',
        '#include "GameLogic/Armor.h"',
        '#include "GameLogic/ArmorSet.h"',
        '#include "GameLogic/DamageFX.h"',
        '#include "GameLogic/WeaponNugget.h"',
        '#include "GameLogic/WeaponSet.h"',
        "",
    ]
    for sym, fname, where in LISTS:
        names = [line.split("\t", 1)[1] for line in (DATA / fname).read_text().splitlines()]
        out.append(f"// {where}, {len(names)} names")
        out.append(f"const char *const {sym}[] = {{")
        for i in range(0, len(names), 4):
            out.append("\t" + ", ".join(f'"{n}"' for n in names[i:i + 4]) + ",")
        out.append("\tnullptr };")
        out.append("")
    for sym, fname, where in LOOKUPS:
        pairs = [line.split("\t")[1:] for line in (DATA / fname).read_text().splitlines()]
        out.append(f"// {where}, {len(pairs)} pairs")
        out.append(f"const LookupListRec {sym}[] = {{")
        for n, v in pairs:
            out.append(f'\t{{ "{n}", {v} }},')
        out.append("\t{ nullptr, 0 } };")
        out.append("")
    return "\n".join(out)


if __name__ == "__main__":
    text = render()
    if "--check" in sys.argv:
        sys.exit(0 if OUT.exists() and OUT.read_text() == text else 1)
    OUT.write_text(text, newline="\n")
    print("wrote", OUT)
