#!/usr/bin/env python3
# OpenBFME. GPL-3.0.
#
# Module coverage (lane MODULES-1): joins the runtime registry table the unit test writes
# (engine/tests/test_module_coverage.cpp, run with OPENBFME_MODULE_COVERAGE_OUT=<tsv>) with the
# census's module histogram (objects using each class, inheritance resolved) and writes the
# markdown table sorted by template count.
#
# Usage: module_coverage.py --table <tsv> --census <census.json> --out <module-coverage.md>
#        [--before <older tsv>]   (adds the totals of an earlier registry for comparison)

import argparse
import json
import sys

# W3DDrawKind (GameEngineDevice/W3DDevice/GameClient/Drawable/Draw/W3DDrawModules.h)
DRAW_KIND_NOTHING = 4
DRAW_KIND_NOT_DRAWN = 5


def read_table(path):
    rows = {}
    with open(path, encoding="utf-8") as f:
        header = f.readline().rstrip("\n").split("\t")
        for line in f:
            if not line.strip():
                continue
            rec = dict(zip(header, line.rstrip("\n").split("\t")))
            rows[(rec["class"], rec["type"])] = rec
    return rows


def coverage(rec):
    """The coverage status of one registry class: ported / base AI / parsed only / missing."""
    if rec["type"] == "Draw":
        kind = rec["drawkind"]
        if kind == "-":
            return "missing"
        kind = int(kind)
        if kind == DRAW_KIND_NOT_DRAWN:
            return "missing"  # an effect draw this engine does not draw (S-113)
        return "ported"  # drawn by the W3D draw runtime, or draws nothing in a release build like retail
    return {"ported": "ported", "base-ai": "base AI", "parsed-only": "parsed only", "missing": "missing"}[rec["status"]]


CATEGORY_TYPE = {"Draw": "Draw", "ClientUpdate": "ClientUpdate", "ClientBehavior": "ClientBehavior"}


def find(rows, cls, category):
    t = CATEGORY_TYPE.get(category, "Behavior")
    return rows.get((cls, t))


def totals(rows, hist):
    out = {}
    for e in hist:
        rec = find(rows, e["class"], e["category"])
        s = coverage(rec) if rec else "not registered"
        n, objs = out.get(s, (0, 0))
        out[s] = (n + 1, objs + e["objects"])
    return out


def main(argv):
    ap = argparse.ArgumentParser()
    ap.add_argument("--table", required=True)
    ap.add_argument("--census", required=True)
    ap.add_argument("--out", required=True)
    ap.add_argument("--before")
    args = ap.parse_args(argv)

    rows = read_table(args.table)
    census = json.load(open(args.census, encoding="utf-8"))
    hist = sorted(census["objects"]["module_histogram"], key=lambda e: (-e["objects"], e["class"]))
    total_templates = census["objects"]["total_templates"]

    lines = []
    lines.append("# Module coverage (base-game data vs. the runtime registry)")
    lines.append("")
    lines.append("Generated by `tools/rw_object_model/module_coverage.py` from the census module histogram "
                 "(`census/census.json`, %d templates, %d module classes used) and the registry table that "
                 "`engine/tests/test_module_coverage.cpp` writes (`OPENBFME_MODULE_COVERAGE_OUT`)." % (total_templates, len(hist)))
    lines.append("")
    lines.append("Status:")
    lines.append("- **ported**: a runtime class is bound in ModuleFactory (it may still report stops for parts it does not port); "
                 "a Draw class counts as ported when the W3D draw runtime draws it (or, like retail's release build, draws nothing);")
    lines.append("- **base AI**: an AI module class that runs as the base AIUpdateInterface, its own behaviour not ported (S-222);")
    lines.append("- **parsed only**: the module data is typed (fields parsed) but the runtime is the explicit UnportedModule (S-140);")
    lines.append("- **missing**: raw data and the UnportedModule (or an effect draw that is not drawn, S-113).")
    lines.append("")

    def totals_table(title, t):
        lines.append("### " + title)
        lines.append("")
        lines.append("| Status | Classes | Templates using them (sum) |")
        lines.append("|---|---:|---:|")
        for s in ("ported", "base AI", "parsed only", "missing", "not registered"):
            if s in t:
                lines.append("| %s | %d | %d |" % (s, t[s][0], t[s][1]))
        lines.append("")

    if args.before:
        totals_table("Totals before this lane", totals(read_table(args.before), hist))
        totals_table("Totals after this lane", totals(rows, hist))
    else:
        totals_table("Totals", totals(rows, hist))

    lines.append("## Per class (sorted by templates)")
    lines.append("")
    lines.append("| # | Module class | Category | Templates | Declarations | Status |")
    lines.append("|---:|---|---|---:|---:|---|")
    for i, e in enumerate(hist, 1):
        rec = find(rows, e["class"], e["category"])
        s = coverage(rec) if rec else "not registered"
        lines.append("| %d | %s | %s | %d | %d | %s |" % (i, e["class"], e["category"], e["objects"], e["declarations"], s))
    lines.append("")
    with open(args.out, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
