"""Tests for the object-model extractors.

The committed goldens (engine/data/rotwk-201/*.json) are checked structurally always, and
regenerated from the binary when RW_GAME_DAT is set (the regenerated bytes must equal the golden).
"""
from __future__ import annotations

import json
import os
import sys
from pathlib import Path

import pytest

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
DATA = HERE.parent.parent / "engine" / "data" / "rotwk-201"


def load(name):
    return json.loads((DATA / name).read_text(encoding="utf-8"))


def test_registry_golden_counts_and_masks():
    reg = load("module-registry.json")
    classes = reg["classes"]
    assert reg["addModuleSites"] == 330
    assert len(classes) == 329                      # 330 sites, WeaponBonusUpgrade registered twice
    by_name = {c["name"]: c for c in classes}
    assert len(by_name) == 329
    assert by_name["WeaponBonusUpgrade"]["sites"].__len__() == 2
    # masks read from the binary (spec 4.4, 5.1; brief): BODY 0x20, DRAW 0x400, CLIENT_UPDATE 0x800
    assert by_name["ActiveBody"]["mask"] == 0x20
    assert by_name["W3DScriptedModelDraw"]["mask"] == 0x400 and by_name["W3DScriptedModelDraw"]["type"] == 1
    assert by_name["WallHubBehavior"]["mask"] == 1
    assert by_name["CastleMemberBehavior"]["mask"] == 4
    assert by_name["WargBehavior"]["mask"] == 0 and by_name["RunOffMapBehavior"]["mask"] == 0
    assert sorted({c["type"] for c in classes}) == [0, 1, 2, 3]
    assert {c["mask"] for c in classes if c["type"] == 3} == {0x1000}
    # predicates: 13 AI classes (slot 4) and 11 body classes (slot 7); InactiveBody is a BODY class without slot 7
    assert sum(c["isAiModuleData"] for c in classes) == 13
    assert sum(c["slot7"] for c in classes) == 11
    assert by_name["InactiveBody"]["mask"] & 0x20 and not by_name["InactiveBody"]["slot7"]
    assert {c["name"] for c in classes if c["mask"] & 0x20 and not c["slot7"]} == {"InactiveBody"}


def test_registration_sequence_is_execution_order_not_alphabetical():
    reg = load("module-registry.json")
    seq = reg["registrationSequence"]
    assert len(seq) == 330
    assert [q["name"] for q in seq[:2]] == ["AutoHealBehavior", "WallHubBehavior"]
    # RW 0x464AD2 runs the 310-site function (0x6579C9) before the 20 draw classes
    assert all(q["type"] != 1 for q in seq[:310])
    assert all(q["type"] == 1 for q in seq[310:])
    assert sorted(q["site"] for q in seq) == sorted(s for c in reg["classes"] for s in c["sites"])
    assert seq[310]["name"] == "W3DDefaultDraw"


def test_field_tables_golden_shape():
    ft = load("field-tables.json")
    obj = ft["tables"][ft["objectTable"]["table"]]
    aud = ft["tables"][ft["audioTable"]["table"]]
    assert len(obj["rows"]) == 191 and obj["terminated"]
    assert len(aud["rows"]) == 56 and aud["terminated"]
    assert ft["audioTable"]["extra"] == 0x124
    names = [r["name"] for r in obj["rows"]]
    assert names[0] == "Hotkey" and "AddModule" in names and "OverrideableByLikeKind" not in names
    assert {"Behavior", "Body", "Draw", "ClientUpdate", "ClientBehavior"} <= set(names)
    # every class table and every block function resolves inside the closure
    reg = load("module-registry.json")
    for c in reg["classes"]:
        for t in c["tables"]:
            assert t["table"] in ft["tables"], c["name"]
    for f, info in ft["functions"].items():
        if info["kind"] == "block":
            for t in info["tables"]:
                assert t["table"] in ft["tables"], f
            if "dispatch" in info:
                for per in info["dispatch"]["tables"]:
                    for t in per:
                        assert t["table"] in ft["tables"]
    # the one script reader and the reviewed conditional openers
    assert [i for i in ft["functions"].values() if i["kind"] == "script"] == [{"kind": "script", "terminator": "ENDSCRIPT"}]
    assert ft["functions"]["0x73b723"]["conditional"]["opens"] == "unlessFloat"
    assert ft["functions"]["0x8b618c"]["conditional"]["value"] == "override"


@pytest.mark.skipif(not os.environ.get("RW_GAME_DAT"), reason="RW_GAME_DAT not set (path of the RotWK game.dat)")
def test_extractors_regenerate_the_goldens_byte_for_byte(tmp_path):
    import extract
    from rwimage import Image

    registry, field_tables = extract.build(Image())
    extract.dump(registry, tmp_path / "module-registry.json")
    extract.dump(field_tables, tmp_path / "field-tables.json")
    for name in ("module-registry.json", "field-tables.json"):
        assert (tmp_path / name).read_bytes() == (DATA / name).read_bytes(), name


def test_missing_game_dat_is_an_error(monkeypatch):
    pytest.importorskip("capstone")
    from rwimage import Image, ImageError

    monkeypatch.delenv("RW_GAME_DAT", raising=False)
    with pytest.raises(ImageError):
        Image()
