# Lane RELEASE-1: the version string of a build (main menu, every log, the package names), regenerated on every build (script mode):
#   cmake -DOUT=<file.cpp> -DROOT=<repo dir> [-DGIT=<git>] [-DVERSION_OVERRIDE=<string>] -P BuildVersion.cmake
# version = `git describe --tags --match "v[0-9]*" --exclude "*-playtest.*" --always --dirty --abbrev=10`, i.e. the last release tag of the rebuild
# plus the commits since it (the legacy codebase's v0.2.0-playtest.* tags are not this program's releases), or the bare commit before the first tag;
# "-dirty" when the tree had local changes. Without Git (a source export) the version is "untracked" unless the release pipeline passes VERSION_OVERRIDE:
# tools/release/package.sh refuses to package an untracked or dirty build.
# build date = the UTC day of the build (string(TIMESTAMP) honours SOURCE_DATE_EPOCH for reproducible builds).
# The file is rewritten only when its text changes, so an unchanged tree recompiles nothing.
# kBuildRecord (review r1: a grep for the commit hash accepted a mismatched library) is the one line tools/release/lib_provenance.py reads
# from a built library: "OPENBFME-BUILD-INFO 1 version=<v> commit=<sha> dirty=<0|1> engine-id=<64 hex> x86-32=<ON|OFF> id-options=<rest>".
# engine-id is the configure-time SHA-256 of the engine's sources (cmake/EngineId.cmake, ENGINE_ID / ID_X86_32 / ID_OPTIONS from cmake/Net.cmake):
# package.sh recomputes it from `git archive HEAD engine`, so a library built from other or uncommitted sources is refused. dirty = git
# describe --dirty (tracked changes anywhere in the tree at build time).
if(NOT OUT OR NOT ROOT)
    message(FATAL_ERROR "BuildVersion.cmake: OUT and ROOT are required")
endif()
set(_version "untracked")
set(_commit "none")
set(_dirty 1) # unknown provenance counts as dirty
if(VERSION_OVERRIDE)
    set(_version "${VERSION_OVERRIDE}")
endif()
if(GIT)
    execute_process(COMMAND "${GIT}" rev-parse HEAD WORKING_DIRECTORY "${ROOT}" OUTPUT_VARIABLE _sha OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET RESULT_VARIABLE _rc)
    if(_rc EQUAL 0 AND _sha)
        set(_commit "${_sha}")
        execute_process(COMMAND "${GIT}" describe --always --dirty=-dirty WORKING_DIRECTORY "${ROOT}" OUTPUT_VARIABLE _d OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
        if(_d MATCHES "-dirty$")
            set(_dirty 1)
        else()
            set(_dirty 0)
        endif()
        if(NOT VERSION_OVERRIDE)
            execute_process(COMMAND "${GIT}" describe --tags --match "v[0-9]*" --exclude "*-playtest.*" --always --dirty --abbrev=10
                WORKING_DIRECTORY "${ROOT}" OUTPUT_VARIABLE _describe OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET RESULT_VARIABLE _rc2)
            if(_rc2 EQUAL 0 AND _describe)
                set(_version "${_describe}")
            endif()
        endif()
    endif()
endif()
string(TIMESTAMP _date "%Y-%m-%d" UTC)
set(_text "// Generated by engine/cmake/BuildVersion.cmake at build time. Do not edit.\n")
string(APPEND _text "#include \"Common/BuildVersion.h\"\n\nnamespace BuildVersion\n{\n") # the extern declarations give the constants external linkage
string(APPEND _text "const char *const kVersion = \"${_version}\";\n")
string(APPEND _text "const char *const kCommit = \"${_commit}\";\n")
string(APPEND _text "const char *const kBuildDate = \"${_date}\";\n")
if(NOT ENGINE_ID)
    set(ENGINE_ID "none")
endif()
string(APPEND _text "const char *const kBuildRecord = \"OPENBFME-BUILD-INFO 1 version=${_version} commit=${_commit} dirty=${_dirty} engine-id=${ENGINE_ID} x86-32=${ID_X86_32} id-options=${ID_OPTIONS}\";\n")
string(APPEND _text "}\n")
set(_old "")
if(EXISTS "${OUT}")
    file(READ "${OUT}" _old)
endif()
if(NOT _old STREQUAL _text)
    file(WRITE "${OUT}" "${_text}")
endif()
