# Writes a C++ source that exposes each INPUTS file (by file name) through
#   bool GetEmbeddedDataFile(const std::string &name, std::string &out);
# Byte arrays, not string literals: MSVC caps string literals at 16 KB.
# Usage: cmake -DOUTPUT=<file.cpp> -DINPUTS=<a;b;c> -P EmbedFiles.cmake

set(body "// Generated by engine/cmake/EmbedFiles.cmake. Do not edit.\n#include <string>\n\nnamespace {\n")
set(table "")
set(index 0)
foreach(input IN LISTS INPUTS)
    get_filename_component(name "${input}" NAME)
    file(READ "${input}" hex HEX)
    string(LENGTH "${hex}" hexlen)
    math(EXPR size "${hexlen} / 2")
    string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," bytes "${hex}")
    string(APPEND body "const unsigned char data${index}[] = {${bytes}0};\n")
    string(APPEND table "    {\"${name}\", data${index}, ${size}},\n")
    math(EXPR index "${index} + 1")
endforeach()
string(APPEND body "struct Entry { const char *name; const unsigned char *data; unsigned long size; };\n")
string(APPEND body "const Entry entries[] = {\n${table}};\n}\n\n")
string(APPEND body "bool GetEmbeddedDataFile(const std::string &name, std::string &out)\n{\n")
string(APPEND body "    for (const Entry &e : entries)\n    {\n        if (name == e.name)\n        {\n")
string(APPEND body "            out.assign(reinterpret_cast<const char *>(e.data), e.size);\n            return true;\n        }\n    }\n    return false;\n}\n")
get_filename_component(outdir "${OUTPUT}" DIRECTORY)
file(MAKE_DIRECTORY "${outdir}")
file(WRITE "${OUTPUT}" "${body}")
