extends SceneTree
const Sim=preload("res://src/retail_slice/retail_slice_sim.gd")
const EXPECTED:=27
var passed:=0;var failed:=0
func _initialize()->void:call_deferred("_run")
func _run()->void:
	var sim:=_sim();var fear_source:=sim.entities[1] as Dictionary;var enemy:=sim.entities[10] as Dictionary;sim._attach_radiate_fear_contract(fear_source,_fear());_check("fear_attaches",fear_source.has("radiate_fear"));sim._step_radiate_fear_updates();_check("fear_inactive_before_trigger",not enemy.has("fear_state"));_check("fear_wrong_power_refused",not bool(sim.activate_radiate_fear(1,2).get("ok",false)));_check("fear_power_activates",bool(sim.activate_radiate_fear(1,1).get("ok",false)));sim._step_radiate_fear_updates();_check("fear_pulse_applies",String(enemy.get("fear_state",""))=="FEAR");var pulse_tick:=int(enemy.get("fear_pulse_tick",-1));sim.tick_index+=5;sim._step_radiate_fear_updates();_check("fear_interval_not_early",int(enemy.get("fear_pulse_tick",-1))==pulse_tick);sim.tick_index+=5;sim._step_radiate_fear_updates();_check("fear_interval_exact",int(enemy.get("fear_pulse_tick",-1))==sim.tick_index)
	sim._attach_poisoned_contract(enemy,_poison());var poison:=sim.apply_poison(10,10.0);_check("poison_arms",bool(poison.get("ok",false)));var initial_health:=int(enemy.get("health",0));sim.tick_index=int(poison.get("next_tick"))-1;sim._step_poisoned_behaviors();_check("poison_not_early",int(enemy.get("health",0))==initial_health);sim.tick_index+=1;sim._step_poisoned_behaviors();_check("poison_pulse_exact",int(enemy.get("health",0))==initial_health-10);sim.tick_index=int(poison.get("expires_tick"));sim._step_poisoned_behaviors();_check("poison_final_boundary_pulse",int((enemy["poisoned_behavior"] as Dictionary).get("pulse_count",0))>=2);sim.tick_index+=1;sim._step_poisoned_behaviors();_check("poison_expires",not bool((enemy["poisoned_behavior"] as Dictionary).get("active",true)))
	var field:=sim.structures[50] as Dictionary;sim._attach_damage_field_contract(field,_damage_field());_check("damage_field_attaches",field.has("damage_field"));var before:=int(enemy.get("health",0));sim.tick_index=int((field["damage_field"] as Dictionary).get("next_tick"))-1;sim._step_damage_fields();_check("field_not_early",int(enemy.get("health",0))==before);sim.tick_index+=1;field["completed_upgrades"]=[];sim._step_damage_fields();_check("field_upgrade_gate",int(enemy.get("health",0))==before);field["completed_upgrades"]=["Upgrade_Damage"];sim._step_damage_fields();_check("field_fires_exact",int(enemy.get("health",0))==before-7);var after:=int(enemy.get("health",0));sim.tick_index+=10;sim._step_damage_fields();_check("field_one_shot",int(enemy.get("health",0))==after);_check("field_respects_allies",int((sim.entities[2] as Dictionary).get("health",0))==100)
	var spawner:=sim.structures[60] as Dictionary;sim._attach_spawn_unit_contract(spawner,_spawn());sim._step_spawn_unit_behaviors();_check("command_spawn_waits",((spawner["spawn_unit_behavior"] as Dictionary).get("spawned_ids",[]) as Array).is_empty());_check("wrong_command_refused",not bool(sim.request_spawn_unit_command(60,"Wrong").get("ok",false)));_check("spawn_command_accepts",bool(sim.request_spawn_unit_command(60,"Command_ConstructFixture").get("ok",false)));sim._step_spawn_unit_behaviors();var spawned:=(spawner["spawn_unit_behavior"] as Dictionary).get("spawned_ids",[]) as Array;_check("spawn_exact_once",spawned.size()==1);_check("spawn_ownership",int((sim.entities[int(spawned[0])] as Dictionary).get("team",-1))==0);_check("repeat_spawn_refused",not bool(sim.request_spawn_unit_command(60,"Command_ConstructFixture").get("ok",false)))
	var unknown:=sim.structures[70] as Dictionary;sim._attach_spawn_unit_contract(unknown,{"module":"SpawnUnitBehavior","extraction":"typed","fields":{"UnitName":{"value":"MissingRetailUnit"}}});sim._step_spawn_unit_behaviors();_check("unknown_spawn_fails_closed",((unknown["spawn_unit_behavior"] as Dictionary).get("unsupported_semantics",[]) as Array).has("unresolved_spawn_unit:MissingRetailUnit"));var snap:=sim.snapshot();var hash:=sim.state_hash();var restored:=_sim();_check("snapshot_restore",restored.restore(snap));_check("hash_restore",restored.state_hash()==hash);print("FEAR_POISON_DAMAGE_SPAWN_RUNTIME_RESULT passed=%d failed=%d"%[passed,failed]);quit(0 if failed==0 and passed==EXPECTED else 1)
func _fear()->Dictionary:return {"module":"RadiateFearUpdate","extraction":"typed","fields":{"InitiallyActive":{"value":false},"TriggeredBy":{"value":"Upgrade_Fear"},"WhichSpecialPower":{"value":1},"GenerateFear":{"value":true},"EmotionPulseRadius":{"define":"FEAR_RADIUS"},"EmotionPulseInterval":{"milliseconds":1000},"VictimFilter":{"value":["ALL","ENEMIES"]}}}
func _poison()->Dictionary:return {"module":"PoisonedBehavior","extraction":"typed","fields":{"PoisonDamageInterval":{"milliseconds":1000},"PoisonDuration":{"milliseconds":3000}}}
func _damage_field()->Dictionary:return {"module":"DamageFieldUpdate","extraction":"typed","fields":{"Radius":{"value":100.0},"ObjectFilter":{"value":["ALL","ENEMIES"]},"RequiredUpgrade":{"value":"Upgrade_Damage"},"FireWeaponNugget":{"WeaponName":{"value":"FixtureDamageWeapon"},"FireDelay":{"milliseconds":200},"OneShot":{"value":true}}}}
func _spawn()->Dictionary:return {"module":"SpawnUnitBehavior","extraction":"typed","fields":{"UnitName":{"value":Sim.ARCHER_OBJECT_ID},"UnitCommand":{"value":"Command_ConstructFixture"},"SpawnOnce":{"value":true}}}
func _sim()->RetailSliceSim:
	var rules:={};for id in [Sim.SOLDIER_OBJECT_ID,Sim.SOLDIER_HORDE_ID,Sim.ARCHER_OBJECT_ID,Sim.TOWER_GUARD_OBJECT_ID,Sim.KNIGHT_OBJECT_ID]:rules[id]=_rule()
	var s:RetailSliceSim=Sim.new();s.setup({}, {"unit_rules":rules,"source_unit_scale":0.1,"fear_radius_defines":{"FEAR_RADIUS":100.0},"death_weapon_rules":{"FixtureDamageWeapon":{"damage":7.0,"radius_source":100.0,"damage_type":"MAGIC","affects":"ENEMIES"}}});s.ai_enabled=false;s.base_loop_enabled=false;s.entities.clear();s.structures.clear();s.entities[1]=_unit(1,0,Vector2.ZERO);s.entities[2]=_unit(2,0,Vector2(5,0));s.entities[10]=_unit(10,1,Vector2(5,0));s.structures[50]={"id":50,"team":0,"health":100,"position":Vector2.ZERO,"completed_upgrades":["Upgrade_Damage"]};s.structures[60]={"id":60,"team":0,"health":100,"position":Vector2(20,0)};s.structures[70]={"id":70,"team":0,"health":100,"position":Vector2.ZERO};return s
func _unit(id:int,team:int,pos:Vector2)->Dictionary:return {"id":id,"team":team,"health":100,"maximum_health":100,"member_health":[100],"position":pos,"destination":pos,"category":"infantry","kind_of":["INFANTRY"],"object_status":{},"timed_modifiers":{}}
func _rule()->Dictionary:return {"horde_id":Sim.SOLDIER_HORDE_ID,"category":"infantry","speed":1.0,"speed_source":10.0,"acceleration":1.0,"acceleration_source":10.0,"turn_rate_degrees_per_second":180.0,"braking":1.0,"braking_source":10.0,"attack_range":1.0,"attack_range_source":1.0,"minimum_attack_range":0.0,"minimum_attack_range_source":0.0,"vision_range":10.0,"vision_range_source":10.0,"delay_between_shots_ms":1000.0,"pre_attack_delay_ms":0.0,"firing_duration_ms":0.0,"attack_period_ticks":10,"pre_attack_ticks":0,"firing_duration_ticks":0,"member_damage":1,"member_health":100,"member_count":1,"formation_positions":[Vector3.ZERO],"provenance":{}}
func _check(label:String,condition:bool)->void:
	if condition:passed+=1
	else:failed+=1;push_error("FEAR_POISON_DAMAGE_SPAWN_RUNTIME_FAIL "+label)
