extends SceneTree
const Sim=preload("res://src/retail_slice/retail_slice_sim.gd")
const EXPECTED:=22
var passed:=0;var failed:=0
func _initialize()->void:call_deferred("_run")
func _run()->void:
	var sim:=_sim();var victim:=sim.entities[1] as Dictionary;sim._attach_hit_reaction_contract(victim,_hit());_check("hit_attaches",victim.has("hit_reaction"));var low:=sim.record_hit_reaction(1,5.0);_check("tier1_exact",int(low.get("tier",0))==1);var first_expiry:=int(low.get("expires_tick",-1));sim.tick_index+=1;var high:=sim.record_hit_reaction(1,45.0);_check("tier3_accumulates",int(high.get("tier",0))==3);_check("fast_hit_resets_expiry",int(high.get("expires_tick",0))>first_expiry);sim.tick_index=int(high.get("expires_tick"));sim._step_hit_reactions();_check("reaction_expires_exact",int((victim["hit_reaction"] as Dictionary).get("active_tier",-1))==0);(victim["hit_reaction"] as Dictionary)["hits"]=[];sim._apply_area_damage_to_battalion(1,5.0,"NORMAL");_check("damage_path_dispatches_reaction",int((victim["hit_reaction"] as Dictionary).get("active_tier",0))==1);var opaque:={};sim._attach_hit_reaction_contract(opaque,{"module":"HitReactionBehavior","extraction":"opaque","fields":{}});_check("opaque_hit_fails_closed",not opaque.has("hit_reaction"));_check("presentation_receipt",((victim["hit_reaction"] as Dictionary).get("unsupported_semantics",[]) as Array).has("reaction_animation_requires_presentation_binding"))
	var animal:=sim.entities[2] as Dictionary;sim.tick_index=0;sim._attach_animal_ai_contract(animal,_animal());sim._step_animal_ai_updates();_check("animal_flees_nearest_hostile",String(animal.get("state",""))=="flee");_check("flee_distance_exact",is_equal_approx(Vector2(animal.get("destination",Vector2.ZERO)).distance_to(Vector2(animal.get("position",Vector2.ZERO))),8.0));(sim.entities[10] as Dictionary)["position"]=Vector2(100,0);sim.tick_index=10;sim._step_animal_ai_updates();_check("wander_selected",String(animal.get("state",""))=="wander");_check("wander_radius_bounded",Vector2(animal.get("destination",Vector2.ZERO)).distance_to(Vector2((animal["animal_ai"] as Dictionary).get("home",Vector2.ZERO)))<=2.0001);var draws:=sim.logic_random_draws;sim._step_animal_ai_updates();_check("animal_timer_no_extra_rng",sim.logic_random_draws==draws)
	var finder:=sim.entities[3] as Dictionary;(sim.entities[10] as Dictionary)["position"]=Vector2(5,0);sim._attach_threat_finder_contract(finder,_threat());sim._step_threat_finders();_check("threat_acquires",int(finder.get("target_id",0))==10);_check("threat_kind",String(finder.get("target_kind",""))=="battalion");(sim.entities[10] as Dictionary)["position"]=Vector2(100,0);sim.tick_index+=1;sim._step_threat_finders();_check("threat_clears_policy",int((finder["threat_finder"] as Dictionary).get("last_target_id",-1))==0);_check("threat_clears_owned_target",int(finder.get("target_id",-1))==0);var malformed:={};sim._attach_threat_finder_contract(malformed,{"module":"ThreatFinderUpdate","extraction":"typed","fields":{"DefaultRadius":{"value":-1}}});_check("negative_threat_fails_closed",not malformed.has("threat_finder"))
	var snap:=sim.snapshot();var hash:=sim.state_hash();var restored:=_sim();_check("snapshot_restore",restored.restore(snap));_check("hash_restore",restored.state_hash()==hash);sim.tick_index+=10;restored.tick_index+=10;sim._step_animal_ai_updates();restored._step_animal_ai_updates();_check("rng_restore_identical",Vector2((sim.entities[2] as Dictionary).get("destination"))==Vector2((restored.entities[2] as Dictionary).get("destination")));_check("evolved_hash_identical",sim.state_hash()==restored.state_hash());print("HIT_ANIMAL_THREAT_RUNTIME_RESULT passed=%d failed=%d"%[passed,failed]);quit(0 if failed==0 and passed==EXPECTED else 1)
func _hit()->Dictionary:return {"module":"HitReactionBehavior","extraction":"typed","fields":{"HitReactionLifeTimer1":{"value":1000},"HitReactionThreshold1":{"value":5.0},"HitReactionLifeTimer2":{"value":2000},"HitReactionThreshold2":{"value":25.0},"HitReactionLifeTimer3":{"value":3000},"HitReactionThreshold3":{"value":50.0},"FastHitsResetReaction":{"value":true}}}
func _animal()->Dictionary:return {"module":"AnimalAIUpdate","extraction":"typed","fields":{"FleeRange":{"value":100.0},"FleeDistance":{"value":80.0},"WanderPercentage":{"value":100.0},"MaxWanderDistance":{"value":50.0},"MaxWanderRadius":{"value":20.0},"UpdateTimer":{"milliseconds":1000}}}
func _threat()->Dictionary:return {"module":"ThreatFinderUpdate","extraction":"typed","fields":{"DefaultRadius":{"value":100.0,"suffix":"f"}}}
func _sim()->RetailSliceSim:
	var rules:={};for id in [Sim.SOLDIER_OBJECT_ID,Sim.SOLDIER_HORDE_ID,Sim.ARCHER_OBJECT_ID,Sim.TOWER_GUARD_OBJECT_ID,Sim.KNIGHT_OBJECT_ID]:rules[id]=_rule()
	var s:RetailSliceSim=Sim.new();s.setup({}, {"unit_rules":rules,"source_unit_scale":0.1,"logic_random_seed":12345});s.ai_enabled=false;s.base_loop_enabled=false;s.entities.clear();s.structures.clear();s.entities[1]=_unit(1,0,Vector2.ZERO);s.entities[2]=_unit(2,0,Vector2.ZERO);s.entities[3]=_unit(3,0,Vector2.ZERO);s.entities[10]=_unit(10,1,Vector2(5,0));return s
func _unit(id:int,team:int,pos:Vector2)->Dictionary:return {"id":id,"team":team,"health":100,"maximum_health":100,"member_health":[100],"position":pos,"destination":pos,"category":"infantry","kind_of":["INFANTRY"],"state":"idle","target_id":0,"target_kind":"battalion","object_status":{},"timed_modifiers":{}}
func _rule()->Dictionary:return {"horde_id":Sim.SOLDIER_HORDE_ID,"category":"infantry","speed":1.0,"speed_source":10.0,"acceleration":1.0,"acceleration_source":10.0,"turn_rate_degrees_per_second":180.0,"braking":1.0,"braking_source":10.0,"attack_range":1.0,"attack_range_source":1.0,"minimum_attack_range":0.0,"minimum_attack_range_source":0.0,"vision_range":10.0,"vision_range_source":10.0,"delay_between_shots_ms":1000.0,"pre_attack_delay_ms":0.0,"firing_duration_ms":0.0,"attack_period_ticks":10,"pre_attack_ticks":0,"firing_duration_ticks":0,"member_damage":1,"member_health":100,"member_count":1,"formation_positions":[Vector3.ZERO],"provenance":{}}
func _check(label:String,condition:bool)->void:
	if condition:passed+=1
	else:failed+=1;push_error("HIT_ANIMAL_THREAT_RUNTIME_FAIL "+label)
