extends SceneTree
const Sim=preload("res://src/retail_slice/retail_slice_sim.gd")
const EXPECTED:=23
var passed:=0;var failed:=0
func _initialize()->void:call_deferred("_run")
func _run()->void:
	var sim:=_sim();var structure:Dictionary=sim.structures[50];sim._structure_module_contracts["barracks"]=[_production(),_getting(),_building()];sim._attach_structure_module_contracts(structure)
	_check("production_attaches",structure.has("production_update"));_check("getting_built_attaches",structure.has("getting_built_behavior"));_check("building_receipts",((structure.get("building_behavior",{}) as Dictionary).get("unsupported_semantics",[]) as Array).has("model_subobject_binding:FireName"));_check("queue_limit_consumed",int((structure["production_update"] as Dictionary).get("maximum_queue_entries",0))==1);_check("spawn_define_resolved",int((structure["getting_built_behavior"] as Dictionary).get("spawn_ticks",0))==20);_check("rebuild_timer_exact",int((structure["getting_built_behavior"] as Dictionary).get("rebuild_ticks",0))==30)
	var production_receipts:=(structure["production_update"] as Dictionary).get("unsupported_semantics",[]) as Array;var build_receipts:=(structure["getting_built_behavior"] as Dictionary).get("unsupported_semantics",[]) as Array
	_check("unexecuted_production_receipted",production_receipts.has("unsupported_production_semantic:UnitInvulnerableTime"));_check("unexecuted_spawn_receipted",build_receipts.has("unsupported_construction_semantic:SpawnTimer"));_check("unexecuted_rebuild_receipted",build_receipts.has("unsupported_construction_semantic:RebuildTimeSeconds"))
	var building:=structure["building_behavior"] as Dictionary
	_check("night_windows_preserve_order",building.get("night_windows",[])==["N_WINDOW","N_GLOW"]);_check("fire_windows_preserved",building.get("fire_windows",[])==["F_WINDOW"]);_check("glow_windows_preserved",building.get("glow_windows",[])==["G_WINDOW"]);_check("repeated_fire_names_preserve_order",building.get("fire_names",[])==["Fire01","Fire02"])
	var unresolved:={};sim._attach_getting_built_contract(unresolved,{"module":"GettingBuiltBehavior","extraction":"typed","fields":{"SpawnTimer":{"define":"MISSING_DEFINE","disabled":false}}});var unresolved_state:=unresolved.get("getting_built_behavior",{}) as Dictionary
	_check("unresolved_define_cannot_schedule",int(unresolved_state.get("spawn_ticks",0))==-1);_check("unresolved_define_receipted",(unresolved_state.get("unsupported_semantics",[]) as Array).has("unresolved_define:SpawnTimer"))
	var opaque:={};sim._attach_building_behavior_contract(opaque,{"module":"BuildingBehavior","extraction":"opaque","fields":{"FireName":[{"value":"Fire03"}]}});_check("opaque_contract_fails_closed",not opaque.has("building_behavior"))
	structure["completed_upgrades"]=["Upgrade_Faster"];var queued:=sim.queue_unit(0,50,Sim.SOLDIER_HORDE_ID);_check("queue_accepts",bool(queued.get("ok",false)));var item:=queued.get("item",{}) as Dictionary;_check("cost_modifier",int(item.get("cost",0))==50);_check("discount_used_for_resource_gate",sim.resources_for_team(0)==0);_check("time_modifier",int(item.get("duration_ticks",0))==5);_check("authored_queue_limit_blocks_second",String(sim.queue_unit(0,50,Sim.SOLDIER_HORDE_ID).get("reason",""))=="queue-full")
	var snap:=sim.snapshot();var hash:=sim.state_hash();var restored:=_sim();_check("snapshot_restore",restored.restore(snap));_check("hash_restore",restored.state_hash()==hash)
	print("PRODUCTION_GETTING_BUILT_RUNTIME_RESULT passed=%d failed=%d"%[passed,failed]);quit(0 if failed==0 and passed==EXPECTED else 1)
func _production()->Dictionary:return {"module":"ProductionUpdate","extraction":"typed","fields":{"MaxQueueEntries":{"value":1},"DoorOpeningTime":{"milliseconds":100},"UnitInvulnerableTime":{"milliseconds":500},"ProductionModifier":[{"RequiredUpgrade":{"value":"Upgrade_Faster"},"CostMultiplier":{"value":0.5},"TimeMultiplier":{"value":0.5},"ModifierFilter":{"value":["ANY"]}}]}}
func _getting()->Dictionary:return {"module":"GettingBuiltBehavior","extraction":"typed","fields":{"SpawnTimer":{"define":"BUILD_DELAY","disabled":false},"RebuildTimeSeconds":{"milliseconds":3000,"disabled":false},"RebuildWhenDead":{"value":true},"DisallowRebuildRange":{"value":100},"WorkerName":{"value":"Worker"}}}
func _building()->Dictionary:return {"module":"BuildingBehavior","extraction":"typed","fields":{"NightWindowName":{"value":["N_WINDOW","N_GLOW"]},"FireWindowName":{"value":["F_WINDOW"]},"GlowWindowName":{"value":["G_WINDOW"]},"FireName":[{"value":"Fire01"},{"value":"Fire02"}]}}
func _sim()->RetailSliceSim:
	var unit_rules:={};for oid in [Sim.SOLDIER_OBJECT_ID,Sim.SOLDIER_HORDE_ID,Sim.ARCHER_OBJECT_ID,Sim.TOWER_GUARD_OBJECT_ID,Sim.KNIGHT_OBJECT_ID]:unit_rules[oid]=_rule()
	var s:RetailSliceSim=Sim.new();s.setup({}, {"unit_rules":unit_rules,"getting_built_time_defines":{"BUILD_DELAY":2.0},"maximum_queue":5,"FIXTURE_COST":100,"FIXTURE_BUILD":10,"FIXTURE_CP":0});s.ai_enabled=false;s.base_loop_enabled=true;s.entities.clear();s.structures.clear();s.team_resources[0]=50;s._unit_production_rules[Sim.SOLDIER_HORDE_ID]={"object_id":Sim.SOLDIER_OBJECT_ID,"category":"infantry","default_cost":100,"default_build_ticks":10,"default_command_points":0,"cost_rule":"FIXTURE_COST","build_ticks_rule":"FIXTURE_BUILD","command_points_rule":"FIXTURE_CP","producer_routes":[{"producer_kind":"barracks"}]};s.structures[50]={"id":50,"team":0,"health":100,"construction_progress":1.0,"structure_kind":"barracks","production":[Sim.SOLDIER_HORDE_ID],"queue":[],"completed_upgrades":[]};return s
func _rule()->Dictionary:return {"horde_id":Sim.SOLDIER_HORDE_ID,"category":"infantry","speed":1.0,"speed_source":10.0,"acceleration":1.0,"acceleration_source":10.0,"turn_rate_degrees_per_second":180.0,"braking":1.0,"braking_source":10.0,"attack_range":1.0,"attack_range_source":1.0,"minimum_attack_range":0.0,"minimum_attack_range_source":0.0,"vision_range":10.0,"vision_range_source":10.0,"delay_between_shots_ms":1000.0,"pre_attack_delay_ms":0.0,"firing_duration_ms":0.0,"attack_period_ticks":10,"pre_attack_ticks":0,"firing_duration_ticks":0,"member_damage":1,"member_health":100,"member_count":1,"formation_positions":[Vector3.ZERO],"provenance":{}}
func _check(l:String,c:bool)->void:if c:passed+=1
else:failed+=1;push_error("PRODUCTION_GETTING_BUILT_RUNTIME_FAIL "+l)
