extends SceneTree
const Sim=preload("res://src/retail_slice/retail_slice_sim.gd")
const EXPECTED:=22
var passed:=0;var failed:=0
func _initialize()->void:call_deferred("_run")
func _run()->void:
	var sim:=_sim();var structure:=sim.structures[50] as Dictionary;sim._structure_module_contracts["barracks"]=[_exit_contract()];sim._attach_structure_module_contracts(structure)
	var exit:=structure.get("queue_production_exit_update",{}) as Dictionary
	_check("exit_typed_attaches",not exit.is_empty());_check("exit_delay_exact",(exit.get("exit_delay_ticks",[]) as Array)==[3]);_check("exit_points_ordered",(exit.get("create_points_source",[]) as Array)==[Vector2(20,30),Vector2(40,50)])
	_check("queue_accepts",bool(sim.queue_unit(0,50,Sim.SOLDIER_HORDE_ID).get("ok",false)));sim.advance(2);var produced_id:=int(sim.entity_ids()[0]);var produced:=sim.entities[produced_id] as Dictionary
	_check("authored_create_point",Vector2(produced.get("production_exit_destination",Vector2.ZERO)).is_equal_approx(Vector2(12,23)));_check("authored_rally_point",Vector2(produced.get("production_rally",Vector2.ZERO)).is_equal_approx(Vector2(15,20)));_check("authored_exit_duration",int(produced.get("production_exit_duration_ticks",0))==3)
	var invalid:={};sim._attach_queue_production_exit_contract(invalid,{"module":"QueueProductionExitUpdate","extraction":"typed","fields":{"UnitCreatePoint":[{"validNumeric":false,"value":null}]}});_check("invalid_coordinate_fails_closed",(invalid["queue_production_exit_update"] as Dictionary).get("create_points_source",[]).is_empty());_check("invalid_exit_not_executable",not bool((invalid["queue_production_exit_update"] as Dictionary).get("executable",true)))
	var parent:={"id":70,"team":0,"health":100,"member_health":[100,0],"member_maximum_health":100,"position":Vector2.ZERO,"completed_upgrades":[]};var banner:={"id":71,"team":0,"health":10,"position":Vector2.ZERO,"is_banner_carrier":true,"banner_parent_entity_id":70,"object_id":"Banner"};sim.entities[70]=parent;sim.entities[71]=banner;sim._attach_banner_carrier_update_contract(banner,_banner_contract())
	sim._step_banner_replenishment(banner);_check("banner_replenishes_one_member",parent.get("member_health",[])==[100,100]);_check("banner_replenish_health_rebuilt",int(parent.get("health",0))==200)
	parent["banner_entity_id"]=71;sim._on_banner_carrier_defeated(banner);_check("banner_respawn_uses_longer_authored_timer",int(parent.get("banner_respawn_ticks_remaining",0))==7);_check("banner_fx_receipted",((banner["banner_carrier_update"] as Dictionary).get("unsupported_semantics",[]) as Array).has("presentation_binding:UnitSpawnFX"))
	var fallback_parent:={"id":72,"team":0,"health":100,"unit_type":"ParentType","member_health":[100],"member_maximum_health":100};var fallback_banner:={"id":73,"team":0,"health":0,"banner_parent_entity_id":72,"object_id":"FallbackBanner"};sim.entities[72]=fallback_parent;sim._unit_banner_carriers["ParentType"]={"respawn_ticks":9};sim._attach_banner_carrier_update_contract(fallback_banner,{"module":"BannerCarrierUpdate","extraction":"typed","fields":{"IdleSpawnRate":{"milliseconds":100}}});sim._on_banner_carrier_defeated(fallback_banner);_check("absent_typed_death_timer_does_not_invent_zero",int(fallback_parent.get("banner_respawn_ticks_remaining",0))==9)
	var hero:=_hero(80);sim._attach_respawn_update_contract(hero,_respawn_update());sim._attach_respawn_body_contract(hero,_respawn_body(true));_check("body_max_health_applied",int(hero.get("member_maximum_health",0))==250);_check("body_health_scaled",int(hero.get("health",0))==250)
	sim.entities[81]={"id":81,"team":1,"category":"hero","kind_of":["HERO"]};sim._schedule_respawn_update(80,hero,"NORMAL",81);_check("permanent_killer_filter_blocks",not sim.respawn_schedules.has(80))
	var no_respawn:=_hero(82);sim._attach_respawn_update_contract(no_respawn,_respawn_update());sim._attach_respawn_body_contract(no_respawn,_respawn_body(false));sim._schedule_respawn_update(82,no_respawn);_check("can_respawn_false_blocks",not sim.respawn_schedules.has(82))
	var ordinary:=_hero(83);sim._attach_respawn_update_contract(ordinary,_respawn_update());sim._attach_respawn_body_contract(ordinary,_respawn_body(true));sim._schedule_respawn_update(83,ordinary,"NORMAL",0);_check("ordinary_death_schedules",sim.respawn_schedules.has(83));_check("body_presentation_receipt",((ordinary["respawn_body"] as Dictionary).get("unsupported_semantics",[]) as Array).has("presentation_binding:HealingBuffFX"))
	sim.entities[80]=hero;sim.entities[82]=no_respawn;sim.entities[83]=ordinary;var snap:=sim.snapshot();var hash:=sim.state_hash();var restored:=_sim();_check("snapshot_restore",restored.restore(snap));_check("hash_restore",restored.state_hash()==hash)
	print("QUEUE_BANNER_RESPAWN_BODY_RUNTIME_RESULT passed=%d failed=%d"%[passed,failed]);quit(0 if failed==0 and passed==EXPECTED else 1)
func _exit_contract()->Dictionary:return {"module":"QueueProductionExitUpdate","extraction":"typed","fields":{"UnitCreatePoint":[{"validNumeric":true,"value":{"x":20.0,"y":30.0,"z":0.0}},{"validNumeric":true,"value":{"x":40.0,"y":50.0,"z":0.0}}],"NaturalRallyPoint":[{"validNumeric":true,"value":{"x":50.0,"y":0.0,"z":0.0}}],"ExitDelay":[{"milliseconds":300}],"PlacementViewAngle":[{"value":90.0}]}}
func _banner_contract()->Dictionary:return {"module":"BannerCarrierUpdate","extraction":"typed","fields":{"IdleSpawnRate":{"milliseconds":100},"DiedRespawnTime":{"milliseconds":500},"MeleeFreeBannerRespawnTime":{"milliseconds":700},"ReplenishNearbyHorde":{"value":true},"UnitSpawnFX":{"value":"FX_Spawn"}}}
func _respawn_update()->Dictionary:return {"module":"RespawnUpdate","extraction":"typed","fields":{"RespawnRules":{"autoSpawn":true,"cost":0,"timeMilliseconds":100,"healthPercent":100.0},"AutoRespawnAtObjectFilter":{"value":["ANY"]}}}
func _respawn_body(can_respawn:bool)->Dictionary:return {"module":"RespawnBody","extraction":"typed","fields":{"MaxHealth":{"define":"HERO_HEALTH"},"RecoveryTime":{"value":5000},"CanRespawn":{"value":can_respawn},"PermanentlyKilledByFilter":{"value":["+HERO"]},"HealingBuffFX":{"value":"FX_Heal"}}}
func _hero(id:int)->Dictionary:return {"id":id,"team":0,"category":"hero","unit_type":"Hero","object_id":"Hero","health":100,"maximum_health":100,"member_maximum_health":100,"member_health":[100],"level":1,"position":Vector2.ZERO}
func _sim()->RetailSliceSim:
	var unit_rules:={};for oid in [Sim.SOLDIER_OBJECT_ID,Sim.SOLDIER_HORDE_ID,Sim.ARCHER_OBJECT_ID,Sim.TOWER_GUARD_OBJECT_ID,Sim.KNIGHT_OBJECT_ID]:unit_rules[oid]=_rule()
	var s:RetailSliceSim=Sim.new();s.setup({}, {"unit_rules":unit_rules,"respawn_body_defines":{"HERO_HEALTH":250},"source_unit_scale":0.1,"FIXTURE_COST":0,"FIXTURE_BUILD":1,"FIXTURE_CP":0});s.ai_enabled=false;s.base_loop_enabled=true;s.entities.clear();s.structures.clear();s.team_resources[0]=100;s._unit_production_rules[Sim.SOLDIER_HORDE_ID]={"object_id":Sim.SOLDIER_OBJECT_ID,"category":"infantry","default_cost":0,"default_build_ticks":1,"default_command_points":0,"cost_rule":"FIXTURE_COST","build_ticks_rule":"FIXTURE_BUILD","command_points_rule":"FIXTURE_CP","producer_routes":[{"producer_kind":"barracks"}]};s.structures[50]={"id":50,"team":0,"health":100,"position":Vector2(10,20),"construction_progress":1.0,"structure_kind":"barracks","production":[Sim.SOLDIER_HORDE_ID],"queue":[],"completed_upgrades":[]};return s
func _rule()->Dictionary:return {"horde_id":Sim.SOLDIER_HORDE_ID,"category":"infantry","speed":1.0,"speed_source":10.0,"acceleration":1.0,"acceleration_source":10.0,"turn_rate_degrees_per_second":180.0,"braking":1.0,"braking_source":10.0,"attack_range":1.0,"attack_range_source":1.0,"minimum_attack_range":0.0,"minimum_attack_range_source":0.0,"vision_range":10.0,"vision_range_source":10.0,"delay_between_shots_ms":1000.0,"pre_attack_delay_ms":0.0,"firing_duration_ms":0.0,"attack_period_ticks":10,"pre_attack_ticks":0,"firing_duration_ticks":0,"member_damage":1,"member_health":100,"member_count":1,"formation_positions":[Vector3.ZERO],"provenance":{}}
func _check(label:String,condition:bool)->void:
	if condition:passed+=1
	else:failed+=1;push_error("QUEUE_BANNER_RESPAWN_BODY_RUNTIME_FAIL "+label)
