extends SceneTree
const Sim=preload("res://src/retail_slice/retail_slice_sim.gd")
const EXPECTED:=36
var passed:=0;var failed:=0
func _initialize()->void:call_deferred("_run")
func _run()->void:
	var sim:=_sim();var slave:=sim.entities[10] as Dictionary;sim.selected_ids=[10];sim._attach_slaved_update_contract(slave,_slave(true))
	_check("slaved_typed_attaches",slave.has("slaved_update"));_check("mark_unselectable_applied",bool(slave.get("unselectable",false)) and not sim.selected_ids.has(10));_check("attack_range_preserved",float((slave["slaved_update"] as Dictionary).get("attack_range_source",0.0))==100.0);_check("attack_range_is_executable",not ((slave["slaved_update"] as Dictionary).get("unsupported_semantics",[]) as Array).has("unsupported_slave_semantic:AttackRange"));_check("guard_wander_is_executable",not ((slave["slaved_update"] as Dictionary).get("unsupported_semantics",[]) as Array).has("unsupported_slave_semantic:GuardWanderRange"));_check("presentation_receipted",((slave["slaved_update"] as Dictionary).get("unsupported_semantics",[]) as Array).has("presentation_binding:FadeTime"))
	var bind_draws:=sim.logic_random_draws;_check("bind_accepts",bool(sim.bind_slave(10,50).get("ok",false)));_check("bind_consumes_exact_logic_rng_draw",sim.logic_random_draws==bind_draws+1);_check("bind_preserves_slave_team",int(slave.get("team",-1))==0);var first_guard:=Vector2((slave["slaved_update"] as Dictionary).get("guard_position",Vector2.ZERO));_check("initial_guard_pin_uses_guard_max_radius",is_equal_approx(first_guard.distance_to(Vector2(8.5,10)),42.0))
	(sim.entities[20] as Dictionary)["position"]=Vector2(100,10);(sim.structures[50] as Dictionary)["target_id"]=20;(sim.structures[50] as Dictionary)["target_kind"]="battalion";sim._step_slaved_updates();var follow:=Vector2(slave.get("destination",Vector2.ZERO));_check("master_victim_follow",follow.x>10.0 and is_equal_approx(follow.y,10.0));_check("master_victim_clamped_from_master",is_equal_approx(follow.distance_to(Vector2(10,10)),10.0));(sim.structures[50] as Dictionary)["target_id"]=0
	slave["position"]=Vector2(100,100);slave["target_id"]=20;slave["order_kind"]="attack";var return_draws:=sim.logic_random_draws;sim._step_slaved_updates();_check("leash_clears_target",int(slave.get("target_id",99))==0);var return_point:=Vector2(slave.get("destination",Vector2.ZERO));_check("later_reroll_uses_guard_wander_radius",is_equal_approx(return_point.distance_to(first_guard),1.5));_check("return_consumes_exact_logic_rng_draw",sim.logic_random_draws==return_draws+1);var pinned_return_draws:=sim.logic_random_draws;sim._step_slaved_updates();_check("active_return_does_not_reroll_each_tick",sim.logic_random_draws==pinned_return_draws)
	var arrival_ticks:=0
	while arrival_ticks<4096 and (not (slave.get("route",[]) as Array).is_empty() or Vector2(slave.get("position",Vector2.ZERO)).distance_to(return_point)>0.001):
		sim._step_slaved_updates();sim._step_route(slave);arrival_ticks+=1
	var arrived_position:=Vector2(slave.get("position",Vector2.ZERO));var arrived_policy:=slave.get("slaved_update",{}) as Dictionary;var arrived_guard:=Vector2(arrived_policy.get("guard_position",Vector2.ZERO));var leash_local:=float(arrived_policy.get("leash_range_source",0.0))*0.1
	_check("physical_return_route_completes",arrival_ticks<4096 and (slave.get("route",[]) as Array).is_empty())
	_check("physical_return_arrives_at_sealed_point",arrived_position.distance_to(return_point)<=0.001)
	_check("physical_return_clears_beyond_guard_range",arrived_position.distance_to(arrived_guard)<=leash_local)
	_check("physical_return_keeps_target_cleared_and_does_not_repin",int(slave.get("target_id",99))==0 and Vector2(slave.get("destination",Vector2.ZERO)).is_equal_approx(return_point))
	_check("physical_return_consumes_no_extra_logic_rng",sim.logic_random_draws==pinned_return_draws)
	(sim.structures[50] as Dictionary)["position"]=Vector2(20,10);sim._step_slaved_updates();_check("guard_anchor_tracks_master",Vector2((slave["slaved_update"] as Dictionary).get("guard_position",Vector2.ZERO)).is_equal_approx(first_guard+Vector2(10,0)))
	(sim.structures[50] as Dictionary)["health"]=0;sim._step_slaved_updates();_check("master_death_kills_authored_slave",int(slave.get("health",1))==0)
	var survivor:=sim.entities[11] as Dictionary;sim._attach_slaved_update_contract(survivor,_slave(false));sim.bind_slave(11,51);(sim.structures[51] as Dictionary)["health"]=0;sim._step_slaved_updates();_check("die_false_survives",int(survivor.get("health",0))>0);_check("die_false_unbinds",int((survivor["slaved_update"] as Dictionary).get("master_id",1))==0)
	var opaque:={};sim._attach_slaved_update_contract(opaque,{"module":"SlavedUpdate","extraction":"opaque","fields":{}});_check("opaque_slave_fails_closed",not opaque.has("slaved_update"))
	var fortress:=sim.structures[60] as Dictionary;sim._attach_castle_upgrade_contract(fortress,_castle("WALL_RADIUS"));_check("castle_typed_attaches",(fortress.get("castle_upgrade_contracts",[]) as Array).size()==1);_check("wall_radius_define_resolves",float(((fortress.get("castle_upgrade_contracts",[]) as Array)[0] as Dictionary).get("wall_upgrade_radius_source",0))==500.0);var grant:=sim.apply_castle_upgrade_trigger(60,"Upgrade_Trigger");_check("castle_trigger_accepts",bool(grant.get("ok",false)));_check("fortress_gets_real_upgrade",(fortress.get("completed_upgrades",[]) as Array).has("Upgrade_Real"));_check("owned_pieces_get_real_upgrade",(sim.structures[61].get("completed_upgrades",[]) as Array).has("Upgrade_Real") and (sim.structures[62].get("completed_upgrades",[]) as Array).has("Upgrade_Real"));sim._apply_castle_upgrade_grants(fortress,"Upgrade_Trigger");_check("queue_integration_is_idempotent",(fortress.get("completed_upgrades",[]) as Array).count("Upgrade_Real")==1);_check("unknown_trigger_fails_closed",String(sim.apply_castle_upgrade_trigger(60,"Upgrade_Unknown").get("reason",""))=="trigger-not-authored")
	var unresolved:={};sim._attach_castle_upgrade_contract(unresolved,_castle("MISSING_RADIUS"));_check("unresolved_radius_receipted",((((unresolved.get("castle_upgrade_contracts",[]) as Array)[0] as Dictionary).get("unsupported_semantics",[]) as Array).has("unresolved_wall_upgrade_radius:MISSING_RADIUS")))
	var snap:=sim.snapshot();var hash:=sim.state_hash();var restored:=_sim();_check("snapshot_restore",restored.restore(snap));_check("hash_restore",restored.state_hash()==hash)
	print("SLAVED_CASTLE_UPGRADE_RUNTIME_RESULT passed=%d failed=%d"%[passed,failed]);quit(0 if failed==0 and passed==EXPECTED else 1)
func _slave(die:bool)->Dictionary:return {"module":"SlavedUpdate","extraction":"typed","fields":{"LeashRange":{"value":250.0},"GuardMaxRange":{"value":420.0},"GuardWanderRange":{"value":15.0},"AttackRange":{"value":100.0},"UseSlaverAsControlForEvaObjectSightedEvents":{"value":true},"DieOnMastersDeath":{"value":die},"MarkUnselectable":{"value":true},"GuardPositionOffset":{"value":{"x":-15.0,"y":0.0,"z":0.0}},"FadeOutRange":{"value":20.0},"FadeTime":{"milliseconds":1000}}}
func _castle(radius:String)->Dictionary:return {"module":"CastleUpgrade","extraction":"typed","fields":{"TriggeredBy":{"value":"Upgrade_Trigger"},"Upgrade":{"value":"Upgrade_Real"},"WallUpgradeRadius":{"define":radius,"expression":radius}}}
func _sim()->RetailSliceSim:
	var unit_rules:={};for oid in [Sim.SOLDIER_OBJECT_ID,Sim.SOLDIER_HORDE_ID,Sim.ARCHER_OBJECT_ID,Sim.TOWER_GUARD_OBJECT_ID,Sim.KNIGHT_OBJECT_ID]:unit_rules[oid]=_rule()
	var s:RetailSliceSim=Sim.new();s.setup({}, {"unit_rules":unit_rules,"source_unit_scale":0.1,"castle_upgrade_radius_defines":{"WALL_RADIUS":500.0}});s.ai_enabled=false;s.base_loop_enabled=false;s.entities.clear();s.structures.clear();s.entities[10]=_unit(10,0);s.entities[11]=_unit(11,0);s.entities[20]=_unit(20,2);s.structures[50]={"id":50,"team":1,"health":100,"position":Vector2(10,10)};s.structures[51]={"id":51,"team":1,"health":100,"position":Vector2.ZERO};s.structures[60]={"id":60,"team":0,"health":100,"position":Vector2.ZERO,"completed_upgrades":[],"castle_piece_structure_ids":[61,62]};s.structures[61]={"id":61,"team":0,"health":100,"completed_upgrades":[]};s.structures[62]={"id":62,"team":0,"health":100,"completed_upgrades":[]};return s
func _unit(id:int,team:int)->Dictionary:return {"id":id,"team":team,"health":100,"maximum_health":100,"member_maximum_health":100,"member_health":[100],"position":Vector2.ZERO,"destination":Vector2.ZERO,"category":"infantry","kind_of":["INFANTRY"],"state":"idle","target_id":0,"target_kind":"battalion","route":[],"route_cells":[],"timed_modifiers":{},"completed_upgrades":[],"command_points":0,"speed":1.0,"acceleration":1.0,"braking":1.0,"current_speed":0.0,"facing":Vector2.RIGHT}
func _rule()->Dictionary:return {"horde_id":Sim.SOLDIER_HORDE_ID,"category":"infantry","speed":1.0,"speed_source":10.0,"acceleration":1.0,"acceleration_source":10.0,"turn_rate_degrees_per_second":180.0,"braking":1.0,"braking_source":10.0,"attack_range":1.0,"attack_range_source":1.0,"minimum_attack_range":0.0,"minimum_attack_range_source":0.0,"vision_range":10.0,"vision_range_source":10.0,"delay_between_shots_ms":1000.0,"pre_attack_delay_ms":0.0,"firing_duration_ms":0.0,"attack_period_ticks":10,"pre_attack_ticks":0,"firing_duration_ticks":0,"member_damage":1,"member_health":100,"member_count":1,"formation_positions":[Vector3.ZERO],"provenance":{}}
func _check(label:String,condition:bool)->void:
	if condition:passed+=1
	else:failed+=1;push_error("SLAVED_CASTLE_UPGRADE_RUNTIME_FAIL "+label)
