extends SceneTree
const Sim=preload("res://src/retail_slice/retail_slice_sim.gd")
const EXPECTED:=21
var passed:=0;var failed:=0
func _initialize()->void:call_deferred("_run")
func _run()->void:
	var sim:=_sim();var owner:=sim.structures[50] as Dictionary;sim._attach_spawn_behavior_contract(owner,_spawn());sim._step_spawn_behaviors();var spawned:=(owner["spawn_behavior"] as Dictionary).get("spawned_ids",[]) as Array
	_check("initial_burst_exact",spawned.size()==2)
	if spawned.size()<2:print("SPAWN_STEALTH_RUNTIME_RESULT passed=%d failed=%d"%[passed,failed]);quit(1);return
	_check("templates_rotate",String((sim.entities[int(spawned[0])] as Dictionary).get("unit_type",""))==Sim.SOLDIER_HORDE_ID and String((sim.entities[int(spawned[1])] as Dictionary).get("unit_type",""))==Sim.ARCHER_OBJECT_ID);_check("spawn_ownership",int((sim.entities[int(spawned[0])] as Dictionary).get("team",-1))==0);_check("share_upgrades",((sim.entities[int(spawned[0])] as Dictionary).get("completed_upgrades",[]) as Array).has("Upgrade_Shared"))
	(sim.entities[int(spawned[0])] as Dictionary)["health"]=0;sim.tick();_check("replacement_not_early",((owner["spawn_behavior"] as Dictionary).get("spawned_ids",[]) as Array).size()==1);sim.advance(2);_check("replacement_not_at_due_frame",((owner["spawn_behavior"] as Dictionary).get("spawned_ids",[]) as Array).size()==1);sim.tick();_check("replacement_exact_due_plus_one",((owner["spawn_behavior"] as Dictionary).get("spawned_ids",[]) as Array).size()==2)
	var unknown:={"id":51,"team":0,"health":100,"position":Vector2.ZERO,"completed_upgrades":[]};sim._attach_spawn_behavior_contract(unknown,{"module":"SpawnBehavior","extraction":"typed","fields":{"SpawnNumber":{"value":1},"SpawnReplaceDelay":{"milliseconds":100},"SpawnTemplateName":{"value":["MissingTemplate"]}}});sim.structures[51]=unknown;sim._step_spawn_behaviors();_check("unknown_template_fails_closed",((unknown["spawn_behavior"] as Dictionary).get("spawned_ids",[]) as Array).is_empty());_check("unknown_template_receipted",((unknown["spawn_behavior"] as Dictionary).get("unsupported_semantics",[]) as Array).has("unresolved_spawn_template:MissingTemplate"))
	owner["health"]=0;sim.tick();_check("required_spawner_kills_children",((owner["spawn_behavior"] as Dictionary).get("spawned_ids",[]) as Array).is_empty())
	var opaque:={};sim._attach_spawn_behavior_contract(opaque,{"module":"SpawnBehavior","extraction":"opaque","fields":{}});_check("opaque_spawn_fails_closed",not opaque.has("spawn_behavior"))
	var hidden:=sim.entities[20] as Dictionary;sim._attach_stealth_update_contract(hidden,_stealth());_check("stealth_contract_attaches",hidden.has("stealth_update"));sim.tick();_check("stealth_delay_not_early",not sim._stealth_active(hidden));sim.tick();_check("stealth_activates_exact_delay",sim._stealth_active(hidden));hidden["destination"]=Vector2(55,0);sim.tick();_check("moving_reveals",not sim._stealth_active(hidden));hidden["position"]=Vector2(55,0);hidden["destination"]=Vector2(55,0);sim._spatial_sync(hidden);sim.advance(2);_check("stealth_rearms_after_delay",sim._stealth_active(hidden));var enemy:=sim.entities[21] as Dictionary;enemy["position"]=Vector2(55.5,0);enemy["destination"]=Vector2(55.5,0);sim._spatial_sync(enemy);sim.tick();_check("anyone_range_reveals",not sim._stealth_active(hidden));hidden["position"]=Vector2(60,0);hidden["destination"]=Vector2(60,0);enemy["position"]=Vector2(100,0);enemy["destination"]=Vector2(100,0);sim._spatial_sync(hidden);sim._spatial_sync(enemy);sim.advance(2);_check("stealth_returns_after_enemy_leaves",sim._stealth_active(hidden));_check("opacity_receipted",((hidden["stealth_update"] as Dictionary).get("unsupported_semantics",[]) as Array).has("presentation_or_unresolved_stealth_semantic:FriendlyOpacityMin"))
	owner["health"]=100;var snap:=sim.snapshot();var hash:=sim.state_hash();var restored:=_sim();_check("snapshot_restore",restored.restore(snap));_check("hash_restore",restored.state_hash()==hash)
	print("SPAWN_STEALTH_RUNTIME_RESULT passed=%d failed=%d"%[passed,failed]);quit(0 if failed==0 and passed==EXPECTED else 1)
func _spawn()->Dictionary:return {"module":"SpawnBehavior","extraction":"typed","fields":{"SpawnNumber":{"value":2},"InitialBurst":{"value":2},"SpawnReplaceDelay":{"milliseconds":200},"SpawnTemplateName":{"value":[Sim.SOLDIER_HORDE_ID,Sim.ARCHER_OBJECT_ID]},"SpawnedRequireSpawner":{"value":true},"ShareUpgrades":{"value":true},"FadeInTime":{"milliseconds":100}}}
func _stealth()->Dictionary:return {"module":"StealthUpdate","extraction":"typed","fields":{"StealthDelay":{"milliseconds":200},"FriendlyOpacityMin":{"ratio":0.1},"FriendlyOpacityMax":{"ratio":0.6},"StartsActive":{"value":true},"StealthForbiddenConditions":{"value":["MOVING","ATTACKING"]},"DetectedByAnyoneRange":{"value":10.0}}}
func _sim()->RetailSliceSim:
	var unit_rules:={};for id in [Sim.SOLDIER_OBJECT_ID,Sim.SOLDIER_HORDE_ID,Sim.ARCHER_OBJECT_ID,Sim.TOWER_GUARD_OBJECT_ID,Sim.KNIGHT_OBJECT_ID]:unit_rules[id]=_rule()
	var s:RetailSliceSim=Sim.new();s.setup({}, {"unit_rules":unit_rules,"source_unit_scale":0.1});s.ai_enabled=false;s.base_loop_enabled=false;s.entities.clear();s.structures.clear();s.entities[20]=_unit(20,0);s.entities[20]["position"]=Vector2(50,0);s.entities[20]["destination"]=Vector2(50,0);s.entities[21]=_unit(21,1);s.entities[21]["position"]=Vector2(100,0);s.entities[21]["destination"]=Vector2(100,0);s.structures[50]={"id":50,"team":0,"health":100,"position":Vector2.ZERO,"completed_upgrades":["Upgrade_Shared"]};return s
func _unit(id:int,team:int)->Dictionary:return {"id":id,"team":team,"health":100,"maximum_health":100,"member_maximum_health":100,"member_health":[100],"position":Vector2.ZERO,"destination":Vector2.ZERO,"category":"infantry","state":"idle","target_id":0,"target_kind":"battalion","route":[],"route_cells":[],"current_speed":0.0,"speed":0.0,"attack_cooldown":0,"attack_move":false,"order_kind":"","auto_acquire_enabled":false,"timed_modifiers":{},"completed_upgrades":[]}
func _rule()->Dictionary:return {"horde_id":Sim.SOLDIER_HORDE_ID,"category":"infantry","speed":1.0,"speed_source":10.0,"acceleration":1.0,"acceleration_source":10.0,"turn_rate_degrees_per_second":180.0,"braking":1.0,"braking_source":10.0,"attack_range":1.0,"attack_range_source":1.0,"minimum_attack_range":0.0,"minimum_attack_range_source":0.0,"vision_range":10.0,"vision_range_source":10.0,"delay_between_shots_ms":1000.0,"pre_attack_delay_ms":0.0,"firing_duration_ms":0.0,"attack_period_ticks":10,"pre_attack_ticks":0,"firing_duration_ticks":0,"member_damage":1,"member_health":100,"member_count":1,"formation_positions":[Vector3.ZERO],"provenance":{}}
func _check(label:String,condition:bool)->void:
	if condition:passed+=1
	else:failed+=1;push_error("SPAWN_STEALTH_RUNTIME_FAIL "+label)
