extends SceneTree
const Sim=preload("res://src/retail_slice/retail_slice_sim.gd")
const Audio=preload("res://src/retail_slice/retail_slice_audio.gd")
const EXPECTED:=21
var passed:=0;var failed:=0
func _initialize()->void:call_deferred("_run")
func _run()->void:
	var sim:=_sim();var unit:=sim.entities[1] as Dictionary;sim._attach_model_condition_sound_selector(unit,_model());sim._attach_random_sound_selector(unit,_random(1.0,false));sim._attach_large_group_audio_contract(unit,_group(3));_check("model_attaches",(unit.get("model_condition_sound_selectors",[]) as Array).size()==1);_check("random_attaches",unit.has("random_sound_selector"));_check("group_attaches",unit.has("large_group_audio"));var move:=sim.emit_typed_audio_intent(1,"move");_check("mounted_state_selects",String(move.get("event_id",""))=="MountedMove");_check("priority_preserved",int(move.get("priority",0))==32);_check("rng_receipt_honest",String(move.get("rng_receipt",""))=="presentation_sequence_hash_not_gameplay_rng");_check("event_emitted",String((sim.events[-1] as Dictionary).get("kind",""))=="audio.typed_selector");unit["model_conditions"]=["MOUNTED","ATTACKING"];var attack:=sim.emit_typed_audio_intent(1,"attack");_check("multi_condition_exact",String(attack.get("event_id",""))=="MountedAttack");_check("higher_state_priority",int(attack.get("priority",0))==64)
	var suppressed:=sim.entities[2] as Dictionary;sim._attach_model_condition_sound_selector(suppressed,_model());sim._attach_random_sound_selector(suppressed,_random(0.0,false));var no_sound:=sim.emit_typed_audio_intent(2,"move");_check("zero_chance_suppresses",String(no_sound.get("reason",""))=="random-selector-suppressed");var reroll:=sim.entities[3] as Dictionary;sim._attach_model_condition_sound_selector(reroll,_model());sim._attach_random_sound_selector(reroll,_random(1.0,true));var unsupported:=sim.emit_typed_audio_intent(3,"move");_check("frame_reroll_fails_closed",String(unsupported.get("reason",""))=="presentation-frame-reroll-unsupported");_check("frame_reroll_receipted",((reroll["random_sound_selector"] as Dictionary).get("unsupported_semantics",[]) as Array).has("reroll_every_frame_requires_presentation_frame_clock"))
	sim._attach_large_group_audio_contract(suppressed,_group(1));sim._attach_large_group_audio_contract(reroll,_other_group(9));var group:=sim.emit_large_group_audio_intent([1,2,3],"move");_check("highest_category_weight_wins",String(group.get("category_key",""))=="ORC MONSTER");_check("group_weight_exact",int(group.get("group_weight",0))==9);_check("group_selected_member",int(group.get("selected_entity_id",0))==3);var snap:=sim.snapshot();var restored:=_sim();_check("snapshot_restore",restored.restore(snap));var a:=sim.emit_large_group_audio_intent([1,2],"move");var b:=restored.emit_large_group_audio_intent([1,2],"move");_check("weighted_choice_restore",int(a.get("selected_entity_id",0))==int(b.get("selected_entity_id",-1)) and String(a.get("event_id",""))==String(b.get("event_id","")));_check("weighted_state_hash",sim.state_hash()==restored.state_hash())
	var audio:RetailSliceAudio=Audio.new();audio.playback_enabled=false;get_root().add_child(audio);audio.sync_events(sim.events);_check("audio_core_consumes",audio.typed_selector_intents.size()>=2);var last:=audio.typed_selector_intents[-1] as Dictionary;_check("audio_core_preserves_event",String(last.get("event_id",""))==String((sim.events[-1] as Dictionary).get("event_id","")));_check("audio_core_preserves_receipt",String(last.get("rng_receipt",""))=="presentation_sequence_hash_not_gameplay_rng");audio.queue_free();print("TYPED_AUDIO_SELECTOR_RUNTIME_RESULT passed=%d failed=%d"%[passed,failed]);quit(0 if failed==0 and passed==EXPECTED else 1)
func _model()->Dictionary:return {"module":"ModelConditionSoundSelectorClientBehavior","extraction":"typed","fields":{"SoundState":[{"conditions":["MOUNTED"],"sounds":{"VoiceMove":{"value":"MountedMove"},"VoiceSelect":{"value":"MountedSelect"},"VoicePriority":{"value":32}},"line":10},{"conditions":["MOUNTED","ATTACKING"],"sounds":{"VoiceAttack":{"value":"MountedAttack"},"VoicePriority":{"value":64}},"line":20}]}}
func _random(chance:float,reroll:bool)->Dictionary:return {"module":"RandomSoundSelectorClientBehavior","extraction":"typed","fields":{"Chance":{"ratio":chance},"RerollOnEveryFrame":{"value":reroll},"VoicePriority":{"value":16}}}
func _group(weight:int)->Dictionary:return {"module":"LargeGroupAudioUpdate","extraction":"typed","fields":{"Key":{"value":["HUMAN","UNIT","INFANTRY"]},"UnitWeight":{"value":weight}}}
func _other_group(weight:int)->Dictionary:return {"module":"LargeGroupAudioUpdate","extraction":"typed","fields":{"Key":{"value":["ORC","MONSTER"]},"UnitWeight":{"value":weight}}}
func _sim()->RetailSliceSim:
	var rules:={}
	for id in [Sim.SOLDIER_OBJECT_ID,Sim.SOLDIER_HORDE_ID,Sim.ARCHER_OBJECT_ID,Sim.TOWER_GUARD_OBJECT_ID,Sim.KNIGHT_OBJECT_ID]:rules[id]=_rule()
	var s:RetailSliceSim=Sim.new();s.setup({}, {"unit_rules":rules});s.ai_enabled=false;s.base_loop_enabled=false;s.entities.clear();s.structures.clear()
	for id in [1,2,3]:s.entities[id]={"id":id,"team":0,"health":100,"maximum_health":100,"member_health":[100],"position":Vector2.ZERO,"state":"idle","model_conditions":["MOUNTED"],"object_status":{}}
	return s
func _rule()->Dictionary:return {"horde_id":Sim.SOLDIER_HORDE_ID,"category":"infantry","speed":1.0,"speed_source":10.0,"acceleration":1.0,"acceleration_source":10.0,"turn_rate_degrees_per_second":180.0,"braking":1.0,"braking_source":10.0,"attack_range":1.0,"attack_range_source":1.0,"minimum_attack_range":0.0,"minimum_attack_range_source":0.0,"vision_range":10.0,"vision_range_source":10.0,"delay_between_shots_ms":1000.0,"pre_attack_delay_ms":0.0,"firing_duration_ms":0.0,"attack_period_ticks":10,"pre_attack_ticks":0,"firing_duration_ticks":0,"member_damage":1,"member_health":100,"member_count":1,"formation_positions":[Vector3.ZERO],"provenance":{}}
func _check(label:String,condition:bool)->void:
	if condition:passed+=1
	else:failed+=1;push_error("TYPED_AUDIO_SELECTOR_RUNTIME_FAIL "+label)
