extends SceneTree
const Sim=preload("res://src/retail_slice/retail_slice_sim.gd")
const EXPECTED:=25
var passed:=0;var failed:=0
func _initialize()->void:call_deferred("_run")
func _run()->void:
	var sim:=_sim();var source:=sim.entities[10] as Dictionary;sim._attach_give_upgrade_contract(source,_give())
	var action:=sim.request_give_upgrade(10,50,"Upgrade_Test","SpecialAbilityGiveUpgrade");_check("give_request_accepts",bool(action.get("ok",false)));_check("give_exact_delivery_tick",int(action.get("delivery_tick",0))==3);_check("give_busy_rejected",String(sim.request_give_upgrade(10,50,"Upgrade_Other").get("reason",""))=="upgrade-delivery-busy");sim.advance(2);_check("upgrade_not_early",not (sim.structures[50].get("completed_upgrades",[]) as Array).has("Upgrade_Test"));sim.advance(1);_check("upgrade_delivered",(sim.structures[50].get("completed_upgrades",[]) as Array).has("Upgrade_Test"));sim.advance(1);_check("give_action_packs_and_clears",not source.has("give_upgrade_action"));_check("give_fx_receipted",((source.get("give_upgrade_updates",[]) as Array)[0].get("unsupported_semantics",[]) as Array).has("presentation_binding:SpawnOutFX"));sim.request_give_upgrade(10,50,"Upgrade_Dead");source["health"]=0;sim.advance(3);_check("dead_source_cancels_delivery",not (sim.structures[50].get("completed_upgrades",[]) as Array).has("Upgrade_Dead"));source["health"]=100
	var opaque:={};sim._attach_give_upgrade_contract(opaque,{"module":"GiveUpgradeUpdate","extraction":"opaque","fields":{}});_check("opaque_give_fails_closed",not opaque.has("give_upgrade_updates"))
	var gate:=sim.structures[60] as Dictionary;sim._attach_gate_open_close_contract(gate,_gate());sim._attach_fake_pathfind_portal_contract(gate,_portal());_check("enemy_portal_denied",not sim.gate_portal_allows(60,20));_check("friendly_portal_allowed",sim.gate_portal_allows(60,10));var opened:=sim.request_gate_open(60,10);_check("gate_opens",bool(opened.get("ok",false)) and bool((gate["gate_behavior"] as Dictionary).get("pathing_open",false)));sim.advance(2);_check("gate_closes_exact_reset",not bool((gate["gate_behavior"] as Dictionary).get("open",true)));_check("gate_audio_receipted",((gate["gate_behavior"] as Dictionary).get("unsupported_semantics",[]) as Array).has("audio_binding:SoundOpeningGateLoop"))
	var ai_gate:=sim.structures[61] as Dictionary;sim._attach_gate_open_close_contract(ai_gate,_gate());sim._attach_ai_gate_contract(ai_gate,_ai_gate());source["position"]=Vector2(25,0);sim.tick();_check("ai_gate_trigger_opens",bool((ai_gate["gate_behavior"] as Dictionary).get("open",false)));source["position"]=Vector2(50,0);sim.advance(2);_check("ai_gate_closes_after_departure",not bool((ai_gate["gate_behavior"] as Dictionary).get("open",true)))
	var detector:=sim.entities[30] as Dictionary;var hidden:=sim.entities[20] as Dictionary;sim._attach_stealth_detector_contract(detector,_detector());hidden["stealth_until_tick"]=100;sim.tick();_check("detector_upgrade_gate_blocks",sim._stealth_active(hidden));detector["completed_upgrades"]=["Upgrade_Detect"];sim.advance(2);_check("detection_reveals_stealth",not sim._stealth_active(hidden));_check("detection_window_exact",int(hidden.get("detected_until_tick",0))==sim.tick_index+2);hidden["position"]=Vector2(100,0);sim.advance(2);_check("stealth_returns_after_detection_window",sim._stealth_active(hidden))
	var contained:=sim.entities[31] as Dictionary;sim._attach_stealth_detector_contract(contained,_detector());sim.entity_container[31]=999;detector["position"]=Vector2(100,0);hidden["position"]=Vector2.ZERO;hidden.erase("detected_until_tick");sim.tick();_check("contained_detector_gate_blocks",sim._stealth_active(hidden));_check("ring_cancel_receipted",((detector["stealth_detector_update"] as Dictionary).get("unsupported_semantics",[]) as Array).has("unsupported_ring_presentation:CancelOneRingEffect"))
	var unresolved:={};sim._attach_stealth_detector_contract(unresolved,{"module":"StealthDetectorUpdate","extraction":"typed","fields":{"DetectionRate":{"expression":"MISSING"},"DetectionRange":{"value":10}}});_check("unresolved_detector_inert",int((unresolved["stealth_detector_update"] as Dictionary).get("rate_ticks",0))==-1)
	var snap:=sim.snapshot();var hash:=sim.state_hash();var restored:=_sim();_check("snapshot_restore",restored.restore(snap));_check("hash_restore",restored.state_hash()==hash)
	print("UPGRADE_GATE_STEALTH_RUNTIME_RESULT passed=%d failed=%d"%[passed,failed]);quit(0 if failed==0 and passed==EXPECTED else 1)
func _give()->Dictionary:return {"module":"GiveUpgradeUpdate","extraction":"typed","fields":{"SpecialPowerTemplate":{"value":"SpecialAbilityGiveUpgrade"},"StartAbilityRange":{"value":15.0},"UnpackTime":{"milliseconds":100},"PreparationTime":{"milliseconds":100},"PersistentPrepTime":{"milliseconds":100},"PackTime":{"milliseconds":100},"DeliverUpgrade":{"value":true},"SpawnOutFX":{"value":"FX_Deliver"}}}
func _gate()->Dictionary:return {"module":"GateOpenAndCloseBehavior","extraction":"typed","fields":{"ResetTimeInMilliseconds":{"milliseconds":200},"OpenByDefault":{"value":false},"PercentOpenForPathing":{"value":50.0},"TimeBeforePlayingOpenSound":{"milliseconds":0},"TimeBeforePlayingClosedSound":{"milliseconds":0},"SoundOpeningGateLoop":{"value":"GateOpen"},"SoundClosingGateLoop":{"value":"GateClose"},"SoundFinishedOpeningGate":{"value":"GateOpened"},"SoundFinishedClosingGate":{"value":"GateClosed"}}}
func _portal()->Dictionary:return {"module":"FakePathfindPortalBehaviour","extraction":"typed","fields":{"AllowEnemies":{"value":false},"AllowNonSkirmishAIUnits":{"value":false}}}
func _ai_gate()->Dictionary:return {"module":"AIGateUpdate","extraction":"typed","fields":{"TriggerWidthX":{"value":200.0},"TriggerWidthY":{"value":100.0}}}
func _detector()->Dictionary:return {"module":"StealthDetectorUpdate","extraction":"typed","fields":{"DetectionRate":{"milliseconds":200},"DetectionRange":{"value":100.0},"RequiredUpgrade":{"value":"Upgrade_Detect"},"CanDetectWhileContained":{"value":false},"CancelOneRingEffect":{"value":true}}}
func _sim()->RetailSliceSim:
	var unit_rules:={};for oid in [Sim.SOLDIER_OBJECT_ID,Sim.SOLDIER_HORDE_ID,Sim.ARCHER_OBJECT_ID,Sim.TOWER_GUARD_OBJECT_ID,Sim.KNIGHT_OBJECT_ID]:unit_rules[oid]=_rule()
	var s:RetailSliceSim=Sim.new();s.setup({}, {"unit_rules":unit_rules,"source_unit_scale":0.1});s.ai_enabled=false;s.base_loop_enabled=false;s.entities.clear();s.structures.clear();s.entities[10]=_unit(10,0,Vector2.ZERO);s.entities[20]=_unit(20,1,Vector2(0.5,0));s.entities[30]=_unit(30,0,Vector2.ZERO);s.entities[31]=_unit(31,0,Vector2.ZERO);s.structures[50]={"id":50,"team":0,"health":100,"position":Vector2(1,0),"completed_upgrades":[]};s.structures[60]={"id":60,"team":0,"health":100,"position":Vector2.ZERO,"completed_upgrades":[]};s.structures[61]={"id":61,"team":0,"health":100,"position":Vector2(20,0),"completed_upgrades":[]};return s
func _unit(id:int,team:int,pos:Vector2)->Dictionary:return {"id":id,"team":team,"health":100,"position":pos,"category":"infantry","kind_of":["INFANTRY"],"completed_upgrades":[],"member_health":[100],"member_maximum_health":100,"maximum_health":100,"state":"idle","target_id":0,"attack_cooldown":0,"route":[],"destination":pos,"current_speed":0.0,"speed":0.0,"timed_modifiers":{}}
func _rule()->Dictionary:return {"horde_id":Sim.SOLDIER_HORDE_ID,"category":"infantry","speed":1.0,"speed_source":10.0,"acceleration":1.0,"acceleration_source":10.0,"turn_rate_degrees_per_second":180.0,"braking":1.0,"braking_source":10.0,"attack_range":1.0,"attack_range_source":1.0,"minimum_attack_range":0.0,"minimum_attack_range_source":0.0,"vision_range":10.0,"vision_range_source":10.0,"delay_between_shots_ms":1000.0,"pre_attack_delay_ms":0.0,"firing_duration_ms":0.0,"attack_period_ticks":10,"pre_attack_ticks":0,"firing_duration_ticks":0,"member_damage":1,"member_health":100,"member_count":1,"formation_positions":[Vector3.ZERO],"provenance":{}}
func _check(label:String,condition:bool)->void:
	if condition:passed+=1
	else:failed+=1;push_error("UPGRADE_GATE_STEALTH_RUNTIME_FAIL "+label)
